### ISSUE TITLE
SMBLibrary/Authentication/GSSAPI/SimpleProtectedNegotiationTokenInit.cs ReadMechanismTypeList

### ISSUE THREAD

**Issue by volitantns** [TalAloni/SMBLibrary#1]
For my tests , maybe the code shall be 

			int entryLength = DerEncodingHelper.ReadLength(buffer, ref offset);
			int entryEndOffset = offset + entryLength;
			while (offset < sequenceEndOffset)
			{
				tag = ByteReader.ReadByte(buffer, ref offset);

**Comment by TalAloni** [comment]
Thanks, can you provide a WireShark capture?

**Comment by TalAloni** [comment]
Thanks for bringing this to my attention, I have corrected the implementation: [https://github.com/TalAloni/SMBLibrary/commit/cd03f7c946485f76fd8f266d59eb293e37ada768](https://github.com/TalAloni/SMBLibrary/commit/cd03f7c946485f76fd8f266d59eb293e37ada768)
