### ISSUE TITLE
Small files read problem

### ISSUE THREAD

**Issue by nareshn2003** [TalAloni/SMBLibrary#100]
Hi

I made small example that reads file from my FreeNas share folder using SMBv2 but problem is SMBLibrary reads larger file than 20MB , in case of small files it gives error of FILE_DOES_NOT_EXIST in CreateFile status. 

I attached debug screenshot 
![image](https://user-images.githubusercontent.com/20838624/129710295-b88adf25-62d9-45a8-a90d-40461a91639e.png)

attached freenas storage screenshot
![image](https://user-images.githubusercontent.com/20838624/129710573-f35a9f62-7056-4f15-b038-9c6bbadacf4f.png)

code C#

```
         SMB2Client client = new SMB2Client(); // SMB2Client can be used as well
            bool isConnected = client.Connect(IPAddress.Parse("192.168.0.18"), SMBTransportType.DirectTCPTransport);
            if (isConnected)
            {
                NTStatus status = client.Login(String.Empty, "Administrator", "winner-123");
                                
                if (status == NTStatus.STATUS_SUCCESS)
                {

                    ISMBFileStore fileStore = client.TreeConnect("Nas2", out status);


                    FileStatus fileStatus;
                    string filePath = "AT8185\\e3ec214b-52ef-449f-9b3f-8192ddc5b389";
                    object fileHandle;
                    status = fileStore.CreateFile(out fileHandle, out fileStatus, filePath,
                        AccessMask.GENERIC_READ | AccessMask.SYNCHRONIZE, FileAttributes.Normal, 
                        ShareAccess.Read, CreateDisposition.FILE_OPEN,
                        CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);
              }
         }

```

Any idea what i am doing wrong ?

**Comment by TalAloni** [comment]
Did you review WireShark packet capture?
If "FreeNas" reports FILE_DOES_NOT_EXIST there's not much the library can do.

**Comment by nareshn2003** [comment]
Hi

Strange thing happend , I copy this file to root or other directory then try to read it works fine . I checked the permission and other things but all is same. 

Let me capture with wireshark.

**Comment by nareshn2003** [comment]
Hi

Attached wireshare capture. I did not find anything CreateFile response.

https://drive.google.com/file/d/1RKuR_2PymAQ8ykW3KlN1HsJ8z5qHqVZc/view?usp=sharing

Naresh

**Comment by TalAloni** [comment]
I'm not sure what you sent me but it's certainly not an SMB packet capture.

**Comment by nareshn2003** [comment]
Please enter smb2 in filter bar in wireshark.  I am not expert in wireshare :)

**Comment by nareshn2003** [comment]
https://drive.google.com/file/d/17wg-xjafFAByLBEtgERtW9ztMHi3nfKV/view?usp=sharing

I filtered the packets. Please see this file

**Comment by TalAloni** [comment]
I'm seeing both your Windows and your SMBLibrary traffic in the capture, it would have been best if you would have disconnected from the share before starting this capture.
I'm also seeing 3 successful CreateFile attempts.
BTW - which version of the library are you using?

**Comment by TalAloni** [comment]
I'm only seeing one request to a file similar to the pattern you mentioned, to a file called "AT8185\e3ec214b-52ef-449f-9b3f-8192ddc5b389"

**Comment by TalAloni** [comment]
Are you creating two handles to the same file BTW? perhaps that's your issue.

**Comment by nareshn2003** [comment]
BTW - which version of the library are you using?
> Using 1.4.6.1 from nuget.

I'm only seeing one request to a file similar to the pattern you mentioned, to a file called "AT8185\e3ec214b-52ef-449f-9b3f-8192ddc5b389"
> yes this request fails in code

Are you creating two handles to the same file BTW?
> No , i am creating only one handle.

**Comment by TalAloni** [comment]
So, to recap,
Are you saying that you see the request succeed with WireShark but the SMBLibrary report this as failure?
Does your code works when trying it against Windows Server?

**Comment by nareshn2003** [comment]
So, to recap,
Are you saying that you see the request succeed with WireShark but the SMBLibrary report this as failure?
Does your code works when trying it against Windows Server?
-> I have two box of freenas , if i copy same file to other freenas box with same configuration it works . Both has same settings and same version and same hardware and working in production mode.

**Comment by TalAloni** [comment]
So you see the request succeed with WireShark but  SMBLibrary report this as failure?
Please re-create this when you capture and see if that's indeed the case.

**Comment by nareshn2003** [comment]
Hi

Ok I tried with github copy and compiled from source code. In Debug window it shows this error during CreateFile. 

Exception thrown: 'System.ArgumentOutOfRangeException' in mscorlib.dll
Invalid SMB2 response: Not a valid Win32 FileTime.
Parameter name: fileTime
Exception thrown: 'System.ObjectDisposedException' in System.dll

**Comment by TalAloni** [comment]
Interesting, this must be one of the fields from the FreeNas reply (Create / LastWrite / LastChange).
can you provide the packet capture?

**Comment by TalAloni** [comment]
I'm now seeing that the status is STATUS_INVALID_SMB, which means that the fileStatus is irrelevant.
STATUS_INVALID_SMB means that there was an issue with the server reply.

**Comment by nareshn2003** [comment]
This is Packets. 

https://drive.google.com/file/d/1zb4GQInvRdkSKYebR2azcc26tGJjQYUl/view?usp=sharing

**Comment by TalAloni** [comment]
Now we're getting somewhere,
I'm seeing that the value of the LastAccess field in the reply is 0xFFFFFFFFFFFFFF7F,
according to the [specs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/2c57429b-fdd4-488f-b5fc-9e4cf020fcdf) this field "represents the number of 100-nanosecond intervals that have elapsed since January 1, 1601, Coordinated Universal Time (UTC)", 
So 0xFFFFFFFFFFFFFF7F represent a value that is far, far into the future (the year 58495842 if my math is right).
C# cannot represent values greater than the year 9999.

This seems like a FrerNas issue, LastAccess should have been the file creation date.

**Comment by nareshn2003** [comment]
I see i also seen in windows explorer file property last access time is wrong.  Not sure what causing it in freenas. Let me check freenas settings. Strange thing is only small size file has wrong last access time while big files has correct time. 

Thank you for your response.
