### ISSUE TITLE
CreateFile options to get file/dir info only.

### ISSUE THREAD

**Issue by h-iggs** [TalAloni/SMBLibrary#102]
I'm trying to get file or directory info only (just to determine if it already exists) I don't need to read or write etc. What options should I use for CreateFile to get a handle to use with GetFileInformation? It's odd because it sometimes works especially when I'm looking at a file in a sub folder (e.g. a\b\c\file.txt) or just the root folder (e.g. a) but when I open a\b as a folder I often get an NTStatus of STATUS_SHARING_VIOLATION. 

BTW... Thank you very much for this.

**Comment by TalAloni** [comment]
The parameters of CreateFile are pretty well documented [here](https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile).
Make sure you close the handle after use and ShareAccess.Read | ShareAccess.Write may help avoid STATUS_SHARING_VIOLATION if the file is already open and the other user of this handle did not request exclusive access.
