### ISSUE TITLE
Not enough credits issue randomly

### ISSUE THREAD

**Issue by nareshn2003** [TalAloni/SMBLibrary#105]
Hi

I am using SMBLibrary in my project has that cause Not enough credit error randomly. My software download around 90000 files per day and Uploads 30000 files per day. 

Not enough credit issue only occurs in upload files to SMB server. Error can occurs random after one or two days continuous usage. until it works fine.  To solve this error i have to reboot PC and restart software then it works fine again. 

How to trace this error ? What cause not enough credit issue ?

**Comment by TalAloni** [comment]
Not enough credits occur when the library is used incorrectly.
Make sure you do not issue more than one pending command to a client instance.

**Comment by nareshn2003** [comment]
Then why it appears after usage of more than 1 day ? If it happens one time then it will continue the error until i reboot the pc or software.

**Comment by TalAloni** [comment]
The fact that a whole day goes by without an issue does not prove that you use the library as intended.

**Comment by nareshn2003** [comment]
One more question,. 

Is it ok to upload multiple files in thread in multiple instance of SMBClient to same server ?  It cause not enough credits ?

**Comment by TalAloni** [comment]
As long as each client instance do not send a command before receiving a reply to the previous command it is OK.
You need to make sure that each client instance is using a separate connection / session.
