### ISSUE TITLE
I am not able to create a sub directory within shared path say 3 levels deep.

### ISSUE THREAD

**Issue by AbhilashKopalli** [TalAloni/SMBLibrary#106]
I am trying something like this:

RootFolder= "x"
String[] NestedDirectory= new String[] {"y","z"}

The folders y and z have to be created inside the shared folder x, and further I am trying to create a file in it. [\x\y\z\file.txt]

                   ISMBFileStore fileStore = client.TreeConnect(RootFolder, out status);

                    foreach ( string subfolder in NestedDirectory )
                    {
                        status = fileStore.CreateFile(out fileHandle, out fileStatus, subfolder,
                        AccessMask.SYNCHRONIZE | (AccessMask)DirectoryAccessMask.GENERIC_READ | (AccessMask)DirectoryAccessMask.DELETE, 0,
                        ShareAccess.Read | ShareAccess.Delete, CreateDisposition.FILE_OPEN | CreateDisposition.FILE_CREATE,
                        CreateOptions.FILE_SYNCHRONOUS_IO_NONALERT | CreateOptions.FILE_DIRECTORY_FILE, null);

                    }

The folders are not created one within the other but rather they are getting created in the shared path itself.

**Comment by TalAloni** [comment]
This is not an issue with the library - your code is simply incorrect. when creating an handle you need to specify the full path relative to the share. (e.g. '\x\y' rather than '\y')
