### ISSUE TITLE
Port 445 error and could not connect SMB

### ISSUE THREAD

**Issue by nareshn2003** [TalAloni/SMBLibrary#117]
Hi

I am using SMBLibrary as client only and Server is Linux FreeNas box with SMB Shared drive.
Total 35 PC is connected to this two Nas boxes with IP (192.168.0.17 and 192.168.0.18).

I am taking data from both server as required but in some PC after usage of 12 to 24 hours i am getting error of could not connect to 
server anymore and throws this exception in SMB2Client.ConnectSocket function during debug. 

**Only one usage of each socket address (protocol/network address/port) is normally permitted 192.168.0.17:445 ?**

If i reboot the PC and start application again everything works fine for few hours. Is there anything i am missing ?

I am using Windows 10 for clients .

**Comment by TalAloni** [comment]
I have to assume that you are doing something wrong - as you shouldn't be using port 445 on the client side,
only the server side is using port 445. the client use another port to connect to the server's port 445.

**Comment by nareshn2003** [comment]
In Library code it has two ports defined 

        public static readonly int NetBiosOverTCPPort = 139;
        public static readonly int DirectTCPPort = 445;

with NetBiosOverTCP & DirectTCPTransport flags when creating SMB client connection. So which flag should be used for client ?

**Comment by nareshn2003** [comment]
netstat produce this result with lot of TIME_WAIT state. 
netstat -ano | findstr :445 

  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    192.168.0.100:49152    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49153    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49154    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49155    192.168.0.18:445       TIME_WAIT       0
  TCP    192.168.0.100:49156    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49157    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49158    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49159    192.168.0.18:445       TIME_WAIT       0
  TCP    192.168.0.100:49160    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49161    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49162    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49163    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49164    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49165    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49166    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49167    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49168    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49169    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49170    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49170    192.168.0.18:445       TIME_WAIT       0
  TCP    192.168.0.100:49171    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49172    192.168.0.17:445       TIME_WAIT       0
  TCP    192.168.0.100:49173    192.168.0.17:445       TIME_WAIT       0
  .....
  TCP    192.168.0.100:65535    192.168.0.18:445       TIME_WAIT       0
  TCP    [::]:445               [::]:0                 LISTENING       4

Due to lot TIME_WAIT dynamic port range of port is reached to end 65535  and not accepting to connecting new client. Not sure why this TIME_WAIT happens ? Do you have any idea ?

**Comment by TalAloni** [comment]
Usually for the client the OS allocate a free port and you don't need to define any port.
Are you creating a large number of client instances?

**Comment by nareshn2003** [comment]
Hi

Ok according to this 
https://help.socketlabs.com/docs/how-to-fix-error-only-one-usage-of-each-socket-address-protocolnetwork-addressport-is-normally-permitted

When TCP connection disconnects it goes to TIME_WAIT for given interval ie. maximum 4 minutes ,it should goes away when timeout occurs. 

1) I have two PC with same windows versions of 10 1903 . 
2) One Pc removes TIME_WAIT after few minutes, other PC dont waited for  more than one hour.

May be something wrong with operating system settings. 

After google i found that if i put  m_clientSocket.Close(0) instead of  m_clientSocket.Disconnect(false)  in SMB2Clinet::Disconnect() function and dispose the client socket it immediately close the TCP connection. 

Is there correct way to do that ?

  public void Disconnect()
        {
            if (m_isConnected)
            {
                m_clientSocket.Close(0);
                m_clientSocket.Dispose();
                m_isConnected = false;
            }
        }

**Comment by TalAloni** [comment]
Calling Close will Call Dispose (see [here](https://stackoverflow.com/a/3601548))

**Comment by nareshn2003** [comment]
Ok . I made both calls and attached library and test new version 50 PC and all working fine since i added Close connection. I will remove dispose in code.

**Comment by nareshn2003** [comment]
I mean to say replace m_clientSocket.Disconnect(false) to m_clientSocket.Close(0) in code ? Is it required ?

**Comment by TalAloni** [comment]
I don't think so, see [here](https://stackoverflow.com/a/35229144)

If your tests suggest otherwise - please let me know

**Comment by alphons** [comment]
` public void Start(IPAddress serverAddress, SMBTransportType transport, bool enableSMB1, bool enableSMB2, bool enableSMB3, TimeSpan? connectionInactivityTimeout)
        {
            int port = (m_transport == SMBTransportType.DirectTCPTransport ? DirectTCPPort : NetBiosOverTCPPort);
            Start(serverAddress, transport, port, enableSMB1, enableSMB2, enableSMB3, connectionInactivityTimeout);
        }`

To make this work, change it to:

` public void Start(IPAddress serverAddress, SMBTransportType transport, bool enableSMB1, bool enableSMB2, bool enableSMB3, TimeSpan? connectionInactivityTimeout)
        {
            int port = (transport == SMBTransportType.DirectTCPTransport ? DirectTCPPort : NetBiosOverTCPPort);
            Start(serverAddress, transport, port, enableSMB1, enableSMB2, enableSMB3, connectionInactivityTimeout);
        }`

**Comment by TalAloni** [comment]
alphons - Thank you very much.
(Please don't hijack another issue though)
