### ISSUE TITLE
ipv6 support?

### ISSUE THREAD

**Issue by vip123456789** [TalAloni/SMBLibrary#119]
I hope SMBLibrary can support ipv6, thank you!

**Comment by TalAloni** [comment]
it does support IPv6

**Comment by vip123456789** [comment]
But i found it only listened the ipv4 port(445), did not listened the ipv6 port.
I can use socat to listen the ipv6 port, it works well through ipv6.

socat tcp6-listen:445,reuseaddr,fork tcp4:localhost:445

**Comment by TalAloni** [comment]
The library itself support IPv6 - but you need to bind to an IPv6 address in order for that to happen.

**Comment by vip123456789** [comment]
my "ip address" setting is "any", but i found it only listened 0.0.0.0:445, it didn't listend [::]:445.
I must use socat to listen [::]:445，so it can works well through ipv6

**Comment by vip123456789** [comment]
The "ip address" setting did not list any ipv6 addresses, so I can not to choose a ipv6 address.

**Comment by TalAloni** [comment]
The library itself support IPv6.
However, the "SMBServer" application showcasing how to use the library only list IPv4 addresses.
