### ISSUE TITLE
SMB1

### ISSUE THREAD

**Issue by HansUrschel** [TalAloni/SMBLibrary#12]
I try to get the list of the shares on mny Window 10 pro maschine. I do this:
 smb = new SMBLibrary.Client.SMB1Client();
// the IP is correct 192.168...and so on 
 smb.Connect(NetHelper.GetHostIPAdr("HU-ENTWALT"), SMBTransportType.DirectTCPTransport);
// i must use myDomain because my LoginName is "myName@myDomain" 
ntStatus = smb.Login(myDomain, myName, myPassword);
// the ntStatus is Success
Shares = smb.ListShares(out ntStatus);
// the Shares is null and if i debug the response header i see header.Status of 3221225661.
Whats wrong with my code and what is 3221225661??

**Comment by ArnieBerg** [comment]
Thank-you, Talaloni! That registry patch suggested in the link you gave was just what I needed.
