### ISSUE TITLE
SMB1Client - I get SMBLibrary.NTStatus.SEC_E_INVALID_TOKEN when trying to log in

### ISSUE THREAD

**Issue by Arnaldo221b** [TalAloni/SMBLibrary#124]
I get SMBLibrary.NTStatus.SEC_E_INVALID_TOKEN when trying to log in using SMB1Client. The following is the code i use:

```
       private SMB1Client Samba1_GetClient(string remoteServerName)
        {
            SMB1Client client = new SMB1Client();
            bool isConnected = false;

            isConnected = client.Connect(IPAddress.Parse("172.17.245.21"), SMBTransportType.DirectTCPTransport);

            if (isConnected)
            {
                NTStatus status = client.Login("MINPUBLICO", "us_resolucion", "resolucion");
                // this is where status value is "SEC_E_INVALID_TOKEN" 
                if (status == NTStatus.STATUS_SUCCESS)
                {
                    log.Info("Auth successful");
                    return client;
                }
                client.Disconnect();
                log.Warn("Auth went wrong");
                return null;
            }
            log.Warn("Not able to connect to the server");
            return null;
        }
```

I have used those credentials to access the share directory with no problem. I'm using windows 10 as my local OS where I'm developing my app. 

I don't have any problems creating clients for SMB2. I'm able to log in with no problem.

Please some help with this.

**Comment by TalAloni** [comment]
Is SMB1 enabled on your server?

**Comment by Arnaldo221b** [comment]
Yes, I do.

![image](https://user-images.githubusercontent.com/7787749/152521006-ca4b5aca-0d64-464a-9acf-402d8a1bdc21.png)

**Comment by TalAloni** [comment]
Are you using the latest version of the library?
I'm sorry but I cannot think of anything else that might prevent you to connect over SMB1 but allow you to connect over SMB2.

**Comment by TalAloni** [comment]
Your server and client are different machines, right?

**Comment by Arnaldo221b** [comment]
> Are you using the latest version of the library? I'm sorry but I cannot think of anything else that might prevent you to connect over SMB1 but allow you to connect over SMB2.

I'm using version 1.4.8.0 (Sorry for the spanish in the picture). And I totally get you, I'm also really frustated because of this.

![image](https://user-images.githubusercontent.com/7787749/152522056-d8ee803b-cdda-4cb9-851d-f132dfe2a983.png)

**Comment by Arnaldo221b** [comment]
> Your server and client are different machines, right?

Yes different machines. I'm testing directly from my visual studio 2019 in my laptop and I'm trying to connect to a Windows Server elsewhere. Actually the weird thing is that, I can access the folder no problem manually but I can do it from code.

![image](https://user-images.githubusercontent.com/7787749/152522654-f562a8ce-00ad-42e6-93e2-ae4b29e870b7.png)

![image](https://user-images.githubusercontent.com/7787749/152522706-53b5540c-d5b5-4d24-853a-b7b4fdf529ac.png)

**Comment by TalAloni** [comment]
Does SMB1 works from other clients?
How about trying to access the server from the machine that does not support SMB2 (e.g. Windows Server 2003 or Windows XP) or from an android App that does not support SMB2?

**Comment by Arnaldo221b** [comment]
> Does SMB1 works from other clients? How about trying to access the server from the machine that does not support SMB2 (e.g. Windows Server 2003 or Windows XP) or from an android App that does not support SMB2?

Don't have any other clients to test with. 

I'll leave you here the code execution.
![image](https://user-images.githubusercontent.com/7787749/152523253-cb7418e8-1984-4271-aa9d-fca3590a8ec5.png)

**Comment by TalAloni** [comment]
Given that this library was tested with many SMB1 servers, I'm 99% sure the issue is with your environment or settings.
I suggest you install a VM with an older OS or get an Android App like 'ES File Explorer' that use SMB1 and perform further testing.
