### ISSUE TITLE
Hang while create file handle to read file, not working on Alpine Container

### ISSUE THREAD

**Issue by aggo15** [TalAloni/SMBLibrary#126]
I written a program in .NET 6 to read files from a remote samba server (not under my control) using SMBLibrary 1.4.8. 

Below code works under Windows 10 version 10.0.17763 environment, but not under Alpine version 3.15. The program hang at this particular line (create file handle) without throwing any error.
```
FileStatus fileStatus;
object fileHandle;
NTStatus createFileHandleStatus = fileStore.CreateFile(out fileHandle, out fileStatus,
    fileInfo.Path,
    AccessMask.GENERIC_READ | AccessMask.SYNCHRONIZE,
    FileAttributes.Normal, ShareAccess.Read, CreateDisposition.FILE_OPEN,
    CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);
```

Dockerfile for building a self contained program that can run in Alpine environment.
```
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine3.15-amd64

ARG TARGET_PLATFORM=alpine.3.15-x64

COPY ./source /source

RUN dotnet publish -c Release --no-restore -o /binaries -r $TARGET_PLATFORM \
    --self-contained=true /p:DebugType=None /p:PublishSingleFile=true -v normal
```

Strange thing I observed is, under Alpine environment, I can see the program managed to login to samba server successfully and able to list files in folder without issue, it just not able to create file handle for reading purpose. 

Is there any dependencies required for Alpine 3.15 environment for the library to work properly? Did I miss something or this is an actual bug?

Appreciate if anyone can point me to the right direction. Thank you.

**Comment by TalAloni** [comment]
Hi,
Sounds odd, can you debug and step into the source code?

**Comment by aggo15** [comment]
I got something, it appears that `createFileHandleStatus` returned `STATUS_INVALID_PARAMETER`. Couldn't figure out what is the problem with my `.CreateFile` parameters though, I'm using the example provided in the repo.

**Comment by TalAloni** [comment]
What is the value of 'fileInfo.Path' under each platform?

**Comment by aggo15** [comment]
It is a full UNC path for both Windows and Alpine. Example `\\servername\directory\filename`.

**Comment by TalAloni** [comment]
The 'CreateFile' path shouldn't contain the server name and share name.

**Comment by aggo15** [comment]
I see now. I did some testing and it turns out that full path works on Windows only, not for Alpine. Passed in file name to `CreateFile` in Alpine and the code work as expected. Guess I need to make some changes to my code.

Thank you @TalAloni. I'll close this issue.
