### ISSUE TITLE
MechanismList MIC has incorrect type

### ISSUE THREAD

**Issue by softworkz** [TalAloni/SMBLibrary#13]
Hi,

first - thank you very much for publishing this interesting library.

I'm trying to use this library for client access using the code from issue #9.

I tried to connect to 
- a Linux machine with Samba (Smb2Client)
- a Windows 2003 Server/PDC in a Domain (Smb1Client)
- a windows 2016 Server in another Domain (Smb2Client)

I'm always ending up here:

https://github.com/TalAloni/SMBLibrary/blob/86afb5af33b3e14aa87d96201563c89346d07f0b/SMBLibrary/Authentication/GSSAPI/SPNEGO/SimpleProtectedNegotiationTokenInit.cs#L176

In all cases, the tag is not DerEncodingTag.ByteArray but DerEncodingTag.Sequence instead.

I can't imagine an explanation for this. It's really weird that it happens in all 3 cases. These cases are different otherwise (different buffer length, different parsed mechanisms).

When I ignore the exception, all subsequent operations against the Samba machine are successful (but there's guest access enabled), but not for the Windows servers...

Any ideas?

**Comment by softworkz** [comment]
Thanks for the quick response.
That part is solved.

But right for the next step, I'm experiencing odd behavior again:

Smb1Client.Login always returns success, no matter if credentials are right or wrong.
Then I'm calling Smb1Client.ListShares()
- If credentials were incorrect, I get a list of shares
- If credentials were correct, ListShares returns ACCESS_DENIED
(sic!)

Smb1Client.TreeConnect() always returns ACCESS_DENIED.

**Comment by TalAloni** [comment]
My latest commit should have fixed the original issue that you reported.
please test and let me know if there are any additional issues.
please open a separate issue for each issue you encounter.
