### ISSUE TITLE
NTFileSystemAdapter unexpectedly mutates FileSystemEntry objects

### ISSUE THREAD

**Issue by Ununoctium117** [TalAloni/SMBLibrary#130]
In my implementation of IFileSystem, I am caching FileSystemEntry objects because the contents I am serving are static, so I can skip going to the filesystem most of the time.

However, in this segment:

https://github.com/TalAloni/SMBLibrary/blob/5c4b88c759f47b97e706a9ab5a86199651dfa545/SMBLibrary.Adapters/NTFileSystemAdapter/NTFileSystemAdapter.QueryDirectory.cs#L49-L56

the entries are modified, and because I return them directly from my cache, the cache is modified and all future attempts to use it result in entries with a `Name` of `"."`. With the client I'm testing with, this results in the current folder seeming to "disappear" from the parent directory after navigating back to the parent, but it may produce other, more dangerous behavior from clients that don't expect multiple directories with a name of "." in the response.

I would propose either copying the FileSystemEntry objects in NTFileSystemAdapter (ideal from an API cleanliness perspective, but a small perf hit for everyone who isn't caching these entries), or documenting that library users should not store FileSystemEntry objects that are returned from `ListEntriesInDirectory` or `GetEntry` (indicating that it's my responsibility to clone/copy the objects; no perf hit in the common case but relies on the user to read that piece of documentation for correctness).

There is clearly an easy workaround from the client side - just don't cache the entry objects or clone them before returning them - so this is a relatively low impact issue.

**Comment by TalAloni** [comment]
You have a point that the documentation here should be improved.
Please note that the NTFileSystemAdapter was meant to get things working fast, I would venture that most if not all mission critical implementations will chose to implement the INTFileStore interface. this way SMB features such as Change-Notify can be supported.

**Comment by TalAloni** [comment]
I have addressed this issue in v1.4.9 by avoiding modifications of the objects returned from the IFileSystem implementation. thanks!
