### ISSUE TITLE
Support for SMB 3.1.1

### ISSUE THREAD

**Issue by jborean93** [TalAloni/SMBLibrary#135]
Feel free to close if you wish but I was wondering whether you had any plans on supporting the SMB 3.1.1 dialect and some of the extra features it brings? I might be interested in adding support for this on the client side but I'm not sure I have enough bandwidth to do the same on the server side code.

**Comment by TalAloni** [comment]
Hi Jordan,
I don't have any such plans, and so far you are the only one requesting it.
Which SMB 3.1.1 feature do you need?

**Comment by jborean93** [comment]
The biggest feature I'm looking for with SMB 3.1.1 is the pre authentication message hash feature. This ensures that the messages that are done before authentication is completed are used as part of the signing and encryption key. The benefits of this is that it forms a MIC to ensure that the negotiate request or session setup messages weren't tampered with to force the client to use an older and potentially weaker setup.

While I don't care about this as much supporting AES GCM (compared to AES CCM with 3.0.x) is always a plus. If I find the time, would you be willing to accept a PR that implemented some of this for just the client side or would you also need the server components to be done at the same time?

**Comment by MedFehmiEBF** [comment]
@jborean93 Are you able to find the time to make this PR? I am interesting to see SMB 3.1.1 supported in this awesome library.
