### ISSUE TITLE
Kerberos Support

### ISSUE THREAD

**Issue by jborean93** [TalAloni/SMBLibrary#137]
I've got some code in C# to PInvoke both SSPI and GSSAPI to provide support for Kerberos, either directly or through Negotiate. I'm happy to try and bring it across here so that people using this library could authenticate not just with NTLM but also with Kerberos. Would you be interested in such a thing?

For Windows this is dead simple and can pretty much replace the existing NTLM code you have today. Non-Windows is a bit more difficult as you aren't guaranteed to have a GSSAPI implementation present, or even NTLM in that GSSAPI implementation.

My thoughts if you are interested in such a thing would be to:

* Add 2 authentication mechanisms to `AuthenticationMethod`
  * `Kerberos` - supports only pure Kerberos through SSPI or GSSAPI
  * `Negotiate` - supports Kerberos with a fallback to NTLM
* Set the default for `Login` on the SMB Client to `Negotiate`
* On Windows these 2 methods will use SSPI directly, others work as they do today
* On non-Windows
  * `Kerberos` - will fail if GSSAPI is not present use `Kerberos` if it is
  * `Negotiate` - will use NTLM if GSSAPI is not present and use `Negotiate` through GSSAPI if it is
  * `NTLM*` - will continue to use the NTLM code already present

The tricky part is that last step. Technically it means that on non-Windows the new default could mean that NTLM is no longer used as it requires another package to be installed. Personally I think it's a good thing for people to explicitly opt into using NTLM if they still need that but I'm aware of the poor UX it might be. The alternative is to keep the default to `NTLMv2` and have it act the same as it does today and have your user's specify `Kerberos` or `Negotiate` if they wish to use GSSAPI/SSPI. This is nice from a continuity perspective but it means your defaults may not be as secure as they should be.

Interested to hear your thoughts as I would love to be able to use this library but Kerberos auth support is a pretty important feature for my use case.

**Comment by TalAloni** [comment]
Hi Jordan,
Please note that SMBLibrary is extensible,
Kerberos support, as well as other authentication mechanisms, could be used without changing the code of SMBLibrary.
All you need is a Kerberos implementation which implements IGSSMechanism.

**Comment by jborean93** [comment]
Thanks, I’ll have a look into that. Would you consider adding support for it if I was to make a pull request or do you prefer to keep it separate?

**Comment by TalAloni** [comment]
I'll definitely consider the Windows implementation.
