### ISSUE TITLE
Provide an async API

### ISSUE THREAD

**Issue by wertzui** [TalAloni/SMBLibrary#139]
I just found this great SMB implementation which seems to be the underlying library for a lot of other libraries which interact with SMB shares.

However one thing, I noticed is that (at least for the client) it does not provide an `async` API.
If my findings are correct, then all network related tasks are using a `Socket` at their base.
Since .Net 6 `Socket` has `async` methods that return a `ValueTask<T>` which could be used.

Are there any plans to implement an `async` API?

**Comment by TalAloni** [comment]
Thanks,
I have no such plans ATM - however, I did open source the library so other developers will be able to improve and optimize the library, so if this is something you think will benefit your project, you're welcome to implement it and provide benchmark showing the improvement you were able to achieve.
