### ISSUE TITLE
Should create a ISMBFileStore streaming file read method.

### ISSUE THREAD

**Issue by nddipiazza** [TalAloni/SMBLibrary#14]
By only supporting a read to byte[], causes out of memory situations on large files.
we should provide a  `ReadStream` method that provides the stream to the data, or a `WriteToOutputStream` method.

**Comment by TalAloni** [comment]
You are missing multiple important points:
1. The INTFileStore API is designed to match the Windows Native API.
2. In 5 years of working with the library (and some very large files) I did not have a single issue with RAM usage.
3. Using Streams does not magically reduce RAM usage.

I suggest you look for the real reason you are getting "out of memory".

**Comment by nddipiazza** [comment]
for a simple use case, try to load a 10G file with a system with 6G available ram. you cannot load it all into a byte array, the system will crash with out of memory.

if you store an entire file into `byte[]` then you will use up the amount of ram equivalent to that file size. on a system with limited ram, you will run out of memory easily.

streaming on the other hand will not at any point store the entire file into the ram instead streams it to the consumer of the data so they can access it incrementally.

**Comment by nddipiazza** [comment]
ah that makes sense. i didn't look closely enough to see that you don't load the whole file at once. That was the piece I was missing.
