### ISSUE TITLE
Deleting large files

### ISSUE THREAD

**Issue by Psai** [TalAloni/SMBLibrary#140]
Hi,

Hopefully this isn't something that has been answered before, although i'd be surprised if it hasn't. I did look through the issues and google, but didn't find anything on the topic.

I'm trying to delete files using the example given in the documentation, however it doesn't seem to work for files larger than about 7mb and i'm struggling to work out why. 

Here's the code that i'm using below, which works flawlessly with files under approximately 9mb (exact limit is unknown):

`status = fileStore.CreateFile(out fileHandle, out fileStatus, fileName, AccessMask.DELETE, FileAttributes.Normal, ShareAccess.Delete, CreateDisposition.FILE_OPEN, CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);

                    if (status == NTStatus.STATUS_SUCCESS)
                        {
                            FileDispositionInformation fileDispositionInformation = new FileDispositionInformation();
                            fileDispositionInformation.DeletePending = true;
                            status = fileStore.SetFileInformation(fileHandle, fileDispositionInformation);
                            bool deleteSucceeded = (status == NTStatus.STATUS_SUCCESS);
                            status = fileStore.CloseFile(fileHandle);
                        }
                        status = fileStore.Disconnect();`

For files under 9mb, it works correctly, returning the status of "STATUS_SUCCESS" and fileStatus of "FILE_OPENED", even though it does.

For files over 9mb, it doesn't work correctly, and returns the status of "STATUS_SHARING_VIOLATION" and fileStatus of "FILE_DOES_NOT_EXIST", even though it does.

Any ideas? I'm not sure if this is a bug, or something that is know but just not documented.

**Comment by TalAloni** [comment]
I've successfully deleted small and large files, there is no correlation to file size.
perhaps something else is different with those files other than their size (e.g. opened by other programs)?

**Comment by Psai** [comment]
Other than size, nothing is different. They are ran through the exact same
code as the smaller fikes (which works as expected).

I was wondering if it's something to do with the max chunk size, ie having
to read/write via a stream. Those examples exist, but there's nothing
similar for deletion.

If not, I will keep investigating. Thanks for the reply.

**Comment by Psai** [comment]
I've tried changing the security and create options etc to see if that
helped, but I did also try a clone of your code too, with the same issue.

Is there any reference somewhere that you can suggest of what the different
security and creation options etc are used for?

It also took me a while to understand what the handles were used for, and
how to use them properly (presuming nice understood correctly).

As you can probably guess, I'm completely new to SMB. Maybe others as new
to the topic as me might benefit from that reference somewhere in the
future.

**Comment by Psai** [comment]
Hi again. 
I have *FINALLY* found a solution to my problem.
For some reason, if I disconnect the current SMB2Client and create a new one, it allows me to delete large files, otherwise it gives me a status of "STATUS_SHARING_VIOLATION" and fileStatus of "FILE_DOES_NOT_EXIST" for large files, whereas for smaller files it ... "just works".

anyway, i've got it working.
Thanks for the information, and the good work on the package itself. 
I really appreciate it :)

**Comment by TalAloni** [comment]
perhaps you are not closing all opened handles

**Comment by Psai** [comment]
I checked that before as I had the same thought. All handles were closed.
If this wasn't the case, it would happened for files of all sizes I presume.

Even disconnecting the filestore didn't fix the issue, it only worked after
creating a whole new client.

As I said, I'm probably doing something wrong somewhere, but I'm just glad
to have a solution now :)
