### ISSUE TITLE
After connecting Samba server, Want to show all files and folders into File Explorer

### ISSUE THREAD

**Issue by DarshitDrg** [TalAloni/SMBLibrary#141]
I am connecting successfully with the Samba server with the following code. I need to open File Explorer with the Samba server shared folder. 

`SMB2Client client = new SMB2Client();
                bool isConnected = client.Connect(IPAddress.Parse("192.168.1.169"), SMBTransportType.DirectTCPTransport);

                if (isConnected)
                {
                    NTStatus status = client.Login(String.Empty, "mint", "test12345");

                    if (status == NTStatus.STATUS_SUCCESS)
                    {
List<string> shares = client.ListShares(out status);
                        Process.Start("explorer.exe", @"\\192.168.1.169\sambashare\");

                        client.Logoff();
                    }

                    client.Disconnect();
                    Console.ReadKey();

                }`

This is not opening anything. Also, I can't access the subdirectory of that folder.

**Comment by TalAloni** [comment]
You seem to be confusing between Windows SMB Client and SMBLibrary, each of those is a separate component and you cannot start a connection with one and continue with the other.

**Comment by DarshitDrg** [comment]
@TalAloni I am looking into https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md. THis shows me how can I use samba-client. Please share any helpful link

**Comment by TalAloni** [comment]
Helpful link to do what?
if you wish to use SMBLibrary to connect to shares, those shares will not be available via Windows Explorer.
if you need a share to be available via Windows Explorer than you will have to connect to that share via Windows. (and not SMBLibrary)
