### ISSUE TITLE
`MaxReadSize` over slow links and STATUS_INVALID_SMB

### ISSUE THREAD

**Issue by thenextman** [TalAloni/SMBLibrary#143]
If I use the [example client code](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md) for "Read large file to its end", things generally work as expected.

I noticed then when connected over a slow / high latency link; small files transfer perfectly but large files generally fail with "STATUS_INVALID_SMB". I can correct this by reading in smaller chunks (for example, instead of `client.MaxReadSize`, 64768 might work).

I'm guessing that I hit some kind of internal timeout? Is there any recommendation for tuning this; or simply try to read with ever decreasing read sizes until I'm successfully able to get the bytes? 

Thanks!!

**Comment by TalAloni** [comment]
Hi,
There is a 5 second timeout for a packet (See ResponseTimeoutInMilliseconds) - I find it unlikely you would hit that timeout on any modern network, but you may tweak the timeout or the packet size if necessary.
A better approach would be to figure out why you can't transmit 64KB under 5 seconds.

**Comment by thenextman** [comment]
Hi

Thanks for swiftly replying!

I understand what's going on with the network conditions; it's not really my problem, more just understanding the failure modes and aiming for high reliability in my application code.

I appreciate the answer. 

The related settings seem to be internal to the `SMBClient` class(es). Is there another way to configure than forking and making the proper changes?

**Comment by TalAloni** [comment]
> The related settings seem to be internal to the `SMBClient` class(es). Is there another way to configure than forking and making the proper changes?

Not really, if something is useful for a broad audience of developers I may consider it. I'm not sure that's the case here.

**Comment by thenextman** [comment]
Great. Thanks for clarifying.
