### ISSUE TITLE
SmbService.Smb2GetFileList returns null at 3rd attempt

### ISSUE THREAD

**Issue by GeoCen01** [TalAloni/SMBLibrary#144]
Hi, I'm at a roadstop, can anyone help on why TreeConnect returns an ErrorResponse when following line is called 3 times:
(MainPageViewModel.cs : 263)
`fileList = smbService.Smb2GetFileList(MySmbInfo);`

It seems that in SmbService.cs:171 the TreeConnect is returning null and the status is "-1073741616"
`var share = client.TreeConnect(pathArr[1], out status) as SMB2FileStore;`

Thank you for your help!

**To reproduce:**
1. In the UI click the green bar under File:
![image](https://user-images.githubusercontent.com/109653909/186383682-ce2fae40-c0c4-44b3-9a0e-f2f81da822fa.png)
 2. Select Cancel at the pop up:
![image](https://user-images.githubusercontent.com/109653909/186383957-a9ee3d2f-7106-4a39-ab0a-506f7dd13afd.png)
3. Repeat steps 2 times will return empty list

**Comment by TalAloni** [comment]
Hi,
This section is for reporting issues with the library - not issues with user programs.
(BTW you have not made your program source code available)
