### ISSUE TITLE
Failures in SMB2Client.Connect() Discard Socket Exception Details

### ISSUE THREAD

**Issue by JeffFerguson** [TalAloni/SMBLibrary#147]
https://github.com/TalAloni/SMBLibrary/blob/de3ea8d4eb2122bcbd1a7b37278c4a184a003ec9/SMBLibrary/Client/SMB2Client.cs#L156

Socket connection failures with the `SMB2.SMB2Client.Connect()` method are caught by a `SocketException` clause, but the exception is discarded, and `false` is returned. Information critical to understanding the reasons behind the failure, therefore, become unavailable, leading to more difficult debugging sessions. The information available in the `SocketException` should be made available, at some level, to aid in debugging.

**Comment by TalAloni** [comment]
While I agree that the Connect method currently does not provide any information why we were not able to connect to the peer and I agree that logging can be useful and can be improved, I do believe that the fact that were were not able to connect to the peer is enough information for most use cases (either the server address is incorrect or a network issue or the server is not responding correctly), I'm not sure helping to diagnose that is within the scope of the client, and there are programs like WireShark to help with such diagnostics.
