### ISSUE TITLE
Reading Large Files Using SMBLibrary And When Writing File Getting Corrupted -EXCEL

### ISSUE THREAD

**Issue by sudharajendan** [TalAloni/SMBLibrary#149]
Hello, 

As per suggestions to copy a file from src to dest path. code to read excel file and write to destination is corrupting the file.

reference code to read 
ISMBFileStore fileStore = client.TreeConnect("Shared", out status);
object fileHandle;
FileStatus fileStatus;
string filePath = "test.xlsx";
if (fileStore is SMB1FileStore)
{
    filePath = @"\\" + filePath;
}
status = fileStore.CreateFile(out fileHandle, out fileStatus, filePath, AccessMask.GENERIC_READ | AccessMask.SYNCHRONIZE, FileAttributes.Normal, ShareAccess.Read, CreateDisposition.FILE_OPEN, CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);

if (status == NTStatus.STATUS_SUCCESS)
{
    System.IO.MemoryStream stream = new System.IO.MemoryStream();
    byte[] data;
    long bytesRead = 0;
    while (true)
    {
        status = fileStore.ReadFile(out data, fileHandle, bytesRead, (int)client.MaxReadSize);
        if (status != NTStatus.STATUS_SUCCESS && status != NTStatus.STATUS_END_OF_FILE)
        {
            throw new Exception("Failed to read from file");
        }

        if (status == NTStatus.STATUS_END_OF_FILE || data.Length == 0)
        {
            break;
        }
        bytesRead += data.Length;
        stream.Write(data, 0, data.Length);
    }
}
status = fileStore.CloseFile(fileHandle);
status = fileStore.Disconnect();

reference code to write

ISMBFileStore fileStore = client.TreeConnect("Shared", out status);
string filePath = "NewFile.xlsx";
if (fileStore is SMB1FileStore)
{
    filePath = @"\\" + filePath;
}
object fileHandle;
FileStatus fileStatus;
status = fileStore.CreateFile(out fileHandle, out fileStatus, filePath, AccessMask.GENERIC_WRITE | AccessMask.SYNCHRONIZE, FileAttributes.Normal, ShareAccess.None, CreateDisposition.FILE_CREATE, CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);
if (status == NTStatus.STATUS_SUCCESS)
{
    int numberOfBytesWritten;
    byte[] data = System.Text.ASCIIEncoding.ASCII.GetBytes("Hello");
    status = fileStore.WriteFile(out numberOfBytesWritten, fileHandle, 0, data);
    if (status != NTStatus.STATUS_SUCCESS)
    {
        throw new Exception("Failed to write to file");
    }
    status = fileStore.CloseFile(fileHandle);
}
status = fileStore.Disconnect();

**Comment by sudharajendan** [comment]
Please help to read excel file and create a file and write content,as the file is getting corrupted
Thanks

**Comment by TalAloni** [comment]
Please read the documentation and follow the examples:
https://github.com/TalAloni/SMBLibrary/blob/b7f93b06b074eab8ef18288a357d66a2a2781bdc/ClientExamples.md#write-a-large-file

Large files should be written in chunks and the correct offset should be set when writing to file

**Comment by sudharajendan** [comment]
Hello,

As per suggestions to copy a file from src to dest path. code to read excel file and write to destination is corrupting the file.
Noted that Large files should be written in chunks and the correct offset should be set when writing to file.But case mantioned ,It is small size excel file with just 15KB.
