### ISSUE TITLE
Can you update this project's github license to LGPL

### ISSUE THREAD

**Issue by nddipiazza** [TalAloni/SMBLibrary#15]
Hi @TalAloni 

Regarding an  closed issue here:
https://github.com/TalAloni/SMBLibrary/issues/4

Would you mind updating the Github license to LGPL on the github project, if it's not too much trouble? 

Even though the license is on the source files, i'm getting push back about using it because the github project doesn't have a license on it, our Jenkins CI is spitting it back at us as "unlicensed." It checks the github project api for the license.

**Comment by TalAloni** [comment]
I did it just for you :)

**Comment by nddipiazza** [comment]
thank you!
