### ISSUE TITLE
Read excel file and write to destination is corrupting the file.

### ISSUE THREAD

**Issue by sudharajendan** [TalAloni/SMBLibrary#150]
Hello,

As per suggestions to copy a file from src to dest path. code to read excel file and write to destination is corrupting the file.
Noted that Large files should be written in chunks and the correct offset should be set when writing to file.But case mantioned ,It is small size excel file with just 15KB.

Also is there a sample code for a read large file from shared path in chunks 

Thank you
_Originally posted by @sudharajendan in https://github.com/TalAloni/SMBLibrary/issues/149#issuecomment-1312785555_

**Comment by sudharajendan** [comment]
Please note the size excel file is just 15KB,code to read excel file and write to destination is corrupting the file.

**Comment by sudharajendan** [comment]
Also please let know is there a sample reference for a read large file from shared path in chunks

**Comment by TalAloni** [comment]
You posted two code snippets that seem unrelated and from the code it seems you are writing "Hello" to the .xls file:
`byte[] data = System.Text.ASCIIEncoding.ASCII.GetBytes("Hello");`

Issues were meant to report issues with the library - not to report issues with programs that you write.
