### ISSUE TITLE
File is being corrupted when read from shared path and written to local system.

### ISSUE THREAD

**Issue by KetuNishant** [TalAloni/SMBLibrary#151]
Hello,

Please find below code snippet which read an excel file from windows shared folder using SMB Client. Once file being read and successfully getting response STATUS_SUCCESS on fileStore.ReadFile, trying to create an excel file and write contents inside that created excel. 

We see that excel file is being created in specified path in local system but on trying to access the excel file, Its being got corrupted. 

We also tried to read excel file contents from shared path and write to AWS bucket but getting the same error "file being corrupted". 

PFA image for the error when opening file after copied to destination..

**### FYI - The below code is able to read from source and write to destination. Upon checking, when repairing the excel file in destination, partial content is loading.**  

**Please help us to fix it. Excel file size is up to 25KB.**

Code Snippet :

    string sharedFolderPath = "testpath.com";
    string sharedFolder = @"TEMP\";
    string userNameVal = "testuser";
    string password = "testpwd";
    string dir = "DIR";    
    SMB2Client client = new SMB2Client(); // SMB2Client can be used as well
    bool isConnected = client.Connect(sharedFolderPath, SMBTransportType.DirectTCPTransport);
    if (isConnected)
    {
        NTStatus status = client.Login(dir, userNameVal, password);
        if (status == NTStatus.STATUS_SUCCESS)
        {
            ISMBFileStore fileStore = client.TreeConnect("WFS", out status);
            object fileHandle;
            FileStatus fileStatus;

           status = fileStore.CreateFile(
                out fileHandle,
                out fileStatus,
                sharedFolder + "CIOTEST.test.xlsx",
                AccessMask.GENERIC_READ | AccessMask.SYNCHRONIZE,
                SMBLibrary.FileAttributes.Normal,
                ShareAccess.Read,
                CreateDisposition.FILE_OPEN,
                CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT,
                null
            );

           if (status == NTStatus.STATUS_SUCCESS)
            {
                System.IO.MemoryStream stream = new System.IO.MemoryStream();
                byte[] data;
                long bytesRead = 0;
                while (true)
                {
                    status = fileStore.ReadFile(
                        out data,
                        fileHandle,
                        bytesRead,
                        (int)client.MaxReadSize
                    );
                    if (status != NTStatus.STATUS_SUCCESS && status != NTStatus.STATUS_END_OF_FILE)
                    {
                        throw new Exception("Failed to read from file");
                    }

                   if (status == NTStatus.STATUS_END_OF_FILE || data.Length == 0)
                    {
                        break;
                    }

                   string path = @"C:\Users\testfolder\Desktop\Newfolder\dirtest";
                    File.WriteAllBytes(path, data);
                }
                string[] arr = {  };
                return arr;
            }
            else
            {
                status = fileStore.Disconnect();
                string[] arr = {  };
                return arr;
            }
        }
        else
        {
            client.Disconnect();
            string[] arr = {  };
            return arr;
        }
    }
    else
    {
        client.Disconnect();
        string[] arr = {  };
        return arr;
    }

<img width="671" alt="Excel file" src="https://user-images.githubusercontent.com/118132345/201541388-6bf2c7f9-834f-4a4a-af66-2297688f1a4f.png">

Thank you !!

**Comment by TalAloni** [comment]
You keep overwriting the file with the latest chunk instead of appending the chunk to the file.
