### ISSUE TITLE
Split Client and Server NuGet packages

### ISSUE THREAD

**Issue by A9G-Data-Droid** [TalAloni/SMBLibrary#153]
There are quite a few forks of this library that split out the client portion and then never get updated. As someone who needs the client, I want to avoid going down that same path.

Is there any desire to split this into 2-3 projects?

- Complete (Like it is today)
- Client
- Server (Optional?)

Having 3 NuGet packages would allow users to choose what they need.

**Comment by TalAloni** [comment]
A lot of the code between the client and server is shared, there is not much overhead that would justify having both the client and server in separate packages...
