### ISSUE TITLE
移动文件

### ISSUE THREAD

**Issue by MarshalT** [TalAloni/SMBLibrary#154]
怎么样从  share1移动到 share2
 public void Move(string form, string to)
        {
            fileStore = smb.TreeConnect("Files", out var status1);
            //    if (fileStore is SMB2FileStore)
            //    {
            //        form = @"Department\BC1\" + form;
            //    }
            object fileHandle;
            FileStatus fileStatus;
            var status = fileStore.CreateFile(out fileHandle, out fileStatus, form, AccessMask.GENERIC_WRITE | AccessMask.DELETE | AccessMask.SYNCHRONIZE, FileAttributes.Normal, ShareAccess.None, CreateDisposition.FILE_OPEN, CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);

            {
                if (status == NTStatus.STATUS_SUCCESS)
                {
                    status = fileStore.SetFileInformation(fileHandle, new FileRenameInformationType2()
                    {
                        FileName = to,

                    });

                    status = fileStore.CloseFile(fileHandle);
                }

                fileStore.Disconnect();
                // smb.Logoff();
                // smb.Disconnect();
            }
        } 
这样是可以移动的，但是我需要移动到别的 share

**Comment by TalAloni** [comment]
Hi,
You need to read the entire file content from share1, and then write it to share2.
you cannot "Move" between shares without reading and writing all the data.
