### ISSUE TITLE
NTStatus - 5963778 while logining

### ISSUE THREAD

**Issue by Maxvel62** [TalAloni/SMBLibrary#155]
After successfully logging, I'm trying to log off, disconnect and log 1 more time in the same method, after what I caught a non-successful status, what does it mean? NT Status =  5963778

**Comment by TalAloni** [comment]
Hi,
Can you provide a code sample?
Are you sure about the number? 5963778?

**Comment by Maxvel62** [comment]
Thank you for a quick response, sure, here is my code
Do not pay attention on login credentials, I tested this with real one.

Invocation of method: ![изображение_2022-12-10_013633734](https://user-images.githubusercontent.com/63812081/206812247-4acff38c-be49-49a8-9bd6-1b4cd0ca27ec.png)
Login implementation: ![изображение_2022-12-10_013702693](https://user-images.githubusercontent.com/63812081/206812296-8d7ad2db-a9ff-44d1-a102-8215f766938d.png)
Logoff implementation: ![image](https://user-images.githubusercontent.com/63812081/206812329-f488d79b-81fa-4967-8c48-51f5d8c9ea86.png)

Error Status code: 
![image](https://user-images.githubusercontent.com/63812081/206812436-6bd02116-c79b-4f97-81de-014afc72cb14.png)

**Comment by TalAloni** [comment]
Can you capture the traffic using WireShark?
Do you use Windows as an SMB server?

**Comment by Maxvel62** [comment]
About traffic capturing, I haven't had much experience with WireShark yet, but I can try.
Considering SMB server, yes, I use windows and share local folder.

**Comment by ArnieBerg** [comment]
This happens to me too. I connect, login and WriteFile, close, logoff and disconnect, then go to connect again and get the error.

**Comment by TalAloni** [comment]
Reusing client instance is now possible using the latest master branch.
