### ISSUE TITLE
How I can Create a file in a specific folder / Query by fileName in a specific folder

### ISSUE THREAD

**Issue by laboua** [TalAloni/SMBLibrary#158]

**Comment by TalAloni** [comment]
CreateFile accepts path that allows you to specify where to create the folder

**Comment by laboua** [comment]
Thanks,
 Is exist a way to use a host name in connect action instead of an ip address?

**Comment by TalAloni** [comment]
Yes, there is an overload for that. (that accepts string)

**Comment by laboua** [comment]
Awesome.
Last question 😁, I would know if the library offer async methods?
