### ISSUE TITLE
how to create subfolders on shared location E.g My shared drive is Epi$ And I want to create Folders //Server/Epi$/2023/folder1 

### ISSUE THREAD

**Issue by itssharadakre** [TalAloni/SMBLibrary#159]
Hi @TalAloni 
how to create subfolders on shared location E.g My shared drive is Epi$ And I want to create Folders //Server/Epi$/2023/folder1

**Comment by TalAloni** [comment]
Like this example:
https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md
But specify the flag FILE_DIRECTORY_FILE

**Comment by itssharadakre** [comment]
@TalAloni I want to create subfolder like in Shared location I want to  create like Shared/Folder1/Folder2 Which is not working with above code.

**Comment by TalAloni** [comment]
It does. you just need to remove the Share name from the path.

**Comment by itssharadakre** [comment]
Hi @TalAloni 
I am using the same code with the FILE_DIRECTORY_FILE flag.
but I am unable to create Subfolders in my Path //Shared/Dev This is my fix path inside this path I need to create subfolders.
like  //Shared/Dev/Folder1
/Shared/Dev/Folder2
Can you help me how I can achieve this.
I have tried the same  code as suggested by you but its returning status   STATUS_OBJECT_PATH_NOT_FOUND

**Comment by itssharadakre** [comment]
@TalAloni 
In create file I am not using Shared name  
Dev/Folder2 this is I'm using in create file.

**Comment by itssharadakre** [comment]
@TalAloni  
Thanks for your Guidance Its working now.
