### ISSUE TITLE
STATUS_NOT_SUPPORTED when trying to get security info

### ISSUE THREAD

**Issue by nddipiazza** [TalAloni/SMBLibrary#16]
Hi. I am trying to get the security info for a file. 

But i keep getting status = `STATUS_NOT_SUPPORTED` when trying. 

I'm trying to get the SIDs of the effective file acls. 

Here is my example: https://github.com/nddipiazza/SambaFetcher/blob/SambaLibrary/SmbFetcher/SmbServerModule.cs

In particular here is where I'm trying to get the security information for a given file. https://github.com/nddipiazza/SambaFetcher/blob/SambaLibrary/SmbFetcher/SmbServerModule.cs#L123

I'm missing something. Can you help me figure out how to get access controls for a file?

**Comment by TalAloni** [comment]
Hi,
In the current implementatiom of NTDirectoryFileSystem, the implementations of GetSecurityInformation and SetSecurityInformation simply return STATUS_INVALID_DEVICE_REQUEST.
(According to [MS-FSA] If the object store does not implement security, the operation MUST be failed with STATUS_INVALID_DEVICE_REQUEST)

Access control for SMBLibrary is implemented at the share level and not at the file system level.
If you need file-system level support then you will have to add this functionality to your INTFileSystem implementation or update the NTDirectoryFileSystem implementation.

**Comment by TalAloni** [comment]
EDIT:
Sorry, I have now realized that you are referring to the client implementation,
SMB2FileStore.GetSecurityInformation is currently a stub that always returns STATUS_NOT_SUPPORTED
Since many file-systems do not support ACLs, I chose not to rely on file-system level access control when implementing the server (and subsequently client), is there any good reason to do so for the client?

**Comment by nddipiazza** [comment]
Hi @TalAloni unless I'm missing something significant, I need a way to get a file's acls. 

Here is how I was doing it when I was using the Windows-only solution: https://github.com/nddipiazza/SambaFetcher/blob/master/SmbFetcher/SmbServerModule.cs#L77

A little background here, I have a project here https://github.com/nddipiazza/SambaFetcher/ that can access windows shares authenticated, and supports the following:

* List files in a folder
* Download a file
* Get all of a given file's metadata including security acls.

This project only supports windows because the authenticated UNC file system access relies on the win32 DLLs.

I am trying to swap it out with yours.

But the only missing piece is the lack of security acls being listed from your client. You have an endpoint for it, but it always returns errors.

**Comment by TalAloni** [comment]
Hi,
I have implemented GetSecurityInformation for SMB1 / SMB2 clients and pushed the changes to the master branch, note that only the NTFS / ReFS file systems store owner / group / DACL information, so don't assume that the call will always be successful.

**Comment by nddipiazza** [comment]
confirmed. it works.
