### ISSUE TITLE
How query a file in sub directories and get the whole path

### ISSUE THREAD

**Issue by laboua** [TalAloni/SMBLibrary#160]
Hello,
in a shared directory we have two subdirectory example:
shared/Ok
shared/Ko
My need it's to know if my file is in Ko or Ok directory, so i want to know if it's possible to achieve that with existing actions ?

thanks in advance.

**Comment by TalAloni** [comment]
Use CreateFile to obtain a handle to the directory, you can use the FILE_DIRECTORY_FILE flag to only obtain directories.

**Comment by laboua** [comment]
But we can't use create if we don't know the path of the given file

**Comment by TalAloni** [comment]
When iterating over files in a directory, you can look at the file flags to know which one is a file and which is a directory
