### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by michelcoudron** [TalAloni/SMBLibrary#161]
Hi,
Is there a way to retrieve the actual size of the content of a file? The attribuut AllocationSize returns the 'size on disk' but that is generally greater than the actual size of the content. 

Rgds
Michel

**Comment by TalAloni** [comment]
The 'EndOfFile' property contain the actual file size.

**Comment by usama03488** [comment]
That is how you get the specific File size.
 FileInformation result;
            status2 = fileStore.GetFileInformation(out result, handle, FileInformationClass.FileAllInformation);
            if(status == NTStatus.STATUS_SUCCESS)
            {
                FileAllInformation info = (FileAllInformation)result;
                filetotalsize = info.StandardInformation.EndOfFile;
   Debug.Log("File size here:"+(filetotalsize/(1024*1024)));
            }
