### ISSUE TITLE
InvalidDataException:** 'Loading...' as soon as disk read sound ends exception is raised.

### ISSUE THREAD

**Issue by ToaRuGakusei** [TalAloni/SMBLibrary#163]
It also appears sometimes when retrieving directory listings.
Is it possible to wait for the disk to load?

[code.txt](https://github.com/TalAloni/SMBLibrary/files/10705037/code.txt)

**Comment by TalAloni** [comment]
Please provide stack track.
"InvalidDataException" means that the client received invalid (protocol) data. WireShark log will also be helpful.

**Comment by ToaRuGakusei** [comment]
Debug Log

Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Collections.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.InteropServices.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Threading.Thread.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Threading.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/TGReaderGX.dll
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Private.Uri.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Maui.Controls.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Numerics.Vectors.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.ObjectModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Private.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Memory.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Diagnostics.TraceSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Collections.NonGeneric.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Collections.Specialized.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.ComponentModel.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.ComponentModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Text.RegularExpressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Collections.Concurrent.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Reflection.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Diagnostics.Tracing.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Win32.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.Http.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.Security.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Security.Cryptography.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Formats.Asn1.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Text.Encoding.Extensions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.Numerics.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.Sockets.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.NameResolution.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Threading.ThreadPool.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Security.Claims.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Diagnostics.DiagnosticSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.Quic.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.Compression.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.Compression.Brotli.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Threading.Channels.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.NetworkInformation.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Reflection.Emit.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.Loader.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Linq.Expressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.ComponentModel.TypeConverter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Drawing.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.Serialization.Formatters.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Resources.Writer.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Xml.XDocument.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Private.Xml.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Maui.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Extensions.Logging.Abstractions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Console.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Extensions.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Extensions.Options.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Extensions.DependencyInjection.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Maui.Controls.Xaml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/SMBLibrary.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/netstandard.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.MemoryMappedFiles.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.Pipes.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Diagnostics.Process.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Diagnostics.FileVersionInfo.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Reflection.Metadata.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Collections.Immutable.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.ComponentModel.EventBasedAsync.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Data.Common.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Xml.XmlSerializer.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Transactions.Local.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Diagnostics.Contracts.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Diagnostics.TextWriterTraceListener.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.Compression.ZipFile.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.FileSystem.DriveInfo.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.FileSystem.Watcher.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.IsolatedStorage.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Linq.Queryable.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Linq.Parallel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.Requests.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.WebHeaderCollection.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.ServicePoint.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.HttpListener.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.WebSockets.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Security.Principal.Windows.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.WebClient.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.WebProxy.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.Mail.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.Ping.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Net.WebSockets.Client.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Reflection.DispatchProxy.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.CompilerServices.VisualC.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.Serialization.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.Serialization.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Threading.Overlapped.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Threading.Tasks.Parallel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Web.HttpUtility.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Xml.XPath.XDocument.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Xml.XPath.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/mscorlib.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/Microsoft.Win32.Registry.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Security.AccessControl.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Security.Permissions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Windows.Extensions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Drawing.Common.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.IO.FileSystem.AccessControl.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Threading.AccessControl.dll [External]
Thread started:  #2
Resolved pending breakpoint for 'TGReaderGX.Program.Main(System.String[])' to C:\Users\r23ry\source\repos\TGReaderGX\TGReaderGX\Platforms\iOS\Program.cs:10 [0x00000].
Loaded assembly: data-0x10ef60000 [External]
Loaded assembly: data-0x10ef74000 [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:423 [0x00000].
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Text.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Text.Encodings.Web.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:418 [0x00000].
Thread started:  #3
Thread started:  #4
Thread started:  #5
Thread started: .NET Timer #6
Thread started: <Thread Pool> #7
Thread started: .NET ThreadPool Gate #8
Thread started: <Thread Pool> #9
Loaded assembly: /private/var/containers/Bundle/Application/4861DFC0-A6B9-4E2B-AF85-A3EA3FE4B2C0/TGReaderGX.app/System.Runtime.Intrinsics.dll [External]
2023-02-10 17:26:53.535 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

Thread started: <Thread Pool> #10
2023-02-10 17:26:53.571 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

2023-02-10 17:26:53.573 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()
2023-02-10 17:26:53.573 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

Thread started: .NET Sockets #11
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
2023-02-10 17:26:54.173 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

2023-02-10 17:26:54.173 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

2023-02-10 17:26:57.719 TGReaderGX[36193:6604654] Successfully load keyboard extensions

2023-02-10 17:26:57.928 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

2023-02-10 17:26:57.928 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

2023-02-10 17:27:00.915 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

2023-02-10 17:27:00.915 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

2023-02-10 17:27:02.824 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

2023-02-10 17:27:02.824 TGReaderGX[36193:6604854] Warning: observer object was not disposed manually with Dispose()

**System.IO.InvalidDataException:** 'Loading...'

Thread finished: <Thread Pool> #13
Thread finished: <Thread Pool> #7
Thread finished: <Thread Pool> #9
スレッド 0xd はコード 0 (0x0) で終了しました。
スレッド 0x7 はコード 0 (0x0) で終了しました。
スレッド 0x9 はコード 0 (0x0) で終了しました。
Thread finished: <Thread Pool> #12
Thread finished: <Thread Pool> #10
Thread started: <Thread Pool> #15
スレッド 0xc はコード 0 (0x0) で終了しました。
スレッド 0xa はコード 0 (0x0) で終了しました。

**Comment by TalAloni** [comment]
This stack trace / issue seem to be unrelated to SMB Library, can you reproduce the issue when running outside of a container?

**Comment by ToaRuGakusei** [comment]
It works fine on Windows, so maybe SMBLibrary has nothing to do with it.
It is now possible that my environment is bad because some files do not produce the exception.
I will check the zip I am saving.

**Comment by ToaRuGakusei** [comment]
やはり、ディスクがスリープから復帰する際に例外が発生します。
先ほど送ったコードを実行すると、MemoryStreamの中身は何もなく、ファイルを読み込めていないです。

**Comment by ToaRuGakusei** [comment]
As expected, an exception occurs when the disk returns from sleep.
When I run the code I just sent, there is nothing in the MemoryStream and the file is not being read.

**Comment by ToaRuGakusei** [comment]
The wireshark logs are submitted after the disk goes to sleep.

**Comment by ToaRuGakusei** [comment]
Here are the wireshark logs.
There was some kind of error.
[log.zip](https://github.com/TalAloni/SMBLibrary/files/10705511/log.zip)

**Comment by TalAloni** [comment]
1. The CreateFile request contains an odd looking path
2. The server is returning STATUS_NETWORK_SESSION_EXPIRED (after 5 seconds)

I would investigate both issues, it doesn't look like an issue with the library but an issue with your code / environment

**Comment by ToaRuGakusei** [comment]
"動画編集" is a normal folder name.
An exception occurred as the HDD finished reading.
Once loaded, the exception is not raised.
