### ISSUE TITLE
v1.4.6.2 could handle "@" in passwords, v1.4.9 cannot now.

### ISSUE THREAD

**Issue by DamoHaynes** [TalAloni/SMBLibrary#166]
v1.4.6.2 could handle "@" in passwords, v1.4.9 cannot now. STATUS_ACCESS_DENIED is provided.

Was this international?

**Comment by TalAloni** [comment]
I don't recall making changes to that area, please double check and report exactly which version introduced this issue.

**Comment by DamoHaynes** [comment]
V1.4.8 -> V1.4.9 has a lot of updates around user and passwords, we jump to V1.4.9, but had to roll back to v1.4.6.2 due to user login issue.

**Comment by TalAloni** [comment]
Please report exactly which version introduced this issue.

**Comment by DamoHaynes** [comment]
V1.4.9

**Comment by TalAloni** [comment]
I have tested v1.4.9 and was able to perform login when the user password contained the '@' character.
Again, I don't recall making changes to that area.
Please double check your assumptions, as you did not provide enough information for a proper investigation of this issue and I have little to go on.
Are you saying that you have an issue that is not present with v1.4.8 but is present with v1.4.9?

**Comment by DamoHaynes** [comment]
Correct, Issue is in 1.4.9

**Comment by TalAloni** [comment]
But isn't in 1.4.8, right?
Can you think of anything other than the '@' sign which may trigger this issue?

**Comment by DamoHaynes** [comment]
no, that was all, just the @

**Comment by TalAloni** [comment]
Can you please state clearly whether the issue exists in 1.4.8?

**Comment by TalAloni** [comment]
I would also ask that you check out the repository and pinpoint the exact commit that cause this issue to occur.

**Comment by TalAloni** [comment]
Closing due to lack of response
