### ISSUE TITLE
Connect to a directory deeper in the directory tree

### ISSUE THREAD

**Issue by cinephos** [TalAloni/SMBLibrary#167]
How do I connect to a directory positioned deeper in the shared directory tree?

For axample:
`List<string> shares = client.ListShares(out status);` returns "Documents" as `shares[2]` item.
The following command
`ISMBFileStore fileStore = client.TreeConnect("Documents", out status);` returns `NTStatus.STATUS_SUCCESS`

However my target directory is @"Documents\Examples\Something"
How can I connect to above directory and then `fileStore = client.TreeConnect`, `fileStore.CreateFile` and `fileStore.ReadFile` ?

**Comment by TalAloni** [comment]
CreateFile(@"Examples\Something")
The CreateFile path is relative to the share.

**Comment by cinephos** [comment]
Yes!!!! I figured out the correct use! Thank you!!!
