### ISSUE TITLE
Creating a file in subfolder

### ISSUE THREAD

**Issue by dare2405** [TalAloni/SMBLibrary#169]
Hi, im trying create a txt file in a path something like this a\b\c\d.txt.
I'm using create file as in the code below and getting error STATUS_OBJECT_PATH_NOT_FOUND. Since I don't know which folder exists when creating this file, should I send request for each folder, if that folder exist or not?
First createFile for a folder, then createFile for a\b, after that createFile for a\b\c, finally createFile for a\b\c\d.txt

Is there a way to create the file in this directory one at a time without requesting to create all the folders one by one?

string filePath=@"a\b\c\d.txt";
status = fileStore.CreateFile(out fileHandle, out fileStatus, filePath, AccessMask.GENERIC_WRITE | AccessMask.SYNCHRONIZE, FileAttributes.Normal, ShareAccess.None, CreateDisposition.FILE_CREATE, CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);

**Comment by TalAloni** [comment]
Yes, you need to create each folder - it will not be done automatically.

**Comment by TalAloni** [comment]
That would be the most sensible approach. not the only one though.

**Comment by dare2405** [comment]
what are the other options?

**Comment by TalAloni** [comment]
If there is a high probability that "a\b\c\" or "a\b\c\" exists, you can skip checking the existence of "a\" for example and only do that as a fallback.
