### ISSUE TITLE
The path of the NTDirectoryFileSystem method is faulty

### ISSUE THREAD

**Issue by mghcool** [TalAloni/SMBLibrary#172]
versions: 1.4.9
OS： windows10

``` C#
// normal
new NTDirectoryFileSystem(@"E:\files")
// exception
new NTDirectoryFileSystem(@"E:\files\")
```

"\\" at the end of the path causes an access exception

**Comment by TalAloni** [comment]
Remove the trailing slash then.
If anything, the issue is with the documentation.
