### ISSUE TITLE
CreateWeakDesEncryptor method exception

### ISSUE THREAD

**Issue by mghcool** [TalAloni/SMBLibrary#174]
Version: 1.4.9

Exception method: SMBLibrary.Authentication.NTLM.CreateWeakDesEncryptor

This method is normal under .net Framework, but it cannot be used under .net Core. I made the following modifications.

``` C#
  public static ICryptoTransform CreateWeakDesEncryptor(CipherMode mode, byte[] rgbKey, byte[] rgbIV)
  {
      DES des = DES.Create();
      des.Mode = mode;
      ICryptoTransform trans = des.CreateEncryptor(rgbKey, rgbIV);
      //DESCryptoServiceProvider sm = des as DESCryptoServiceProvider;
      //MethodInfo mi = sm.GetType().GetMethod("_NewEncryptor", BindingFlags.NonPublic | BindingFlags.Instance);
      //object[] Par = { rgbKey, mode, rgbIV, sm.FeedbackSize, 0 };
      //ICryptoTransform trans = mi.Invoke(sm, Par) as ICryptoTransform;
      return trans;
  }
```

**Comment by TalAloni** [comment]
Hi,
Thanks for reporting this,
Your solution overlooked an issue with weak DES keys, I have implemented an alternative solution that should work under .NET 5.0 and .NET 6.0.

**Comment by TalAloni** [comment]
SMBLibrary v1.5.0 includes this change and should work under .NET 5.0 and .NET 6.0.
