### ISSUE TITLE
Use Integrated NTLM for client

### ISSUE THREAD

**Issue by zabulus** [TalAloni/SMBLibrary#177]
Is it possible to use integrated security for smb client? In some cases we need to have ability to connect to share using process user, password for which we do not have.

**Comment by TalAloni** [comment]
Please note that the client logic is currently cross-platform, and since Integrated Windows Authentication is only supported under Windows, integrating this code into the client is a bit of a challenge.

**Comment by zabulus** [comment]
Will you accept PR for this?

**Comment by TalAloni** [comment]
Well, it has to be done in a way that is both extensible to other authentication mechanisms (e.g. Kerberos) and does not clutter the API too much, could be nice to have of course but I'm not sure how it would be best to do. need to put some thinking into it.

**Comment by TalAloni** [comment]
I agree this should be improved, trying to find time to address this.

**Comment by TalAloni** [comment]
Thanks,
I've pushed the ability to provide custom authentication for SMB2Client to master using the IAuthenticationClient interface.
For integrated authentication I suggest to inherit from NTLMAuthenticationClient.

**Comment by zabulus** [comment]
Great! Will you publish these changes to nuget?

**Comment by TalAloni** [comment]
Yes, it's now part of v1.5.0.2
