### ISSUE TITLE
STATUS_INVALID_SMB when reading a file

### ISSUE THREAD

**Issue by rabellinonico** [TalAloni/SMBLibrary#179]
Hello,
I had a problem while using .NET 6 and SMBLibrary 1.4.9
I was reading a file and encountered a problem while reading, it returns me STATUS_INVALID_SMB.
If I read it with client.MaxReadSize it gives me STATUS_INVALID_SMB. As I changed the parameter to a number for example 65536 it works.

What could be causing the problem?

The code I used is from the ClientExamples.md file (Read large file to its end)

**Comment by TalAloni** [comment]
Without Wireshark packet capture and code it's hard to say.
You also didn't specify which SMB server you are using.

**Comment by jahales-intel** [comment]
We seem to be seeing the same issue after having updated from 1.4.8 to 1.4.9. I'll see if I can collect some more details for you and add them here later.

**Comment by rabellinonico** [comment]
> Without Wireshark packet capture and code it's hard to say.

I'm sorry but it's my client's network and I don't know how to use Wireshark...

> You also didn't specify which SMB server you are using.

My client doesn't know which SMB server is installed but I'm using the SMB2Client class (it doesn't work if I use SMB1Client).

Also I find that the maximum number I can set on the 'maxCount' parameter is 130991.

I hope this help,
Best regards

**Comment by TalAloni** [comment]
I'm sorry but it doesn't help.
Using WireShark is easy and there are many guides available online.
Are you using port 139 or port 445?
To me it sounds like the server reporting a higher number than of MaxReadSize than actually supported, a WireShark capture can help shed light on this.

**Comment by rabellinonico** [comment]
> Are you using port 139 or port 445? 

I really don't know, I use SMBTransportType.DirectTCPTransport, might it help?

> a WireShark capture can help shed light on this.

I'm installing it right now, what am I looking for?

**Comment by TalAloni** [comment]
DirectTCPTransport is port 445,
You want to capture all traffic between the client and server, usually a capture filter of "host <ip-address> port 445" does the trick.

**Comment by rabellinonico** [comment]
Ok I think I got it with `ip.addr == <SERVER IP> and tcp.port == 445`.
How do I send it to you?

**Comment by TalAloni** [comment]
those are display filters, it means that you captured and will send more information than just SMB traffic.
you can upload here or send to my email address (appear in the repo readme)

**Comment by TalAloni** [comment]
Closing due to lack of feedback
