### ISSUE TITLE
windows server backup does not work

### ISSUE THREAD

**Issue by kztao** [TalAloni/SMBLibrary#18]
![image](https://user-images.githubusercontent.com/1481448/54917351-9b123200-4f36-11e9-9249-f08c6ff6cfc5.png)

**Comment by TalAloni** [comment]
From what I've gathered Windows Server Backup uses RPC over SMB to connect to services such as 'lsarpc' and 'srvsvc' as part of the backup operation, those services are not present in SMB Library.

**Comment by TalAloni** [comment]
Edit: I was able to successfully make a backup using the 'Inherit' option.
