### ISSUE TITLE
STATUS_INVALID_SMB after idle timeout

### ISSUE THREAD

**Issue by MaksymKlos** [TalAloni/SMBLibrary#180]
I use SMB2Client and windows 10 as a server.
I found that after 15 minutes of idle, smb client disconnects from the file share, and CreateFile() returns STATUS_INVALID_SMB and file status:  FILE_DOES_NOT_EXIST every time during the session.

Is it any way to change this idle timeout with the library or in the windows settings?

**Comment by TalAloni** [comment]
Hi Maksym,
The server is the one terminating the connection of idle clients,
In most common use cases, the client will not be idle, it will perform some job and then disconnect.
If you have a need to keep a connection for a long period of time without sending a command, you could detect idle connection, and send some dummy command to make sure the server will keep the connection open.

**Comment by MaksymKlos** [comment]
Thank you for a quick response. A dummy command is actually a good idea. What is the least resource intensive command that can be sent?

**Comment by TalAloni** [comment]
For SMB2 that would be the ECHO request

**Comment by MaksymKlos** [comment]
Can I send somehow this ECHO request using SMB2Client? Because I do not see such a possibility

**Comment by TalAloni** [comment]
Right, sorry, it's not implemented because it doesn't do anything useful.
ListShares is a good alternative.
(again, perhaps you want to disconnect and reconnect again when needed).

**Comment by dwlee-gemiso** [comment]
Is it ideal to call ListShares once every few seconds?

**Comment by TalAloni** [comment]
"every few seconds" seems a bit excessive.
