### ISSUE TITLE
Custom Json Object as FileSystem

### ISSUE THREAD

**Issue by techfactorservices** [TalAloni/SMBLibrary#181]
I want to write a custom file system trying to implement a SMB server in front of a REST api  so the files can be exposed via UNC share. 

can someone please share example of this?

**Comment by TalAloni** [comment]
This issues section is dedicated to bugs or problems with the library.

As a side note - trying to put SMB "in front" is similar to trying to add wings to a garbage truck - it will not fly.
SMB is not FTP and it isn't HTTP, there are various low level operations that can't easily be translated to other protocols, anything that is not planned end-to-end may encounter issues with some use cases. locking files is a notorious example of the granularity in SMB that does not exist in other protocols.

**Comment by ClaytonPulman** [comment]
@TalAloni, I also am trying to find an example of this. I would like to create a virtual file structure listing. In your doco you mention.

"You can share anything from actual directories to custom objects, as long as they expose a directory structure."

Can you provide an example? I am trying to do the exact same thing as @techfactorservices. Understand your mention of the rubbish truck, but in my example it is not relevant. Just trying to present a virtual file structure listing - aka custom objects.

**Comment by TalAloni** [comment]
The NTFileSystemAdapter should get you started, implementing IFileSystem should be easy enough.

**Comment by techfactorservices** [comment]
So If I understand correctly, IFileSystem will return custom objects to NTFileSystemAdapter and handle all file operations happening in NTFileSystemAdapter?

If that is the case, 

1. How does NTFileSystemAdapter gets the directory structure as its not calling any such method from IFileSystem?
2. How does NTFileSystemAdapter integrate with application? Is there an example, currently the class is not being used.

**Comment by TalAloni** [comment]
Please make a basic attempt to figure things out before rushing to ask questions,
1. The question is not a valid question, NTFileSystemAdapter does invoke IFileSystem methods.
2. The SMBServer constructor has a SMBShareCollection parameter, the adapter can be used as a share filesystem implementation.
