### ISSUE TITLE
Action logging

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#187]
It seems to me that it is worth changing the logging levels of some actions.  Logging initially saves a very large amount of information to a file, even at the Verbose level.  It seems to me that the levels should be reconsidered, since a very large amount of information is stored in the file that does not make any sense.

**Comment by nvd05** [comment]
For example: logging of received and sent packets should be attributed to the debug level, since this information is not needed during server operation.  General information about what is happening is important: writing to a file, reading it, creating, deleting, etc.

**Comment by nvd05** [comment]
Sorry, I phrased the question wrong.  I was trying to say that calling ErrorResponse should essentially return a Warning, not a Verbose.

**Comment by TalAloni** [comment]
First of all, the library itself does not write anything to disk, but simply raises an event. the subscriber can decide what is worth writing to disk and what can be filtered.
