### ISSUE TITLE
Creating events

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#188]
I recommend making 'event' functions.  It will be useful if, for example, when deleting a file, do not delete it, but move it to the trash, and only delete the file in the trash.

Lib:
```cs
public SMB2Command Remove(...)
{
    ...
}

public SMB2Command Move(...)
{
    ...
}

...
```

User logic example:
```cs
[OVERRIDE]
public SMB2Command Remove(...)
{
    return nameShare == 'trash'
        ? this.Remove(...)
        : this.Move(...);
}
```

```cs
var server = new SMBServer(...);
server.handlers = ...;
```

**Comment by nvd05** [comment]
Rename functions 'Remove' => 'OnRemove', etc.

**Comment by TalAloni** [comment]
You seem to be completely misunderstanding what my library does. my library is simply a pipe - a pipe does not alter the content of what goes inside it. if you want something other than a pipe - you're welcome to fork the project and build that.

**Comment by TalAloni** [comment]
Any override at the file system level can be obtained using a wrapper around the INTFileStore implementation. no need to create events for that.

**Comment by nvd05** [comment]
```cs
// https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary/NTFileStore/INTFileStore.cs#L19

namespace SMBLibrary
{
    public interface INTFileStore
    {
        ...
    }
}
```

```cs
// https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary/NTFileStore/NamedPipeStore.cs#L16

namespace SMBLibrary
{
    public class NamedPipeStore : INTFileStore
    {
        ...
    }
}
```

private variable 'm_store'.
there is no way to replace it.

```cs
// https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary/Server/Shares/NamedPipeShare.cs#L20

namespace SMBLibrary.Server
{
    public class NamedPipeShare : ISMBShare
    {
        private NamedPipeStore m_store;

        public NamedPipeShare(List<string> shareList)
        {
            List<RemoteService> services = new List<RemoteService>();
            m_store = new NamedPipeStore(services);
        }

        public INTFileStore FileStore
        {
            get
            {
                return m_store;
            }
        }
    }
}
```

The variable 'm_services' is private.
there is no way to replace it.

```cs
// https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary/Server/SMBServer.cs#L31

namespace SMBLibrary.Server
{
    public partial class SMBServer
    {
        private NamedPipeShare m_services; // Named pipes

        public SMBServer(SMBShareCollection shares, GSSProvider securityProvider)
        {
            m_shares = shares;
            m_services = new NamedPipeShare(shares.ListShares());
        }
```

---

As a result, there is no way to replace the functions of the file system, since even with class inheritance and function redefinition. we can't pass it to the server class.

note: I may have missed something.
I haven't used c# for about 3 years, I could well have forgotten something about the compiler.
