### ISSUE TITLE
dotnet core support

### ISSUE THREAD

**Issue by schmitch** [TalAloni/SMBLibrary#19]
Hello, it would be good to have dotnet core support.
sadly that means that at least the libraries need to be "modern" projects and at least compile to .net standard.

**Comment by TalAloni** [comment]
Hi, since all the code is C# only, it should be really easy to achieve .NET core compatibility.
Feel free to start your own fork with .NET core support, there is already a .NET standard fork here: https://github.com/hagaygo/SMBLibrary

**Comment by TalAloni** [comment]
Done:
https://www.nuget.org/packages/SMBLibrary/

https://www.nuget.org/packages/SMBLibrary.Win32/
