### ISSUE TITLE
MAUI IOS platform can not use

### ISSUE THREAD

**Issue by Early-Emperors** [TalAloni/SMBLibrary#190]
ios : 16
SMBLibrary : 1.5.0
MAUI
`
SMB1Client client = new SMB1Client();
 bool isConnected = client.Connect(IPAddress.Parse("XX.XX.XX.XX"), SMBLibrary.SMBTransportType.DirectTCPTransport);//block
`
no exception

**Comment by Early-Emperors** [comment]
blocking position in SMB1Client.cs  
` 
  private bool ConnectSocket(IPAddress serverAddress, int port)
        {
            m_clientSocket = new Socket(serverAddress.AddressFamily, SocketType.Stream, ProtocolType.Tcp);

            try
            {
                m_clientSocket.Connect(serverAddress, port);// block
            }
`

**Comment by TalAloni** [comment]
Hi, I'm not familiar with the MAUI platform and have no way to help without additional information.

**Comment by TalAloni** [comment]
Also, are you sure that the IP and port are accessible and that the proper permissions are associated with the app?
again, I don't know what the requirements are for a MAUI app to open a TCP connection...

**Comment by Early-Emperors** [comment]
Sorry，My mistake,Company network issues.About block issue,I made an error of judgment. it will experience timeout exception,I'm too impatient!

**Comment by adfansong** [comment]
> Sorry，My mistake,Company network issues.About block issue,I made an error of judgment. it will experience timeout exception,I'm too impatient!

Hi, I met the same block issue when connecting on iOS. Could you tell me how you solved that?
