### ISSUE TITLE
wrong LastWriteTime value after the WriteFile action

### ISSUE THREAD

**Issue by kra5alllez** [TalAloni/SMBLibrary#192]
Hello

I ran into a problem that after writing data to a file, I get an incorrect LastWriteTime value.

My procedure is like this:

CreateFile(CreateDisposition.FILE_OVERWRITE) -> WriteFile -> GetFileInformation -> get LastWriteTime value -> CloseFile

After that, I connect to this file again:

CreateFile(CreateDisposition.FILE_OPEN) -> GetFileInformation -> get LastWriteTime value -> CloseFile

The value obtained in the examples above is different. And the value from the first example is wrong. I want to receive the correct value initially without repeating a call to Create and Close.

Do you know what the problem could be?

**Comment by TalAloni** [comment]
Hi,
This behavior is expected. Windows OS updates the file LastWriteTime when you close the handle used to modify the file.
There is an API to set the LastWriteTime yourself, but I don't recall if you can use the same handle or need to call Create again.
