### ISSUE TITLE
Not enough credits on dispose()

### ISSUE THREAD

**Issue by smarsh-gregj** [TalAloni/SMBLibrary#193]
Hi there.  I have looked at the other "Not enough credits" issues and I think our issue is unique.   
We are using for the most part your boilerplate code to write files to SMB.

```
  private NTStatus WriteToFileViaChunksFromStream(Stream contents, SMBConnection connection, object fileHandle)
  {

	NTStatus status = NTStatus.STATUS_SUCCESS;

	int numberOfBytesWritten;
	long offset = 0;
	int writeBufferSize = connection.client.MaxWriteSize;
	byte[] buffer = new byte[writeBufferSize];

	int bytesread = contents.Read(buffer, 0, buffer.Length);
	while (bytesread > 0)
	{

		if (bytesread<buffer.Length)
		{
			Array.Resize(ref buffer, bytesread);
		}

		status = connection.client.FileStore.WriteFile(out numberOfBytesWritten, fileHandle, offset, buffer);
		offset += numberOfBytesWritten;
		if (status != NTStatus.STATUS_SUCCESS)
		{
			string message = $"Failed to write to file.  Status: {status} at offset: {offset} with buffer size of {writeBufferSize}";
			_logger.Error(message);
			throw new Exception(message);
		}
		bytesread = contents.Read(buffer, 0, buffer.Length);
	}
	return status;
  }
```

This works 99.99% of the time but we are very rarely (though at our volume still significant) getting the Not Enough Credits issue.  We are getting back STATUS_INVALID_SMB from FileStore.WriteFile() which I believe is coming from here.  https://github.com/TalAloni/SMBLibrary/blob/4c3d3b542f33557bc19c678d96ccfb264f021acf/SMBLibrary/Client/SMB2FileStore.cs#L115  

When this happens, we throw our error and it bubbles up to the point where we try to dispose the SMB2Client and that is where the "Not enough credits" error is occurring.   It seems that ProcessPacket is never called to re-up the m_availableCredits on the client.   https://github.com/TalAloni/SMBLibrary/blob/4c3d3b542f33557bc19c678d96ccfb264f021acf/SMBLibrary/Client/SMB2Client.cs#L443 and SMB2FileStore.Disconnect() requests one credit and fails.

So question would be.  Is there a recommended way to dispose the client in this case that will unlock the file?  Or should we look in the other direction and still try to figure out if we are doing something wrong with our write requests?  We are not doing multiple requests simultaneously with our client and our apps are running single threaded.

Thanks for all the work you do.

**Comment by TalAloni** [comment]
Not Enough Credits and STATUS_INVALID_SMB are two different issues.
In both cases it means the client is doing something it should not do. (it can be the library code or how the library is used)
In most previous cases it was due to incorrect usage of the library (e.g. multi-threading, multiple requests)
This can be investigated though a WireShark capture of the session.
Are you based on the latest v1.5.0?

**Comment by smarsh-gregj** [comment]
Thanks for the response.  I understand they are different issues, but in our case, we get STATUS_INVALID_SMB and throw an exception which causes the FileStore to Disconnect() and throw "Not enough credits".   
So my question would be... **If/When we get STATUS_INVALID_SMB, what is the proper way to handle that status?**  If the answer is "Don't get that status" then we can certainly look deeper into that too.

Unfortunately I have no way to get a wireshark capture due to the problem happening seemingly randomly and we haven't been able to reproduce in production.
