### ISSUE TITLE
Search for files recursively in Directory structure

### ISSUE THREAD

**Issue by paulowirth** [TalAloni/SMBLibrary#194]
Hello TalAloni,

I am using SMBLibrary, and I have a scenario where I have a share with a certain structure.

- root
  - subfolder1
    - subfolder2
      - year
        - month
          - day
            - subfolder3
              - 0001.html
              - 0002.html
              - 000n.html     
            - subfolder4
              - 0001.html
              - 0002.html
              - 000n.html   
                          
 Is there a way to search for all files of a certain extension (in this case *.html) the tree structure without resorting to read level by level?
 
Thank you,
Paulo

**Comment by TalAloni** [comment]
No, there is no way to search through all the levels with SMB.
