### ISSUE TITLE
How can I get list of directory files and read them all.

### ISSUE THREAD

**Issue by NiceOneFox** [TalAloni/SMBLibrary#196]
I am trying to somehow able to read all files that I get from filestore.QueryDirectory(..)

Also I have tried to read CreateFile(test.xml) after I used a CreateFile for getting directory(share\\maxpatrol8). I was thinking it changes the current directory so I will be able to CreateFile using only name of reading file(test.xml) instead of full path after share name. ( It does not work for me )

can you please share with me some code of reading all files from share\\tmp\\maxpatrol8 ?

**Comment by TalAloni** [comment]
There is no such thing as "current directory" with SMB.
CreateFile should use the full path (relative to the share).

**Comment by NiceOneFox** [comment]
> There is no such thing as "current directory" with SMB.
> 
> CreateFile should use the full path (relative to the share).

Thank you for the quick answer.
Appreciate your work done on this library.
