### ISSUE TITLE
connection output synchronization

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#198]
Can you tell me what ideas you have for synchronizing your library with information output?

I'll take WPF (Windows Presentation Foundation):
There is a table on the screen.
The table shows all connections to the SMB server (active connections).

Tried to find something from the sync, but found nothing.
So far, only a timer that runs every 5 seconds comes to mind.
But the timer is a pretty bad solution to the problem.

**Comment by TalAloni** [comment]
There are some events you can subscribe to (e.g. ConnectionRequested).
I'm not seeing why a timer is a bad solution. it's a common practice.
If other events are needed this can be added.

**Comment by nvd05** [comment]
I would recommend making an event when the user disconnects.

[SMBServer.cs](https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary/Server/SMBServer.cs#L46)
```cs
public event EventHandler<DisconnectionRequestEventArgs> DisconnectionRequested;
```

**Comment by nvd05** [comment]
https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary/Server/SMBServer.cs#L180
```cs
                acceptConnection = connectionRequestArgs.Accept;
            }

            if (acceptConnection)
            {
                ConnectionState state = new ConnectionState(clientSocket, clientEndPoint, Log); // <====
                state.LogToServer(Severity.Verbose, "New connection request accepted");
                Thread senderThread = new Thread(delegate()
                {
                    ProcessSendQueue(state);
                });
                senderThread.IsBackground = true;
                senderThread.Start();
```

https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary/Server/ConnectionState/ConnectionState.cs#L41
```cs
    internal delegate void LogDelegate(Severity severity, string message);

    internal class ConnectionState
    {
        private Socket m_clientSocket;
        private IPEndPoint m_clientEndPoint;
        private NBTConnectionReceiveBuffer m_receiveBuffer;
        private BlockingQueue<SessionPacket> m_sendQueue;
        private DateTime m_creationDT;
        private DateTime m_lastReceiveDT;
        private Reference<DateTime> m_lastSendDTRef; // We must use a reference because the sender thread will keep using the original ConnectionState object
        private LogDelegate LogToServerHandler;
        public SMBDialect Dialect;
        public GSSContext AuthenticationContext;

        public ConnectionState(Socket clientSocket, IPEndPoint clientEndPoint, LogDelegate logToServerHandler)
        {
            m_clientSocket = clientSocket;
            m_clientEndPoint = clientEndPoint;
            m_receiveBuffer = new NBTConnectionReceiveBuffer();
            m_sendQueue = new BlockingQueue<SessionPacket>();
            m_creationDT = DateTime.UtcNow;
            m_lastReceiveDT = DateTime.UtcNow;
            m_lastSendDTRef = DateTime.UtcNow;
            LogToServerHandler = logToServerHandler; // <=====
            Dialect = SMBDialect.NotSet;
        }

        // ....

        public void LogToServer(Severity severity, string message)
        {
            message = String.Format("[{0}] {1}", ConnectionIdentifier, message);
            if (LogToServerHandler != null)
            {
                LogToServerHandler(severity, message);
            }
        }

        public void LogToServer(Severity severity, string message, params object[] args)
        {
            LogToServer(severity, String.Format(message, args));
        }
```

I propose to create a folder "Events" and move all events into it.
In my opinion, it is better to move the logging function from the server base class to a separate class (this is a big plus, as it is easy to maintain in the future).

**Comment by TalAloni** [comment]
Hi,
This issue started with you suggesting to add "event when the user disconnects", but then morphed into a proposal to rewrite the way logging works into something that is not helpful to me. obviously those two should not be in the same issue.
You're making the assumption that I want to log just events but this is clearly not the case, I do not want to add "pretend events" just for logging purposes, it's not a style that works for me.

**Comment by nvd05** [comment]
Most likely, I do not quite understand the rules of your code.  Personally, I prefer to make a separate class for each element, which will only be responsible for processing it.  Thus, in my code there would never be a class that started the server, was responsible for events and took on half of the processing logic.  Please note: I am not trying to say that your code is bad, or to offend you or your project in any way.  On the contrary, I will tell you that you have done a great job and I am grateful to you for this library.  I'm just trying to point out those little things that, in my opinion, could be implemented differently and follow the general rules for writing code.  Whether you follow this logic is up to you.  I'm just trying to suggest how I would write this or that solution, if for some reason I don't like it.

**Comment by TalAloni** [comment]
Thanks,
My take / philosophy is that events are for 3rd party subscribers, 
I agree that the logging infrastructure can be better, but I don't necessarily agree that event-based logging is the necessary improvement.
And in any case, the internals of the library are one thing and user requirements are another, and instead of communicating what you wish to achieve (event-based updating of the UI), the discussion turned to "how" which IMO is not really the point.

**Comment by nvd05** [comment]
I agree that most often you are given technical tasks, but they do not say how these tasks need to be implemented.
     However, my position is that everything should be done well: both the visible (for example, the browser) and the invisible (code) part.

     I explain why I recommend using the event system.
     The fact is that I would like to be able to change the text of the library log (I took this out in a separate question).

     Of course, you can make a separate static class that will store all messages and access them later, in the format:

     ```CS
     state.LogToServer(SMBMessages.client.connected).
     ```

     But this is not the best solution, in my opinion, since it is better to do it as an event and subscribe logging to the event.

     [Not a big digression]

     I mentioned earlier that I haven't written C# for a very long time.  Used languages such as: python, node, php and so on.

     So, a vivid example is nodejs, in which everything is built on callback functions.  I don't like the following facts in the language:
     1. Text events.  Nobody canceled the chance to make a mistake when writing, and then you can look for a problem for a long time and spend a very large amount of time solving it.
     2. The second problem is a lot of event overload.  There are events even where they are not needed and the code is very heavily reloaded.
     3. It is not always clear whether such an event even exists.
     4. It is not always known what arguments the function takes.

     For this event as text, I don't really like it.
     It is better, in my opinion, to do something similar to the EventEmitter c # library, in which the binding to the event is achieved not by text, but by classes, which is of course better, because you have code editor hints and a large number of other pluses.

     [End Retreat]

     I wrote this to clarify that events might be redundant, but in your case I think it will.

     I recommend binding events to classes that will have some properties that you can access and change the logging to your liking.

     The logging format: "text{0}, text{1}" is only appropriate if your logs are legible and immutable, but if you allow the user to modify the logs, you should switch to the '{PROPERTY_NAME}' property system.

**Comment by TalAloni** [comment]
Usually an SMB server will run as a service and not as an interactive application,
(The UI will either be web based or a separate interactive application).
The API was designed for polling the active connection rather than pushing change because that's what makes sense under such scenario.

After giving it additional thought following your request to add a "ConnectionTerminated" event, I'm still not seeing a common use case where the SMB server is an interactive application or one that will benefit from such event.
While I agree that in principle this may be useful for some use cases, this is not the main use case and I'm reluctant to invest my little time in implementing and testing it.
