### ISSUE TITLE
Cancel a working WriteToFile operation.

### ISSUE THREAD

**Issue by MedFehmiEBF** [TalAloni/SMBLibrary#199]
@TalAloni 
Based on your client examples I can't seem to find a way to cancel a "write to file (large or small size)" operation. The idea is obviously to stop writing data to the file and revert its content to to the state before starting the operation. Is this this idea already supported? How to achieve this if not?
Thanks a lot again for the great effort you put on this awesome library.

**Comment by TalAloni** [comment]
You write the file in chunks, if you wish to cancel then you simply stop writing additional chunks and delete the file (if that's required by you).
This part of the logic is under your responsibility so it's not really an issue with the library IIUC.
