### ISSUE TITLE
Username based shares

### ISSUE THREAD

**Issue by ciamberlini** [TalAloni/SMBLibrary#2]
Really great work, thanks you!
It is possible to show different shares for each authenticated username?

**Comment by TalAloni** [comment]
Thanks,
This is technically possible, but the current API does not support it.
The server service named pipe ("srvsvc") that is responsible to return the list of shares is implemented as part of the "object store" layer, currently, this layer is not aware of the SMB layer (authentication).

Passing the UserName down to the server service, and replacing the share list with the actual FileSystemShare objects, will allow the service to check permissions on each share and list only those with at least Read permission. should be an easy change, let me know if you need help with it.

**Comment by ciamberlini** [comment]
Just as I imagined :-)
I'll do some testing, many thanks!

**Comment by TalAloni** [comment]
I have updated the current implementation: CreateFile now has a SecurityContext argument which contains the UserName, this is necessary for the object store, and was planned all along.

NamedPipeStore.CreateFile is the method that instantiates named pipes, so modifications should start there.

**Comment by ciamberlini** [comment]
Strange, now it give me an error in NTFileSystemAdapter.GetFileInformation:
An unhandled exception of type 'System.InvalidCastException' occurred in SMBLibrary.dll
Additional information: Unable to cast object of type 'System.String' to type 'SMBLibrary.FileHandle'.

Handle object is empty string when the error occour.

**Comment by ROM-Knowledgeware** [comment]
Sorry about that! After I added the SecurityContext parameters there was one place that used an incorrect method overload that didn't trigger a compiler error. I have committed the fix.

**Comment by TalAloni** [comment]
Sorry about that! After I added the SecurityContext parameters there was one place that used an incorrect method overload that didn't trigger a compiler error. I have committed the fix.
