### ISSUE TITLE
Ability to change the text of the logs.

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#200]
Hi, could you add the ability to change the logging text? It would also be desirable to add a different number to each log.

It would be like a browser system where there is text and response code for the browser.

#### events
```cs
// events/SMBEvents.cs
public interface SMBEvents
{
}

// events/SMBLogger.cs
public class SMBLogger : SMBEvents
{
    // public readonly object properties;
    public readonly string message;
    public readonly int status_code;
}

// events/SMBEventClientConnected.cs
public class SMBEventClientConnected : SMBEvents
{
    public readonly string property_1;
    // next code ...
}
```

#### change
```cs
var property = typeof(SMBEventClientConnected);
var value = "new string {PROPERTY_1}, end";

server.messages[property] = value;
```

#### usage
```cs
void LogParser(SMBLogger data)
{
    // example
    Console.WriteLine(data.status_code + " => " + data.message);
}

server.events.Subscribe<SMBLogger>(LogParser);
```

**Comment by TalAloni** [comment]
1. I have specifically designed the logging to be separate from the library to avoid dealing with logging and allow each user to use their favorite logging infrastructure.
2. The logging mechanism is not limited to logging SMB responses, while in most cases there is an SMB response status associated with the log line, this is not true in all cases, and this is not the key information in the log entry anyway. the key info is the severity of the log entry, and that is indeed logged separately.
