### ISSUE TITLE
Improve memory allocation for NetBios receive buffer

### ISSUE THREAD

**Issue by itsKontra** [TalAloni/SMBLibrary#202]
While testing your library on an embedded device, I recognized my application used all my remaining memory (over 1 Gb). I analyzed it with dotMemory. Most allocations happend in **SMBLibrary.NetBios.NBTConnectionReceiveBuffer** during `IncreaseBufferSize(int bufferLength)`. 
By adding `ArrayPool` to NBTConnectionReceiveBuffer the application stays at 100Mb. ArrayPool is available for .NET Standard and would be a huge improvement.

**Comment by itsKontra** [comment]
Main change 
`public sealed class NBTConnectionReceiveBuffer : IDisposable 

    {
        public NBTConnectionReceiveBuffer(int bufferLength)
        {
            if (bufferLength < SessionPacket.MaxSessionPacketLength)
                throw new ArgumentException(
                    "bufferLength must be large enough to hold the largest possible NBT packet");
    #if NETSTANDARD2_0 
            m_buffer = ArrayPool<byte>.Shared.Rent(bufferLength);
    #else
            m_buffer = new byte[bufferLength];
    #endif
        }

        public void IncreaseBufferSize(int bufferLength)
        {
            if (m_buffer.Length >= bufferLength) return;
    #if NETSTANDARD2_0
            var buffer = ArrayPool<byte>.Shared.Rent(bufferLength);
    #else
            var buffer = new byte[bufferLength];
    #endif
            if (m_bytesInBuffer > 0)
            {
                Array.Copy(m_buffer, m_readOffset, buffer, 0, m_bytesInBuffer);
                m_readOffset = 0;
            }

    #if NETSTANDARD2_0
            ArrayPool<byte>.Shared.Return(m_buffer);
    #endif
            m_buffer = buffer;
        }
       
        private void ReleaseUnmanagedResources()
        {
    #if NETSTANDARD2_0
            ArrayPool<byte>.Shared.Return(m_buffer);
    #endif
        }

        public void Dispose()
        {
            ReleaseUnmanagedResources();
            GC.SuppressFinalize(this);
        }

        ~NBTConnectionReceiveBuffer()
        {
            ReleaseUnmanagedResources();
        }

    }

**Comment by TalAloni** [comment]
Thanks, I'm incredibly busy but I'll try to take a look soon.

**Comment by itsKontra** [comment]
Pullrequest #204

**Comment by TalAloni** [comment]
Thanks, would I be correct to assume that you're simultaneously opening a large number of connections?

**Comment by TalAloni** [comment]
Also, I wonder what would be the effect of simply calling
```
GC.Collect();
GC.WaitForPendingFinalizers();
```
On NBTConnectionReceiveBuffer.Dispose

**Comment by itsKontra** [comment]
1) Yes we open many small files very frequently. Support for a file-based communication. Therefor we also need to check for file changes as often as possible. 

2) Following call would work but is a hacky solution for an unsolved problem.
```
GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
GC.Collect();
```

**Comment by TalAloni** [comment]
Sorry for taking my time on this issue, will try to get to it soon.

**Comment by TalAloni** [comment]
Please check out the latest changes and provide feedback whether this addresses the issue.
