### ISSUE TITLE
Allow getting server states.

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#206]
Hello, could you please make the following fields public?

```cs
namespace SMBLibrary.Server
{
    public partial class SMBServer
    {
        private IPAddress m_serverAddress;

        private SMBTransportType m_transport; 
        private bool m_enableSMB1; 
        private bool m_enableSMB2; 
        private bool m_enableSMB3; 
        private Socket m_listenerSocket; 
        private bool m_listening; 
        private DateTime m_serverStartTime;
    }
}
```

```cs
public IPAddress m_serverAddress { get; private set; }

public SMBTransportType m_transport { get; private set; }
public bool m_enableSMB1 { get; private set; }

...
```

I need this information to get server state and additional variables.  I don't want to make a stateful class, because it's much easier to change it in a library than to write your own class.

**Comment by TalAloni** [comment]
Hi,
those are values that are initialized by the caller, so I don't see any issue with the caller using some settings class and then use that to display the information.
Please understand that I have very little time to work on this library and I try to focus on bugfixes and high value changes.

**Comment by nvd05** [comment]
> Hi,
> those are values that are initialized by the caller, so I don't see any issue with the caller using some settings class and then use that to display the information.
> Please understand that I have very little time to work on this library and I try to focus on bugfixes and high value changes.

I don't like it when there are synchronizations in the code (in which case you say to use them).  I don't like it, because in js it causes problems and not always everything works as it should.  I know that you do not have much free time, but I immediately offer you solutions, and in my opinion: they are worth it.

**Comment by nvd05** [comment]
```cs
namespace SMBLibrary.Server
{
	public partial class SMBServer
	{
		public IPAddress ServerAddress => m_serverAddress; 
		public SMBTransportType Transport => m_transport; 
		public bool EnableSMB1 => m_enableSMB1; 
		public bool EnableSMB2 => m_enableSMB2; 
		public bool EnableSMB3 => m_enableSMB3; 
		public bool Listening => m_listening; 
		public DateTime StartTime => m_serverStartTime;
	}
}
```
