### ISSUE TITLE
Immediate acceptance of changes

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#211]
Your library does not have instant synchronization capability.

![image](https://github.com/TalAloni/SMBLibrary/assets/69719657/eb178191-1790-41e4-b893-413a4565989a)

When you start the server, you get a list of shared folders, and there is no way to change it later.

In the question below I already asked if the database could be synchronized with the library and got a yes answer, but by "synchronize" I meant instant synchronization, i.e. instant change of information.
#203

For example, if there were 2 public folders and I added another one to the database, I would expect the next query to give me 3 public folders, but that's not the case.

**Comment by TalAloni** [comment]
You are correct. There is no way to add shares while the server is running.

**Comment by TalAloni** [comment]
Just to clarify - I don't see it as a critical feature so currently not planning to add it.

**Comment by nvd05** [comment]
For me it is not critical, but if in the future you are going to make the possibility of instant synchronization, then think about 'async' at the same time

**Comment by nvd05** [comment]
@TalAloni, Then why do you need the `Start` function in your library, if in fact after creating the server class I can no longer change the server settings (folders, users)...

**Comment by TalAloni** [comment]
@nvd05
Please avoid from going off topic.
This issue is closed.
If something not to your liking you can fork the project and make the necessary changes to meet your requirements.

**Comment by nvd05** [comment]
I'm just wondering why you made "those" decisions.
I like everything, as you have done a great job.

About the synchronization. Can you tell me why you didn't think of synchronization in the first place? There is for example FTP, in it you have to click 'refresh' every time to see new files and folders, but SMB solves this problem, but it turns out that not completely, but only partially.

**Comment by TalAloni** [comment]
You seem to be mixing different ideas and goals and I find this style of communication unproductive,
When you write something like "instant synchronization, then think about 'async' at the same time"
you mix between "async" which is a programming model and "instant synchronization" which is a general idea.
However in practice IIUC you seem to want to promote what I would call "the ability to add a share while the server is running".
I would recommend to you to focus on the actual "feature" you want to promote avoid avoid speaking in generalities or mixing up multiple features.

**Comment by TalAloni** [comment]
My desire is that you focus on the one thing that is most beneficial to you and only when we've accomplished that you'll move on to the next one to avoid overloading me. remember that I'm a volunteer and have very little time for this project.
