### ISSUE TITLE
Does the library plan to migrate to `c# 8.0` and later.

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#212]
Can you please tell me if there are plans to port the library to `c# 8.0` and later?

> Since `c# 8.0` there are warnings on `nullable`.
> To avoid them you need to specify the data type as `TYPE?`

**Comment by TalAloni** [comment]
nullable is an optional component of C# 8.0
Even if I'll migrate to C# 8.0, which I currently have no plan to, I will disable the nullable feature (<Nullable>disable</Nullable>)
(After using it for a while in other project I find the cost outweigh the benefit)
