### ISSUE TITLE
Are there any plans to migrate the library to `async'?

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#213]
For example, the authorization function can be implemented through a database.
But there is a recommendation in c# that says it is undesirable to use `Task.FromResult`, `Task.GetAwaiter` and other functions that block code execution.
It is better to use await, but your library is written without using `async`, `await`.

**Comment by TalAloni** [comment]
You're mixing up between things that are completely unrelated:
Authorization function can be implemented through a database and some users of the library are already doing so, this has nothing to do with async.
Currently there is no plan to introduce breaking changes to the library API. the time it will require is significant and the benefit is marginal at best.
