### ISSUE TITLE
Not able to access file in sub-directory.

### ISSUE THREAD

**Issue by EmberLynn** [TalAloni/SMBLibrary#216]
I'm trying to delete a file from a folder I have access to. I am able to connect to the client and login in, but I get the following status when calling CreateFile: ACCESS_DENIED with status and fileStatus is returning "FILE_DOES_NOT_EXIST".

```cs
SMB2Client client = new SMB2Client();
bool isConnected = client.Connect("mydomain", SMBTransportType.DirectTCPTransport);
if (isConnected)
{
    NTStatus status = client.Login("domainname", "username", "password");
    if (status == NTStatus.STATUS_SUCCESS)
    {
        ISMBFileStore fileStore = client.TreeConnect("FileShare", out status);
        if (status == NTStatus.STATUS_SUCCESS)
        {
            object fileHandle;
            FileStatus fileStatus;
            status = fileStore.CreateFile(out fileHandle, out fileStatus, "\\SubFolder1\\SubFolder2\\SubFolder3\\filename.png", AccessMask.GENERIC_WRITE | AccessMask.DELETE | AccessMask.SYNCHRONIZE, SMBLibrary.FileAttributes.Normal, ShareAccess.None, CreateDisposition.FILE_OPEN, CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);
            if (status == NTStatus.STATUS_SUCCESS)
            {
                // do something
            }
        }
        status = fileStore.Disconnect();
    }
}
```

**Comment by TalAloni** [comment]
Hi Ember,
ACCESS_DENIED is pretty self explanatory. note that you will not be able to obtain access to the handle with ShareAccess.None if the file is being used.
My only suggestion is to use WireShark to examine / verify your parameters.
Also, to delete a file you'll need to set SetFileDispositionInfo.DeletePending to true on the file handle.

**Comment by EmberLynn** [comment]
Please forgive me for not being well versed in network protocol, but I did use WireShark while running my code.

After I run this line:
```cs
bool isConnected = client.Connect("mydomain", SMBTransportType.DirectTCPTransport);
```
I noticed a message in WireShark stating: Destination unreachable (Port unreachable) despite it returning true on the connection and I can list all of the shared folders in the destination.

**Comment by TalAloni** [comment]
1. I suggested to capture Windows traffic, not the library traffic (to examine the parameters sent by Windows).
2. Make sure that you capture the traffic from the PC that you monitor (either the client or the server), and make sure you capture the traffic on both port 139 and 445 (Windows will attempt to connect to both)

**Comment by EmberLynn** [comment]
Thanks for your assistance here.

After talking to my co-worker, he mentioned that the server we are trying to access is a DFS. I saw in one of your issues that this library does not support DFS. So, we decided not to access the file share through DFS.
