### ISSUE TITLE
Can't access most QueryDirectoryFileInformation attributes

### ISSUE THREAD

**Issue by KerryXEX** [TalAloni/SMBLibrary#218]
Hi,
I'm trying the Connect to share and list files and directories - SMB2 example
which runs correctly and in VisualStudio "Locals" explorer I can see all the values, but in the code, I'm not able to access most attributes (such as FileName, FileAttributes etc.)
Only FileInformationClass and FileIndex are accessible.

What am I doing wrong?

Thanks
Kerry.

**Comment by TalAloni** [comment]
Sorry, but the issue section was not meant to help with Visual Studio issues.
This is probably the result of some compiler optimization though (I guess those values remained unused as as such optimized away and thus not accessible)

**Comment by phillijw** [comment]
You just need to cast the object to `FileDirectoryInformation`
