### ISSUE TITLE
Connecting to Subshare throws STATUS_BAD_NETWORK_NAME	

### ISSUE THREAD

**Issue by MedFehmiEBF** [TalAloni/SMBLibrary#219]
Hello @TalAloni,
I am trying to access a shared space "Sharespace-personal" situated under "Sharespace-main". I am attempting this with
```c#
connection established/login successful...
then connection to the share:

string shareSpace = "Sharespace-main/Sharespace-personal";
ISMBFileStore fileStore = client.TreeConnect(shareSpace, out fileStoreStatus);
``` 
which fails to connect with STATUS_BAD_NETWORK_NAME status error.
How can I achieve "connecting to share then to subshare" successfully?

**Comment by TalAloni** [comment]
No such thing as subshare, you must mean a directory under the share,
to obtain a handle to a directory you'll need to use CreateFile.

See: https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md
