### ISSUE TITLE
What is NTStatus 3221225680?

### ISSUE THREAD

**Issue by cds9046** [TalAloni/SMBLibrary#220]
Hello, I am using SMB2Client.

I am using your library with gratitude.

However, sometimes login failures occur in the client.Login part.

The client.Login method returns a value of 3221225680.

However, NTStatus cannot determine the value and cannot determine which error it is.

Am I using it the wrong way?

Attach a piece of my code.

Thank you.

```C#
try
{
    SMB2Client client = new SMB2Client();
    bool isConnected = client.Connect(IPAddress.Parse(_configuration.GetValue<string>("Storage:HOST")), SMBTransportType.NetBiosOverTCP);
    if (isConnected)
    {
        NTStatus status = client.Login(_configuration.GetValue<string>("Storage:HOST"), _configuration.GetValue<string>("Storage:ID"), _configuration.GetValue<string>("Storage:PW"));
        if (status == NTStatus.STATUS_SUCCESS) // This status is 3221225680
        {
            // My Code
        }
    }
}

**Comment by TalAloni** [comment]
3221225680 = 0xC00000D0 = STATUS_REQUEST_NOT_ACCEPTED

As to why this is returned - I suggest to review WireShark communication and server settings / limitations.
