### ISSUE TITLE
The server is returning STATUS_SHARING_VIOLATION while creating a handle to delete a folder.

### ISSUE THREAD

**Issue by MedFehmiEBF** [TalAloni/SMBLibrary#222]
Hello,
I have an issue with Deleting a directory that has a content inside, constructing the structure inside the directory works perfectly, then also deleting the content inside it, afterwards soon as I attempt to get a handle on the directory I attempt to delete the sharing violation status is returned. Please take a look at the sample console app to reproduce the issue.

[SMB_DeleteDirectory_SampleApp.zip](https://github.com/TalAloni/SMBLibrary/files/12750523/SMB_DeleteDirectory_SampleApp.zip)

**Comment by TalAloni** [comment]
Hi, not really my job to debug your code.
The issue is unlikely with the library unless you can prove it is.
