### ISSUE TITLE
How do I hide a shared folder?

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#224]
Hi.

A few months ago I asked the question, "Can I hide a shared folder?" and got the answer, "Yes, you can".

By "hide a public folder" I meant not showing it in the list of available folders at all.

After entering your username and password, the next step is to select the public folder you want to open.
If you try to open a public folder that you do not have access to, Windows will show you a window with fields for entering your username and password, as well as a "not enough permissions" message.
However, I want you to simply not see public folders that you do not have access to (as if the other public folders do not exist at all, but are there and available to other users).

Could you please tell me if it is possible to hide public folders now or is it necessary to change the library code for this?

**Comment by TalAloni** [comment]
1. I understood the question.
2. Yes, you'll have to modify the code in order to not enumerate the folder you wish to be invisible.
