### ISSUE TITLE
High RAM consumption.

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#228]
Hi, @TalAloni 
Can you please tell me if such a large number of selected objects is a normal phenomenon?

These objects are not removed by the garbage collector (even by force).

Note: this volume filled in a week or so.

![1000008040.png](https://github.com/TalAloni/SMBLibrary/assets/69719657/686eeb07-ecf1-423d-ba54-3d97ba56f908)

![1000008038.png](https://github.com/TalAloni/SMBLibrary/assets/69719657/4a34cabd-24d3-4799-8732-45659c9b2527)

![1000008039.png](https://github.com/TalAloni/SMBLibrary/assets/69719657/81365947-8509-4881-95da-dfd1033d29dd)

![1000008037.png](https://github.com/TalAloni/SMBLibrary/assets/69719657/d39674a4-6c19-4b84-a258-36b1d70b386a)

**Comment by TalAloni** [comment]
Hi, this is related to #202

**Comment by nvd05** [comment]
Perhaps the reason why the server requires a lot of RAM is due to the fact that the server is shared and there are robots that try to pick the login and password to log in.

This can be seen in the smb server logs:
![1000008045.png](https://github.com/TalAloni/SMBLibrary/assets/69719657/ee3c14e8-45de-49c3-a61c-a2a6046cd326)

Also by the authorization table of the ftp server:
![1000008046.png](https://github.com/TalAloni/SMBLibrary/assets/69719657/631bbe87-99dd-4c68-baf5-51e6f15d95cd)

A copy of the DotMemory file:
1. https://dropmefiles.com/LKncI
2. http://78.29.34.5/Attach%20to%20SMBServer.dmw

**Comment by TalAloni** [comment]
Yes, large number of simultaneous incoming connections will require large number of connection buffers (one for each connection).
However right now those buffers are periodically collected by the GC which might take a while and in #202 the proposal is to reuse those buffers will will improve RAM usage in scenarios such as this.

**Comment by TalAloni** [comment]
p.s. I find it curious that your server is configured to support plain text passwords, which might be a security concern.

**Comment by TalAloni** [comment]
(I would also suggest to block accounts after a series of invalid attempts)

**Comment by nvd05** [comment]
The problem is that the robots don't know the logins and passwords, and the ip address is constantly changing (most likely using proxy).

Therefore, blocking an account is useless, as they pick up the login without even realizing if it actually exists.

As for login and password being plain text.
The thing is that in FTP the system is very different from SMB.

In FTP everything is passed in the format: `command parameters`.

Authorization example:
`USER <LOGIN>\n`
`PASS <PASSWORD>\n`

**Comment by nvd05** [comment]
> Yes, large number of simultaneous incoming connections will require large number of connection buffers (one for each connection).
However right now those buffers are periodically collected by the GC which might take a while and in https://github.com/TalAloni/SMBLibrary/issues/202 the proposal is to reuse those buffers will will improve RAM usage in scenarios such as this.

Simultaneous connections are usually no more than 1-2, but the bot makes a new connection every 3-5 seconds and tries to pick up the login and password.

Usually GC should destroy objects that are no longer referenced by anyone. This should happen as soon as the connection has been broken, especially since `SMBServer` even has a separate thread for this.

But apparently something is not working the way I assume.

**Comment by TalAloni** [comment]
"Usually GC should destroy objects that are no longer referenced by anyone. This should happen as soon as the connection has been broken"
That's not how GC works.

"In FTP everything is passed in the format: command parameters."
That's true but there is FTPS and SFTP, and better yet, SCP.

**Comment by nvd05** [comment]
Since you already know the essence of the problem, also this problem was asked earlier by another person, I think it is better to close my problem, since it is a copy of the one asked earlier.

**Comment by TalAloni** [comment]
Thanks again for the detailed information provided here, RAM consumption has been reduced in v1.5.1
