### ISSUE TITLE
Is it possible to get a login and NTLM?

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#229]
Hello, @TalAloni 
Could you please tell me if it is possible to get login and NTLM during authorization?

(There are sites that can decode this string based on their database. Of course, they may not decode every combination as the database is limited, but it's better than nothing).

**Comment by TalAloni** [comment]
Username can be obtained but NTLM credentials were specifically designed to prevent decoding. the same password will be encoded to a different value in each login attempt.

**Comment by nvd05** [comment]
For some reason, sites like https://md5decrypt.net/en/Ntlm/#answer produce the same result for the same string.

I will check the code that results from Windows coding later.

**Comment by TalAloni** [comment]
This is true for NTLM v1 which is not used these days. it was replaced by NTLM v2

**Comment by nvd05** [comment]
Thank you for the information.
