### ISSUE TITLE
Login without user and password

### ISSUE THREAD

**Issue by WhyLesS** [TalAloni/SMBLibrary#237]
Hi, how can I login without user and password?

**Comment by TalAloni** [comment]
username == string.Empty and password == string.Empty (as per [https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/5e550938-91d4-459f-b67d-75d70009e3f3?redirectedfrom=MSDN](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/5e550938-91d4-459f-b67d-75d70009e3f3?redirectedfrom=MSDN))
