### ISSUE TITLE
Bug after latest ArrayPool implementation

### ISSUE THREAD

**Issue by itsKontra** [TalAloni/SMBLibrary#238]
Bugs after #202 feature implementation:

I tested the new library and it works after fixing following bugs:

Dispose throws exception when array is null. It happend after a failed login request. I guess dispose got called twice. 
Anyway, it should be safe to call dispose twice.
 
_NBTConnectionReceiveBuffer.cs_
 ```
        public void Dispose()
        {
            if  (m_buffer == null) {
                return;
            }
#if NETSTANDARD2_0
           ArrayPool<byte>.Shared.Return(m_buffer);
#endif
            m_buffer = null;
        }
```

clientSocket.BeginReceive(...) throws ArgumentNullException if buffer.Buffer is already disposed. I simply added a null check there.

_SMB2Client.cs_
_SMB1Client.cs_
line 400ff:
```
try
{
    if (buffer.Buffer == null)
    {
        throw new ObjectDisposedException("buffer");
    }
    clientSocket.BeginReceive(buffer.Buffer, buffer.WriteOffset, buffer.AvailableLength, SocketFlags.None, new AsyncCallback(OnClientSocketReceive), state);
}
catch (ObjectDisposedException)
{
    m_isConnected = false;
    Log("[ReceiveCallback] BeginReceive ObjectDisposedException");
    buffer.Dispose();
}
catch (SocketException ex)
{
    m_isConnected = false;
    Log("[ReceiveCallback] BeginReceive SocketException: " + ex.Message);
    buffer.Dispose();
}
```

But the implementation works like a charm and memory usage is not increasing infinitely anymore. 
Thx for the effort

**Comment by TalAloni** [comment]
Thank you, can you please share exactly how to reproduce this? what does the server / client needs to be doing?

**Comment by TalAloni** [comment]
Hi, I was able to recreate the second issue and pushed a fix, would appreciate information on how to reproduce the first issue.

**Comment by TalAloni** [comment]
I decided calling Dispose twice shouldn't throw an exception anyway and pushed a fix for that as well.
Let me know if the latest fixes works out. Thanks!

**Comment by TalAloni** [comment]
Latest implementation is now part of v1.5.1, please report any issue that you find. Thanks again for the assistance in resolving this problem.
