### ISSUE TITLE
Async  exception on sync operation 

### ISSUE THREAD

**Issue by johankoolwaaij** [TalAloni/SMBLibrary#241]
This happened only once in 2 years of operation, but it made me wondering,

I upload 29 files to a SMB share, and all files are copied perfectly. But one second after the last upload I get this exception below, that is unhandled, and terminates my app.

I used 

`status = fileStore.CreateFile(out fileHandle, out fileStatus, remoteFilePath, AccessMask.GENERIC_WRITE, SMBLibrary.FileAttributes.Normal, ShareAccess.None, CreateDisposition.FILE_OVERWRITE_IF, CreateOptions.FILE_NON_DIRECTORY_FILE, null);`

which is synchronous and does what it should do, but only once it threw the async exzception below.

How can this be?

---

type=System.NullReferenceException

source=SMBLibrary

message=Object reference not set to an instance of an object.

stack=
```
   at SMBLibrary.Client.SMB2Client.OnClientSocketReceive(IAsyncResult ar)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by TalAloni** [comment]
Receiving data from the server is done using the asynchronous OnClientSocketReceive, however the 'NullReferenceException' exception still should not have happened.
Do you use the latest library version?

**Comment by johankoolwaaij** [comment]
Yes, I use 1.5.1, and as I said this happened only once in two years or so. But because it happened in a thread not controlled by me, it was unhandled, and it crashed my IIS razor app after all files were copied correctly. I guess we need to wait until someone else has the same issue in next two years?

**Comment by TalAloni** [comment]
1.5.1 was released a month ago (and there was a change in that area).
If you could provide a code snipped that reproduce this - or stack trace showing line numbers - that would be helpful

**Comment by johankoolwaaij** [comment]
I was lucky that I log the unhandled exceptions, and this was all I have.
It happened after the last CreateFile(), maybe on the 

 `status = fileStore.CloseFile(fileHandle);`

or 

`status = fileStore.Disconnect();`

And until now no reproduction. So I guess we have to wait...

**Comment by sprehn-ero** [comment]
we experience the same issue on version 1.5.1. I think there is a race condition between  `SMB2Client().Disconnect() `
and `OnClientSocketReceive `callback, which calls Dispose on the receive buffer as well, especially when the connection gets terminated.


```
NBTConnectionReceiveBuffer

 public void Dispose()
 {
     if (m_buffer != null)
     {
         ArrayPool<byte>.Shared.Return(m_buffer); 
         m_buffer = null;
     }
 }
```
m_buffer is checkt for non-null, but is null when evaluated inside the Return method.
The only line where m_buffer is set to null is the line after. So Dispose must be called concurrently.

this section must be synchronized

here is a screenshot from our observability system (sentry.io)
![image](https://github.com/TalAloni/SMBLibrary/assets/106254717/68c7b734-ce86-47d0-b326-b4c52a23a4db)
