### ISSUE TITLE
how can I use SMB2 upload larger file in 'ResumeFromBreakPoint' mode?

### ISSUE THREAD

**Issue by idea-zone** [TalAloni/SMBLibrary#244]
How can I do like  `copy /z  D:\downloads\file.ext  \\server\folder\file.ext ` ? 
If the network is interrupted, when the network is reconnected, can I continue uploading instead of starting from the beginning?

Thanks.

**Comment by TalAloni** [comment]
Hi,
Yes you can. you need to check if the file already exists and if so - append to it.

**Comment by idea-zone** [comment]
> Hi, Yes you can. you need to check if the file already exists and if so - append to it.

Can you give me some examples code? Thanks.

**Comment by TalAloni** [comment]
Hi, the "issues" section is for reporting issues with the library,
If you want someone to code for you, you can hire someone to do that, if you wish to write the code yourself, the steps are as follows:
1. Check the size of the existing file (GetFileInfromation)
2. If necessary, open the file in a mode allowing append (There is plenty of online information on "CreateFile" and its various modes)
3. Use FileStore.WriteFile and specify the write offset (see [ClientExamples](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md)) and append to the existing file

**Comment by idea-zone** [comment]
> Hi, the "issues" section is for reporting issues with the library, If you want someone to code for you, you can hire someone to do that, if you wish to write the code yourself, the steps are as follows:
> 
> 1. Check the size of the existing file (GetFileInfromation)
> 2. If necessary, open the file in a mode allowing append (There is plenty of online information on "CreateFile" and its various modes)
> 3. Use FileStore.WriteFile and specify the write offset (see [ClientExamples](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md)) and append to the existing file

Thanks! The idea you provided is what I am missing.
