### ISSUE TITLE
Copying a file while having an STATUS_SHARING_VIOLATION

### ISSUE THREAD

**Issue by georgeskhater** [TalAloni/SMBLibrary#245]
Hello, 

First of all thanks for your efforts developing this library. 

Secondly, I mainly use your library to copy files from a shared server onto my local machine. To copy those files I have followed your 
[ClientExamples ](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md) 

```
if (status == NTStatus.STATUS_SUCCESS)
{
    byte[] data;
    int bytesRead = 0;
    using (FileStream destinationStream = new FileStream(destination, FileMode.Create, FileAccess.Write))
    {
        while (true)
        {
            status = smb.store.ReadFile(out data, fileHandle, bytesRead, (int)smb.client.MaxReadSize);
            if (status != NTStatus.STATUS_SUCCESS && status != NTStatus.STATUS_END_OF_FILE)
            {
                _logger.LogError($"Failed to read from file in windows shared: {status}");
                throw new Exception("Failed to read from file");
            }

            if (status == NTStatus.STATUS_END_OF_FILE || data.Length == 0)
            {
                break;
            }

            bytesRead += data.Length;
            destinationStream.Write(data);
        }
    }

    _logger.LogDebug($"SMB copy ended, File Exists : {File.Exists(destination)}, Bytes Copied : {new FileInfo(destination).Length}");
    smb.store.CloseFile(fileHandle);
    return true;
}
```

so I read the file and copy it to a destination stream to create a local  copy.

Problem is that sometimes the file is locked by another user (STATUS_SHARING_VIOLATION), I was wondering if there is a method to copy the file even if it is in use by another user, or at least know it is locked by which process/session?

Thanks

**Comment by TalAloni** [comment]
Hi George,
This is not really a question about the library but more of a question about Win32 API that the library invoke on the remote file server.

When you create the handle (CreateFile) you can specify the desired access and share access which may have an affect on the ability to interact with other processes accessing this file on the server. you can use an all-or-nothing approach to try to obtain a handle in a way that, if successful, will guarantee you read success and may prevent other processes from accessing the file.
Again, this is CreateFile related and not SMBLibrary related, there is plenty of info on that subject out there. the issues section is meant for bugs in SMBLibrary.
