### ISSUE TITLE
SMBServer.exe

### ISSUE THREAD

**Issue by steom** [TalAloni/SMBLibrary#247]
Please think to consider to add command switch so we can run smbserver as a service.

Like this old project https://github.com/skyjos-com/Redfish

**Comment by TalAloni** [comment]
Hi
You seem to be under the wrong impression regarding the role of SMBServer.exe.
SMBServer is a sample project demonstrating how to use the library. Users of SMBLibrary are welcome to create their own server implementation with the features they need.
