### ISSUE TITLE
[Question] FileSystemWatcher-like support

### ISSUE THREAD

**Issue by MosheL** [TalAloni/SMBLibrary#251]
Hi,

Did you have a support for something like FileSystemWatcher?
So I can monitor changes in network files?

Thanks.

**Comment by TalAloni** [comment]
You seem to be confused, FileSystemWatcher relies on capabilities offered by the running OS (i.e. not over the network)
SMBLibrary is a library that allows exposing and consuming services over the SMB protocol (i.e. over the network).
Within the context of SMB, there is something called CHANGE_NOTIFY, which allows tracking of some changes on a remote file system.
In any case, SMBLibrary provides low-level infrastructure, if the developer needs specific behavior or API - that's up to them to implement it.
