### ISSUE TITLE
tree connect returning null

### ISSUE THREAD

**Issue by UnIQSaQYA** [TalAloni/SMBLibrary#252]
Hi, what to pass inside client.Treeconnect("shared", out status). I have passed shared by looking at the code examples but nothing happens all  i get is null returned.

**Comment by TalAloni** [comment]
The issue section is to report issues with the library, it's not meant to provide assistance.
You didn't even specify the status being returned.
I any case, I suggest using WireShark to view the parameters sent by Windows to figure out what's needed to be sent.
