### ISSUE TITLE
SMB1Client Connect method not timing out

### ISSUE THREAD

**Issue by widget-tester** [TalAloni/SMBLibrary#255]
Attempting to fileshare between a Windows 7 SP1 machine and Windows for Workgroups 3.11 machine.  

Problem is with:
Console.WriteLine("attempt to connect");
bool isConnected = client.Connect(IPAddress.Parse("100.1.1.4"), SMBTransportType.NetBiosOverTCP, true, 1000);
Console.WriteLine("check if connection successful");

Experimented with the timeout value and this method call just seems to hang indefinitely, my 2nd print to console never occurs.

While my application is running, I can see using netstat -an that a connection appears to be established, i.e.:
Proto Local Address     Foreign Address State
TCP    100.1.1.1:49325   100.1.1.4:139     ESTABLISHED

In services.msc, the server service is stopped and disabled, TCP\IP NETBIOS Helper service is enabled.  Ping between machines works

**Comment by widget-tester** [comment]
Some debugging shows I'm not receiving a PositiveSessionResponsePacket, so likely security settings on my end.  I think it could still be improved by applying a timeout to the entire connect process as well as returning more detailed status vs as bool.

**Comment by TalAloni** [comment]
Can you please debug and update where inside Connect it hangs?

**Comment by TalAloni** [comment]
I did identify that we're using 5 seconds as timeout instead of the value provided using the Connect method and pushed the fix for that, is that the only issue?

**Comment by TalAloni** [comment]
The fix for the aforementioned issue is included in v1.5.2
