### ISSUE TITLE
SMBLibrary may crash the entire process

### ISSUE THREAD

**Issue by rodion-m** [TalAloni/SMBLibrary#260]
In version 1.5.1 we run into the exception that crashed our ASP.NET Core application entirely.

Here is the stacktrace:
```
Unhandled exception. System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at SMBLibrary.Client.SMB2Client.ProcessPacket(SessionPacket packet, ConnectionState state)
   at SMBLibrary.Client.SMB2Client.ProcessConnectionBuffer(ConnectionState state)
   at SMBLibrary.Client.SMB2Client.OnClientSocketReceive(IAsyncResult ar)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

In our (visible) client side we got an exception `NT_STATUS: STATUS_FILE_CLOSED`.

Perhaps it was happened because of parallel access (but we are not sure)

Also, I found a related issue: https://github.com/TalAloni/SMBLibrary/issues/257

Even if the `ArgumentException` is fixed, it's really not OK that SMBLibrary can crash the application process under the hood. I suppose you could catch such unhandled exceptions (or make this feature optional because of possible performance issues) and then log them to a global logger, or if no logger is set, "redirect" exceptions to something like `AppDomain.CurrentDomain.UnhandledException`.

**Comment by TalAloni** [comment]
Hi,
1. Please check if this happens with v1.5.2
2. The client is not thread-safe.

**Comment by TalAloni** [comment]
Also, obviously there should be no unhandled exceptions on background threads, if there is such a case - it is obviously a bug that should be addressed and exceptions should be handled locally. I don't feel there is a need to handle exceptions globally as an additional precaution.

**Comment by rodion-m** [comment]
Thanks a lot for a quick response! Ok, we'll update and try to reproduce this error after that.

About thread safety - do you mean that a class instance of SmbClient2 is not thread safe? (In this case it's enough to use it as scoped dependency). Or entire parallel access to SMBLibrary is not safe? (In this case dependency lifetime doesn't take an effect and we should globally synchronize access to SmbClient2).

**Comment by rodion-m** [comment]
> Also, obviously there should be no unhandled exceptions on background threads, if there is such a case - it is obviously a bug that should be addressed and exceptions should be handled locally. I don't feel there is a need to handle exceptions globally as an additional precaution.

But the exception from SMBLibrary that I reported crashes the entire app. Maybe it's a bug in .NET runtime, idk... We use .NET 6. 
I think you can easily reproduce this behavior by yourself just manually throwing any exception inside the callback:

**Comment by TalAloni** [comment]
A class instance of SMB2Client is not thread safe and access to it from two different threads should be synchronized.

**Comment by TalAloni** [comment]
> But the exception from SMBLibrary that I reported crashes the entire app (I assume that it crashes ThreadPool or ThreadPool's thread). Maybe it's a bug in .NET runtime, idk... 

Any unhandled exception in a thread started by SMBLibrary has the potential to crash the entire app. That's how .NET is designed and that's why there shouldn't be any unhandled exception in a thread started by SMBLibrary.
There was a bug in v1.5.1 that was fixed in v1.5.2, if you can show there is another issue - it will be addressed as well.

**Comment by rodion-m** [comment]
> There was a bug in v1.5.1 that was fixed in v1.5.2

Thanks a lot! We'll check it and report you about the results.

**Comment by TalAloni** [comment]
Please open a new issue if you experience an issue with the latest version.

**Comment by rodion-m** [comment]
We couldn't reproduce this error after an updating to 1.5.3. Thanks a lot for your help!
