### ISSUE TITLE
LargeMTU unavailable

### ISSUE THREAD

**Issue by michaelkocian** [TalAloni/SMBLibrary#262]
Constants in file SMB2Client prevent the filestore from reading larger buffers than 1MB. This results in slow Read/Write speeds of large files e.q. playing a high bitrate video.

```
 public static readonly uint ClientMaxTransactSize = 1048576;
 public static readonly uint ClientMaxReadSize = 1048576;
 public static readonly uint ClientMaxWriteSize = 1048576;
```
```
 m_maxTransactSize = Math.Min(response.MaxTransactSize, ClientMaxTransactSize);
 m_maxReadSize = Math.Min(response.MaxReadSize, ClientMaxReadSize);
 m_maxWriteSize = Math.Min(response.MaxWriteSize, ClientMaxWriteSize);
```
My SMB allows readings up to 8MB.
![image](https://github.com/TalAloni/SMBLibrary/assets/50811306/8bf70b55-4925-4191-a22f-24d37cbfb78c)

Simply increasing this variable does not help due to the command would cost too many credits.

**Comment by TalAloni** [comment]
Hi Michael,
1. The defaults in SMB2Client were chosen to fit wide range of usage scenarios, including embedded devices with low amounts of RAM, and it's true that they may not be optimal for your specific use case.
2. SMB2 allows reading up to 16MB.
3. Unless you have a very unique network with high latency, I would find it hard to believe that increasing the buffer from 1MB to 16MB will make a big difference.
4. DesiredCredits is set to 1MB / 64KB = 16. increasing MaxReadSize requires changes to DesiredCredits as well.

**Comment by michaelkocian** [comment]
Thanks, Increasing the DesiredCredits helped to resolve the problem.

Unfortunately, as I increased the buffer to 8MB, the time required to download the data also increased.
It took around 100-200ms to download 1MB and 600-1200ms to download 8MB.
Perhaps the allocation of the buffer is what is slowing my program down (I am using the library in an MAUI project)
