### ISSUE TITLE
How to create a simple SMB1 server?

### ISSUE THREAD

**Issue by hardlevel** [TalAloni/SMBLibrary#263]
Hi! 

I read the samples, but there's any about how to create a SMB1 server, can you share some sample of simpliest way of starting a SMB1 server?

Thanks!

**Comment by TalAloni** [comment]
I've provided a sample application called SMBServer.

**Comment by hardlevel** [comment]
hi! thanks!

can you provide some simple sample without an user interface please?

**Comment by TalAloni** [comment]
The purpose of the sample application was to help users figure out how to start the server. this is the example I've provided and I think it's clear enough. if you need additional help I suggest you hire a developer to assist you.

**Comment by hardlevel** [comment]
Hello my friend, I hope you are well.

It is not a question of hiring someone, I am a developer and I am just starting out with C# now, and the example is not user-friendly for beginners. Usually complex projects have documentation that details each item of the project.

What I was asking for was just an example of the minimum necessary to make a server work, without the need for an interface. I searched a lot on the internet for materials that could help, but there is simply nothing anywhere, but that's okay, I already understand that it will not be possible, thank you for your attention.

**Comment by TalAloni** [comment]
I suggest you take your time to review the example I provided.
Multiple developers have used it successfully to understand how to start a server.

**Comment by hardlevel** [comment]
Ok friend, I will look out for other solution

Thanks for your time
