### ISSUE TITLE
SMB(2) Move File Only On Server ?

### ISSUE THREAD

**Issue by samba2** [TalAloni/SMBLibrary#264]
Hi, 

just a clarification question. Given I have file `/dirA/myFile.txt`. I want to move that file to a different directory structure on the SMB server (e.g. `/dirB/myFile.txt`) *without* reading the file to the client and writing it back. I really just want to change the storage location on the SMB server and keep client <> server communication as small as possible. 

How would I achieve that ?

PS: I have a share talking SMB2 and SMB3.

**Comment by TalAloni** [comment]
If the source and target are on the same SMB share you can issue a RENAME command to achieve that.
if they are on different shares you'll have to read and write.
