### ISSUE TITLE
List Folders only 

### ISSUE THREAD

**Issue by otkhan** [TalAloni/SMBLibrary#265]
Hi TalAloni,
Is there a way I can filter out the response for Directories only ahead of time? 

status = fileStore.QueryDirectory(out fileList, directoryHandle, "*", FileInformationClass.FileDirectoryInformation);

Here "*" is for everything, *.* can be for files, is  there a way to only list directories but not files?

**Comment by TalAloni** [comment]
Hi,
The purpose of issues section is to report issues with the library.
To answer your question, I'm not aware of any way to only list directories.
