### ISSUE TITLE
ACE size issue

### ISSUE THREAD

**Issue by tom-gez-sp** [TalAloni/SMBLibrary#266]
Hi @TalAloni,

I recently encountered a case where if I use `SMB2FileStore.GetSecurityInformation()`, I get a malformed DACL back.
Specifically, I get 2 ACEs, the first of which looks fine, but the second contains unintelligible data, like a SID that has a revision of 0 and a nonexistent authority.

I used a sniffer on the network to see what the difference is between that specific response and others that did work, and I saw that each ACE had a padding suffix 4 bytes long.
This was reflected in their Size property's value, which was indeed larger by 4 than the length of the data itself, but since the code disregards this property and calculates the ACE length by the length of the SID, this gets missed, which results in all ACEs in the ACL except the first one to become malformed.

Would it be possible for you to modify this code so that it takes the Size property into account so the offset gets updated correctly for following ACEs?
If you need more information on the matter, I'm more than willing to provide.

Thanks!
Tom

**Comment by TalAloni** [comment]
Thanks Tom,
1. Are you saying the library does not correctly parse a DACL in this case?
2. A WireShark capture can be useful.

**Comment by tom-gez-sp** [comment]
Thanks for the prompt response, @TalAloni :)
1. Yes, this is what I'm saying.
2. Attaching the GetInfo request and response capture from Wireshark.
[getinfo_response_with_padding_in_dacl_truncated.zip](https://github.com/user-attachments/files/16792652/getinfo_response_with_padding_in_dacl_truncated.zip)

**Comment by TalAloni** [comment]
Thanks for this report and packet capture. this issue has been resolved in SMBLibrary v1.5.3.5
