### ISSUE TITLE
Updating the Client automatically

### ISSUE THREAD

**Issue by NilsHoyer** [TalAloni/SMBLibrary#268]
I would like to mount an Android file system on Windows and a Windows file system on Android.

For this, I wish to forward also any updates like adding a new file or remaining one, without to bother the user with refreshing his file manager UI like the Windows Explorer.

Sine you are using the IFileSystem interface and this does not support events, I believe my wishes will not be offered from SMBLibrary. Am I right?

Does the SMB protocol support this?

**Comment by TalAloni** [comment]
SMB protocol does support updating the client regarding file system events via the NotifyChange mechanism.
The SMBLibrary does support it via the INTFileStore interface.
IFileSystem was meant to hide the complexities of implementing INTFileStore, but it only allows for basic capabilities and does not support NotifyChange. you can implement INTFileStore if you require NotifyChange support.

**Comment by NilsHoyer** [comment]
Thank you for this hint. Sounds like I'm looking for. 😀
