### ISSUE TITLE
STATUS_PENDING not taken in account

### ISSUE THREAD

**Issue by gldfdp** [TalAloni/SMBLibrary#27]
Hello,

it seems that the library does not take in account CreateMessage with Response status STATUS_PENDING. It should be wait for the next answer with same PID. I have this status for large file requests.

From [https://wiki.wireshark.org/SMB2](https://wiki.wireshark.org/SMB2)

> If a SMB2 command can not be completed immediately the server will respond immediately with STATUS_PENDING and specify a value for the PID that the client can use later to Cancel the request. This STATUS_PENDING reply has the P bit set to 1 to indicate that the PID is valid. Once the command completes later the server will send a second reply to the command, this time still keeping the P bit set to 1 and repeating the same PID as in the initial STATUS_PENDING reply.

**Comment by TalAloni** [comment]
it's not clear from your text what your issue is and which component of the library is not behaving as expected. moreover, you quote from a document that is not the official MS-SMB2 specifications.

**Comment by gldfdp** [comment]
@TalAloni The problem is that the library does not properly handle smb v2 status_pending response.

**Comment by TalAloni** [comment]
The server? The Client? please provide additional details and a WireShark capture demonstrating the problem.

**Comment by gldfdp** [comment]
Sorry, the client.
I will try to make you a capture.
Basically I make a create request with smb 2 client, the windows server
answers with status_pending (I think it is caused by the fact that is a
large file), but the library does not handle it and return an error.

Regards

**Comment by TalAloni** [comment]
If you're getting STATUS_PENDING when sending a Create request it usually means one of your Create parameters is incorrect. I suggest you examine the parameters sent by Windows in order to figure out how to correctly create a file, there are also examples here:
https://github.com/TalAloni/SMBLibrary/issues/9
