### ISSUE TITLE
Windows 11, Build 26040 should support alternative TCP ports for SMB

### ISSUE THREAD

**Issue by NilsHoyer** [TalAloni/SMBLibrary#270]
Just a small hint to update your [Notes](Windows 11, Build 26040 should support alternative TCP ports for SMB):
https://techcommunity.microsoft.com/t5/storage-at-microsoft/smb-alternative-ports-now-supported-in-windows-insider/ba-p/3974509

**Comment by TalAloni** [comment]
Cool.
