### ISSUE TITLE
DTO as prerequisites to going for async/await!

### ISSUE THREAD

**Issue by bakhtvar** [TalAloni/SMBLibrary#272]
Hi Tal
I am using SMBLibrary for some years and I Owe myself to it.
Moreover nowadays getting async/await is unavoidable for most scenarios and even in my applications also using SMBLibrary in async mode is a must.

I have reviewed the pipeline and arrive the point that the very first point need to be changed (at least to give a try to going for async) are the following two
```
        internal SMB2Command WaitForCommand(ulong messageID)
        internal SMB2Command WaitForCommand(ulong messageID, out bool connectionTerminated)
```

But the issue was that changing to async is required the Function not have any 'out' params.
I believe changing these params to 'DTO pattern' single input, is the only option. I mean something like..
```
internal SMB2Command WaitForCommand(SMB2CommandArgs args);

class SMB2CommandArgs
{
    public ulong MessageID { get; set; }
    public bool ConnectionTerminated {get; set;}
}
```
There after of omitting 'out' param, one can go for async.

---
So the point is that 'I am ready to take this burden and go for this DTO style' and provide the PR.
Actually I already started but as I found it would be a huge one. hereby I'd like to receive your greenlight.
Are you agree for going to DTO style (just for above two methods)?

PS.
After approving the PR, later I will continue for async/await.

**Comment by TalAloni** [comment]
Thanks Bakhtvar,
I have a full time job and it's harder and harder to find time for this side project - I can only find time if the effort is small and the value is significant.
9 months ago I agreed to introduce small optimization related to RAM usage, and only a few weeks ago I was finally able to stabilize it. a lot of time was spent debugging and updating code - time I do not have. there are still issues related to this change.
What you are proposing is much more than small - I'm sorry but I do not have the capacity for that right now or in the immediate future.
