### ISSUE TITLE
How to execute FSCTL_DFS_GET_REFERRALS Ioctl call to figure out what is the correct server of the share

### ISSUE THREAD

**Issue by mate1213** [TalAloni/SMBLibrary#273]
Hello,

I have a share to connect, but I'm unable to connect to the file share, because the response "bad_network_name".
I can create the client and login. I can use the IPC$ def share.
I figured out when I get the share list, it doesn't contains the required share, what I want to connect.

If I try to connect to the same share through Windows Explorer, (with the same credentials, what I use in this library), I can login, and get the content of the share RW rights provided.
When I debugged the connection I've found the the default windows client call up an function called: `FSCTL_DFS_GET_REFERRALS` with the parameter of the share I want to connect
This gives back multiple endpoint where the share exactly "live". (completly different DNS name from the original)
Is there any way, to call this function manually, to figure out where the share exist?

**Comment by TalAloni** [comment]
DFS is not currently supported.
The project is open source so you can add the missing implementation.
