### ISSUE TITLE
Ambiguity and confusion in success responses

### ISSUE THREAD

**Issue by kikaragyozov** [TalAloni/SMBLibrary#276]
As previously discussed in https://github.com/TalAloni/SMBLibrary/issues/68, personally as a consumer to this library I expect a reliable way via the API to check if a given operation was successful or not.

The way I expected to do so, is via the returned `NTStatus` and checking if it's anything different from `NTStatus.STATUS_SUCCESS`.

Apparently, this is not the case. I have no such guarantee as certain methods supposedly return other statuses denoting a success, which leads to ambiguity.

Can we please address this? If `STATUS_NO_MORE_FILES` for `ISMBFileStore.QueryDirectory` is truly a success, why is it returned as anything other than success?

At the very least, there should be a helper method, or anything really, that reliably communicates with you if the command was successful or not. For example, you could pass a `NTStatus` to a method that reports back if its value is considered a success response or a failure.

If I'm missing something, let me know. But at this point, I, as a consumer, have no clue what other surprises other methods have, and what status codes they might return denoting a success, but in a different fashion for the sake of more verbosity.

**Comment by TalAloni** [comment]
Hi Kiril,
You are missing something - I am not the author of the SMB protocol - Microsoft is - any issue you have with the protocol - you should take with Microsoft.
According to the protocol STATUS_NO_MORE_FILES - is the expected result for a successful operation.

**Comment by kikaragyozov** [comment]
> Hi Kiril, You are missing something - I am not the author of the SMB protocol - Microsoft is - any issue you have with the protocol - you should take with Microsoft. According to the protocol - STATUS_NO_MORE_FILES is the expected result for a successful QueryDirectory operation.

Could you please let me know if there's any other methods in the `ISMBFileStore` I should be aware of that return different status codes for success?

**Comment by TalAloni** [comment]
Don't recall all of them from the top of my head - I think there is also STATUS_END_OF_FILE.

**Comment by kikaragyozov** [comment]
> Don't recall all of them from the top of my head - I think there is also STATUS_END_OF_FILE.

Do we have `NTStatus` codes representing the following errors as outlined in the [following](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/652e0c14-5014-4470-999d-b174d7b2da87) specification page?

At first glance, we seem to be missing these two from that list:

```
STATUS_NETWORK_SESSION_EXPIRED
STATUS_SERVER_UNAVAILABLE
```
