### ISSUE TITLE
Opt-in for larger defaults on Read/Write in SMB2Client

### ISSUE THREAD

**Issue by kikaragyozov** [TalAloni/SMBLibrary#278]
Currently, the SMB2Client was made with the assumption that devices with low amounts of RAM will be using it, which is why there are upper bounds on all the Read and Write operations via the following constants:

```
public static readonly uint ClientMaxTransactSize = 1048576;
public static readonly uint ClientMaxReadSize = 1048576;
public static readonly uint ClientMaxWriteSize = 1048576;
```

Generally this is okay, but if we'd like to utilize what the server is offering us as maximum read and maximum write sizes, can we provide an opt-in to consumers of this library for that specific case? That opt-in should also modify the timeout and increase it appropriately, as the current one is very likely not to suffice for read/write operations with the increased buffer size.

I made a local test to an SMB server, to see what I would gain if I used what the server's offering as limits. The test involved transferring a 111 MB file, twice. Results:

1. With limits, process took about 54 seconds.
2. Without limits, process took about 35 seconds.

This difference will increase/decrease depending on how large the file gets and what buffer the consumer is using. I used the maximum available one, as shown in the code examples for writing large files.

**Comment by TalAloni** [comment]
Thanks Kiril,
1MB read/write size is quite a lot, my tests showed marginal improvement when going beyond that, so I'm quite surprised by your measurements.
any opt-in such as the one proposed gives user the ability to set values that may cause problems, something "less than ideal" that works well is preferable to me, given that I was not able to witness the improvement that you describe.

**Comment by kikaragyozov** [comment]
> Thanks Kiril, 1MB read/write size is quite a lot, my tests showed marginal improvement when going beyond that, so I'm quite surprised by your measurements. any opt-in such as the one proposed gives user the ability to set values that may cause problems, something "less than ideal" that works well is preferable to me, given that I was not able to witness the improvement that you describe.

I'd imagine the opt-in as a simple bool flag which when you pass, everything is done under the hood for them. Encryption was involved in the SMB server, perhaps that plays a part in the above perf improvement. This is just a guess, but it makes sense that a buffer of 8 mb (That was what the server proposed) versus a buffer of 1 mb to be quite faster in uploading a file, as you avoid 8 times more I/O or so.
