### ISSUE TITLE
Can you provide a simple implementer of IFileSystem

### ISSUE THREAD

**Issue by jlongo62** [TalAloni/SMBLibrary#28]
There are no classes in the solution that implement IFileSystem

I was  able to figure out how to create a class  to implement IFileSystem and include it in the server, but it fails once I get a level down in tree. A simple example of IFileSystem class that just wraps System.Io.File, Directory for a demo class would be very helpful.

**Comment by TalAloni** [comment]
Here is an (old) example that implements IFileSystem:
https://github.com/TalAloni/SMBLibrary/tree/9fe283762a21546be5787735a6fe719fa2e20172/SMBServer/DirectoryFileSystem
