### ISSUE TITLE
How to achieve parallel processing when a user uploads n files

### ISSUE THREAD

**Issue by kaihekaihe** [TalAloni/SMBLibrary#282]
How to achieve parallel processing when a user uploads n files? I've found that in the actual situation, the files are uploaded one by one in a serial manner, which leads to poor performance.

**Comment by TalAloni** [comment]
You can use multiple client instances, each uploads a file, thus achieving parallel upload of multiple files.

**Comment by kaihekaihe** [comment]
However, I need to develop a client by myself and then drag files into this client to initiate multiple SMB clients, right? I want to drag five files in Windows Explorer and have these five files uploaded concurrently.
