### ISSUE TITLE
SMB2Client.ListShares returns NTStatus.STATUS_PENDING

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#32]
The issue looks like issue #27, but the status is (often, not always) returned by ListShares. Following calls to ListShares then return STATUS_NOT_SUPPORTED. The SMB server is a Synology NAS.

**Comment by TalAloni** [comment]
Hi, can you please provide a WireShark capture?

**Comment by JX75** [comment]
I'm installing it now.

**Comment by TalAloni** [comment]
Please do.

**Comment by TalAloni** [comment]
No capture was received

**Comment by CraigBT** [comment]
I temporarily resolved this issue by modifying DeviceIOControl() in SMB2FileStore.cs. This is a hack and hopefully the author can provide a proper resolution.

******** Original Code:

            TrySendCommand(request);
            SMB2Command response = m_client.WaitForCommand(SMB2CommandName.IOCtl);
            if (response != null)
            {
                if ((response.Header.Status == NTStatus.STATUS_SUCCESS || response.Header.Status == NTStatus.STATUS_BUFFER_OVERFLOW) && response is IOCtlResponse)

******** Total Hack that appears to work:

            TrySendCommand(request);
Retry:
            SMB2Command response = m_client.WaitForCommand(SMB2CommandName.IOCtl);
            if (response != null)
            {
                if (response.Header.Status == NTStatus.STATUS_PENDING)
                    goto Retry;

                if ((response.Header.Status == NTStatus.STATUS_SUCCESS || response.Header.Status == NTStatus.STATUS_BUFFER_OVERFLOW) && response is IOCtlResponse)
