### ISSUE TITLE
Custom FileSystem

### ISSUE THREAD

**Issue by suddenelfilio** [TalAloni/SMBLibrary#33]
Hello

I wrote a custom file system trying to implement a SMB server in front of a REST api for a digital asset management system so the assets can be exposed via UNC share. I can list the folders and files just perfectly, except opening the file is not working. I initialy tried return the Stream - which is the download stream of the file on the web server - but it always complained the files was invalid. Next I tried to download the file to temp storage locally and then return the file via filestream, this either blows up, complains the file is locked or opens up the file. I had to change the NTFileSystemAdapter to allow the rewriting of the path so the GetEntry is called with a UNC path, it then performs the REST api call and downloads the file and I rewrite the path to the file that was downloaded locally. This works on and off...

Any tips or clues on how to get this working reliably?

**Comment by rebelweb** [comment]
Are you using the client or another part of this library?

**Comment by TalAloni** [comment]
Hi,
Note that Windows (the client) may open the same file multiple time when you double click on it (read properties, generate thumbnails, etc.) so your file system has to handle that scenario.
There is no requirement for the file to be temp-stored-locally, using REST API should work, compare the file that you copied from the SMB server to the original file and see if you have some bug that causes corruption.
