### ISSUE TITLE
IOCTL failed. CTL Code: FSCTL_VALIDATE_NEGOTIATE_INFO. NTStatus: STATUS_NOT_SUPPORTED.

### ISSUE THREAD

**Issue by suddenelfilio** [TalAloni/SMBLibrary#34]
When connecting from a windows server 2016 machine to the smb server I get the following error: IOCTL failed. CTL Code: FSCTL_VALIDATE_NEGOTIATE_INFO. NTStatus: STATUS_NOT_SUPPORTED.

I'm not an expert in this protocol and on the web I found I should disable RequiresSecureNegotiate but the listed powershell command does not work it seems.

**Comment by TalAloni** [comment]
I have just tested Windows Server 2016 again and did not have this issue.
What exactly are you trying to do? do you attempt to access the server share list ('\\server-ip') or are you accessing a specific share ('\\server-ip\share')?
Could you provide additional details about the version of Server 2016 you are using?
