### ISSUE TITLE
SMB Client: connect to a sub-folder

### ISSUE THREAD

**Issue by fgbustoa** [TalAloni/SMBLibrary#38]
Hi and thanks.

QUESTION:
how can i read/write/create a file in a subfolder ???

i.e.:
\\SERVER\SHARENAME\FOLDER1\FILE.TXT
\\SERVER\SHARENAME\FOLDER1\FOLDER2\FILE.TXT

**Comment by TalAloni** [comment]
See Issue #9 
You should provide CreateFile with the path that is relative to the share (e.g. "FOLDER1\FILE.TXT" as per your example)

**Comment by karthick-theta** [comment]
@fgbustoa  have you figured it out?
File write to subfolders works great. But I am having trouble listing files under sub dir
`fileStore.QueryDirectory(out fileList, directoryHandle,folder\subfolder,FileInformationClass.FileDirectoryInformation);`

**Comment by TalAloni** [comment]
karthick-theta,
1. Please don't hijack issues.
2. You need to open a handle to the subdirectory, you can't issue QueryDirectory to a parent folder and use that to query a subfolder.
