### ISSUE TITLE
GetSecurityInformation: Unable to cast to 'SMBLibrary.SMB2.FileID'

### ISSUE THREAD

**Issue by vadimcebotari** [TalAloni/SMBLibrary#39]
Hello! Thanks for this amazing project. 
I've got an issue when trying to get folder access information. As I understood I added `ACCESS_SYSTEM_SECURITY ` to access mask. But when I call `.GetSecurityInformation` it throws this exception:
> Unable to cast object of type 'System.Object' to type 'SMBLibrary.SMB2.FileID'.
>  at SMBLibrary.Client.SMB2FileStore.GetSecurityInformation(SecurityDescriptor& result, Object handle, SecurityInformation securityInformation)

using
`SMBLibrary Version="1.4.1"`

I looked at some examples and my code looks like this

```csharp
    var host = path.Split("xxx.xxx.xxx.xxx");
    var dir = "Dir"


    var client = new SMB2Client();
    var success = client.Connect(IPAddress.Parse(host), SMBTransportType.DirectTCPTransport);

    if (success)
    {
        var status = client.Login(domain, username, password);
        // Success
        SMB2FileStore fileStore = client.TreeConnect(dir, out status) as SMB2FileStore;

        if (fileStore != null)
        {
            object handle = new object();

            status = fileStore.CreateFile(out handle, out var fileStatus, Dir, AccessMask.ACCESS_SYSTEM_SECURITY | AccessMask.SYNCHRONIZE | (AccessMask)DirectoryAccessMask.FILE_LIST_DIRECTORY, 0, ShareAccess.Read | ShareAccess.Write | ShareAccess.Delete, CreateDisposition.FILE_OPEN, CreateOptions.FILE_SYNCHRONOUS_IO_NONALERT | CreateOptions.FILE_DIRECTORY_FILE, null);

            List<QueryDirectoryFileInformation> result = new List<QueryDirectoryFileInformation>();
            //var tree = fileStore.QueryDirectory(out result, handle, "*", FileInformationClass.FileFullDirectoryInformation);

            object secHandle = new object();
            SMBLibrary.SecurityDescriptor secDescr;
            var secStatus = fileStore.GetSecurityInformation(out secDescr, secHandle, SecurityInformation.GROUP_SECURITY_INFORMATION);

        }

    }
```

**Comment by TalAloni** [comment]
GetSecurityInformation should get FileHandle, you're passing secHandle
instead of the previously opened fileHandle.

**Comment by vadimcebotari** [comment]
😅 My fault! I'm closing the issue!
Thank you!
Have you got some examples of how to get a foulder's permission for each group?

**Comment by TalAloni** [comment]
Sorry, I didn't experiment with permissions. don't have any examples.
