### ISSUE TITLE
Can you please clarify which license this software is released under?

### ISSUE THREAD

**Issue by enishoca** [TalAloni/SMBLibrary#4]
Hi - 
I don't see any licensing information.  I would be great if you can clarify that.  Or just add a license.  Apache 2.0 or MIT are best if your intent is sharing.

thanks

**Comment by TalAloni** [comment]
Hi, The licensing information is specified in the header of the code files.
The license I've chosen is LGPL which I think is best for two-way sharing.

**Comment by jdluzen** [comment]
Hi @TalAloni, thanks for this great library! Due to the LGPL license, can I can use this in an Android application?

**Comment by TalAloni** [comment]
Thanks. The LGPL license does not prevent you from using this library in an Android application.
