### ISSUE TITLE
Using SMB1 client to rename/move a file/directory

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#40]
Hello,

I used successfully SetFileInformation with a FileRenameInformation2 parameter to rename remote items using SMB2.

Is it possible to do the same with SMB1 ?
I tried the following with no success:
- Call IFileStore.SetFileInformation(Object,FileRenameInformationType1): Not supported in SMB1Client.
- Call SMB1Client.SetFileInformation(Object,SetInformation): No subclass of SetInformation allows to rename a file.
- Add a function sending a RenameRequest directly: The server replies with a sharing violation status.

Have you got any suggestion about the way to proceed?

**Comment by TalAloni** [comment]
FileRenameInformationType2 is used for both SMB1 and SMB2.

**Comment by JX75** [comment]
The problem is that SetFileInformation is not implemented by SMB1FileStore :

        public NTStatus SetFileInformation(object handle, FileInformation information)
        {
            throw new NotImplementedException();
        }

**Comment by TalAloni** [comment]
I see - Fixed now.
Note that my earlier comment was incorrect,
FILE_RENAME_INFORMATION_TYPE_1: Used for 32-bit local clients and SMB1.
FILE_RENAME_INFORMATION_TYPE_2: Used for 64-bit local clients and SMB2.

**Comment by justinmchase** [comment]
Is there an example of how to call this?

**Comment by TalAloni** [comment]
Yes, rename and move are the same. path should be relative to the share.

**Comment by justinmchase** [comment]
Thanks it worked for me!
