### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by stevendev** [TalAloni/SMBLibrary#41]
We try to create a SMB server and access it from a mobile app - FE File Explorer. 

iOS:
https://itunes.apple.com/app/id510282524

Android:
https://play.google.com/store/apps/details?id=com.skyjos.apps.fileexplorerfree

We're able to browse shares and download files in FE File Explorer, but we get failure when you try to upload files. Then we go back to SMBLibrary V1.3.9 and everything goes fine. 
Any ideas?

**Comment by stevendev** [comment]
I'm not able to upload file with Direct TCP mode, but I'm able to upload with NetBIOS over TCP.

**Comment by TalAloni** [comment]
Thanks! fixed in v1.4.2
