### ISSUE TITLE
Reduce allocations with Span/Memory

### ISSUE THREAD

**Issue by sidristij** [TalAloni/SMBLibrary#43]
In all the project you use byte[], which can be easy changed to Span<T>. But, of course, this will work only for .NET Core.

For .NET 2.0+ you can make your own Span<T>, which will look like 
```
public struct Span<T>
{
    private byte[] target;
    private int offset;
    private int size;

    public Span<T> Slice(int offset) => new Slice(target, this.offset + offset, size - (this.offset + offset));
    public Span<T> Slice(int offset, int size) => new Slice(target, this.offset + offset, size);
}
```
of course, with bounds checking. 

In places of usage:
```
// for native Span:
Span<byte> buffer = stackalloc byte[NT ... .ParametersLength];
```

This will reduce all allocations to nothing.

**Comment by TalAloni** [comment]
I'm aware of the costs associated with allocating a byte array / span and especially zero-ing them out.
Feel free to create a branch - if you can produce a benchmark displaying significant improvement - I'll consider this.

**Comment by NN---** [comment]
.NET Standard 2.0 has [System.Memory](https://www.nuget.org/packages/System.Memory/) NuGet.

**Comment by sidristij** [comment]
Hi, @TalAloni. Remember me? :) I done. But on 1.4.2. This version is zero-allocating. Very fast, but API changed to work with Span/Memory 

https://github.com/speechpro/SMBLibrary/tree/feature/optimize-work-with-span-memory-use

**Comment by sidristij** [comment]
Not all parts moved from my internal repo and not moved to support SMB30, but main code can be discovered

**Comment by TalAloni** [comment]
Good for you - I looked at the changes but you put a lot of changes into one commit so it's really hard to understand what's going on.
Can you produce a benchmark displaying significant improvement?
