### ISSUE TITLE
SMB 3.x support

### ISSUE THREAD

**Issue by aling93** [TalAloni/SMBLibrary#44]
Hello,

Do you have any plans to add SMB v3 support? 

Thanks,
Alin G

**Comment by TalAloni** [comment]
Is there any particular feature of SMB v3 you are missing?

**Comment by aling93** [comment]
My understanding is that v3 adds encryption and would eventually deprecate the older versions. I've already seen significant adoption of v3 in some storage solutions like some of the DELL products.

**Comment by TalAloni** [comment]
Yes, encyrption is the most interesting SMB v3 feature.
it will not take a lot of time to implement, but I don't have too much time on my hands right now.

**Comment by TalAloni** [comment]
SMB 3.0 support was added in v1.4.3, client now supports encryption.
