### ISSUE TITLE
Can't read more then 65kb

### ISSUE THREAD

**Issue by fayilt** [TalAloni/SMBLibrary#45]
Hi,

I'm trying to set the buffer to 1MB, but when using SMB2, I'm getting STATUS_INVALID_PARAMETER if I try to read more than 65k.

If I switch to SMB1, it doesn't fail, but returns me 65k even if I request more.

We're currently using SharpCifs.Std library, which is able to return 1MB (although it only supports SMB1), so it's probably not a server limitation, but I can't figure out what needs tweaking so I can get more than 65k in one read.

**Comment by TalAloni** [comment]
Hi,
You'll need to check for the negotiated size and avoid reading more than the server allows.

**Comment by TalAloni** [comment]
Note that reading more than 64KB in SMB2 is only allowed over port 445
