### ISSUE TITLE
ListShares gives STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by yellowpanda** [TalAloni/SMBLibrary#47]
I trying to get the list of shares from a Windows Server. I can access the list of shares with Windows File Explorer but I get ACCESS_DENIED when using the library. Any hints?

```
var smb = new SMB2Client();
bool connected = smb.Connect(new IPAddress(addressBytes), SMBTransportType.DirectTCPTransport);
if (connected)
{
    var status = smb.Login("myDomain", "myUserName", "myPassword", AuthenticationMethod.NTLMv2);
    //status is STATUS_SUCCESS :)
    //...
    var shares = smb.ListShares(out status);
    //status is STATUS_ACCESS_DENIED :(
    //...
    var fileStore = smb.TreeConnect("myShareName", out _status) 
    //status is STATUS_ACCESS_DENIED :(
}
```

**Comment by TalAloni** [comment]
Please provide a packet capture with the library and a packet capture when using Windows Explorer

**Comment by yellowpanda** [comment]
What package capture tool do you prefer (Wireshark)?

**Comment by yellowpanda** [comment]
Packet capture send to you email.

**Comment by TalAloni** [comment]
Are you using the latest version of the library? (1.4.2)
The packet capture you sent demonstrate that messages are not being signed, but the v1.4.2 code should have signed those messages.
Can you please double check that those captures are taken using the latest version?
