### ISSUE TITLE
Windows 10 refuses to navigate to share.

### ISSUE THREAD

**Issue by honkmother** [TalAloni/SMBLibrary#48]
I have the ports opened, I can connect via telnet over TCP, but I cannot get Windows to allow me to navigate to the share.
I have no idea what I am doing wrong.

**Comment by TalAloni** [comment]
There are very little details here, did you disable Windows built-in file-sharing for that port?
Which OS is the server? which is the client?
Do you see the incoming connection in the application's log?

**Comment by honkmother** [comment]
I am trying to host on a local ip: e.g 192.168.0.2 - can I not connect to myself? I am **not** doing \\localhost.
I am connecting to the correct IP that I am hosting the server on. Neither NetBIOS or Direct TCP works.

The OS is Windows 10 & all the built-in file sharing was fully removed and disabled.

I don't see the incoming connection but I know it does try to connect because if I shut off the server in the middle of connecting it will immediately stop trying to connect.

![image](https://user-images.githubusercontent.com/16845709/87478122-42691b80-c5f7-11ea-9247-3713911280f7.png)
![image](https://user-images.githubusercontent.com/16845709/87478310-8e1bc500-c5f7-11ea-8004-1cda6903aa5e.png)
![image](https://user-images.githubusercontent.com/16845709/87478327-996ef080-c5f7-11ea-9222-33ea85ddec9e.png)

I don't mind donating for paid support in the future but I've got to make money to do that :)

**Comment by TalAloni** [comment]
If you don't see the incoming connection it means you're not talking to the application,
localhost connection is certainly possible, but it's a bit more tricky to get working, so I would start with something easier and make sure remote clients can successfully connect.

**Comment by TalAloni** [comment]
I also observed that you're not binding the server for all adapters - I'm not sure if localhost can work when you only bind 192.168.0.3

**Comment by honkmother** [comment]
I did nothing different just now and it allowed me to map the drive. Thanks!
