### ISSUE TITLE
Cannot get example working

### ISSUE THREAD

**Issue by JoshuaaMichael** [TalAloni/SMBLibrary#5]
I cannot get the example to run, continually getting "An attempt was made to access a socket in a way forbidden by it's access permissions".

I've installed a Microsoft Loopback Adapter, given it the IP details of 192.168.50.1/24
I'm looking to run the program on port 445 so Windows Explorer will pick up on the share.
I've found and opened the Settings.xml document. It references a "C:\Shared" folder by default. I've made that folder and put a test text document in it. However I'm still not able to open "\\192.168.50.1" in explorer.
When I run the SMB server, I'd like to not block the existing access for the local machine to run their own SMB shares through Windows. Is that possible?

Also, were there any working examples implementing an IFileSystem?

My apologies if I haven't been clear, feel free to ask me to clarify anything. Thank you.

![image](https://user-images.githubusercontent.com/12680312/36513183-816c347e-17c2-11e8-9b86-943b8bae763f.png)
![image](https://user-images.githubusercontent.com/12680312/36513292-19814196-17c3-11e8-89fd-ebb9c82d2d19.png)
![image](https://user-images.githubusercontent.com/12680312/36513302-27361262-17c3-11e8-9da1-d607d7b8ed16.png)
![image](https://user-images.githubusercontent.com/12680312/36513310-2f7f78b4-17c3-11e8-9864-fbe92a095efd.png)

**Comment by TalAloni** [comment]
Hi Joshuaa,
1. The Readme file clearly states that port 445 is bound globally, and you must disable the Microsoft Server service completely if you wish to use this port. I suggest you read the Readme.md carefully.
2. Here is an (old) example that implements IFileSystem:
[](https://github.com/TalAloni/SMBLibrary/tree/9fe283762a21546be5787735a6fe719fa2e20172/SMBServer/DirectoryFileSystem)

**Comment by JoshuaaMichael** [comment]
Hello.

1. I see. I was unsure if there was a way around that limitation.
2. Thank you very much, I'll take a look

Thank you for your time, much appreciated.
