### ISSUE TITLE
SMB2Client login to share in azure file store results in STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by nortti** [TalAloni/SMBLibrary#52]
If I'm interpreting [MS Docs](https://docs.microsoft.com/en-us/azure/storage/common/storage-require-secure-transfer) correctly, SMB 2.1 client should work when secure transfer is disabled in the storage account settings.

> Connecting to an Azure File share over SMB without encryption fails when secure transfer is required for the storage account. Examples of insecure connections include those made over SMB 2.1, SMB 3.0 without encryption, or some versions of the Linux SMB client.

![image](https://user-images.githubusercontent.com/3278000/91439175-366aad80-e875-11ea-8595-3d69139ca9bc.png)
``` csharp
var client = new SMB2Client();
if (client.Connect(iPAddress, SMBTransportType.DirectTCPTransport)) {
    NTStatus status = client.Login(domain, userName, password); // These are correct.
    // status is NTStatus.STATUS_ACCESS_DENIED
}
```
[Wireshark dump](https://github.com/TalAloni/SMBLibrary/files/5136033/smb-dump.txt)

**Comment by TalAloni** [comment]
Hi,
Note that you provided a text file, not a WireShark capture.

Please provide a WireShark capture of a successful SMB2 connection an addition to the one created with the SMBLibrary that fails.
this way it will be possible to compare between the two.

**Comment by nortti** [comment]
Thanks for the quick reply. Using samba/smbclient with SMB2 yields the same error (SMB3 works). Mystery solved, azure file store is SMB3-only.

In reference to [Your comment on #51](https://github.com/TalAloni/SMBLibrary/issues/51#issuecomment-667149629), here you have a major product that requires SMB3.
