### ISSUE TITLE
Infinite loop in SMB1.FindInformation.ReadEntry causes memory full crash.

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#54]
In the public FindFileDirectoryInfo(byte[] buffer, int offset, bool isUnicode), the last entry of a query returns 0 in field NextEntryOffset :
            NextEntryOffset = LittleEndianReader.ReadUInt32(buffer, ref offset);

This causes the caller to enter an infinite loop and create over and over the same entry

        public FindInformationList(byte[] buffer, FindInformationLevel informationLevel, bool isUnicode)
        {
            int offset = 0;
            while (offset < buffer.Length)
            {
                FindInformation entry = FindInformation.ReadEntry(buffer, offset, informationLevel, isUnicode);
                this.Add(entry);
                offset += (int)entry.NextEntryOffset; <========= Last entry in the list returns 0
            }
        }

**Comment by JX75** [comment]
By the way I detected this when accessing a shared folder on Windows XP.

**Comment by TalAloni** [comment]
odd, buffer is not supposed to contain additional bytes after the last entry, can you please provide a packet capture?

**Comment by TalAloni** [comment]
Thanks, I was able to recreate, I pushed the fix to master.
