### ISSUE TITLE
Azure SMB3 support?

### ISSUE THREAD

**Issue by nddipiazza** [TalAloni/SMBLibrary#55]
I don't see anything about whether or not this project supports Azure SMB share.

Can you add something to the readme to say yay or nay? Thanks!

**Comment by TalAloni** [comment]
I think it's clear from the readme that only SMB 1.0 / 2.0 / 2.1 are supported.

**Comment by nddipiazza** [comment]
thanks! have a good one.

**Comment by nddipiazza** [comment]
@TalAloni just a quick follow-up do you have any plans to add SMB3? I think this is the only .NET core option for SMB2 and SMB3 has no .NET core support at all.

**Comment by TalAloni** [comment]
SMB 3.0 will probably happen at some point, It's not a lot of work, but I don't have too much free time right now.

**Comment by TalAloni** [comment]
SMB 3.0 support was added in v1.4.3, client now supports encryption.

**Comment by nddipiazza** [comment]
you're amazing! thanks.

**Comment by SimonGurney** [comment]
Thanks for sorting this out.  This library is awesome.  

How do you use the SMB3 client, do we just use the same SMB2 client against SMB3 systems?

**Comment by TalAloni** [comment]
Yes, you use the SMB2 client, if the server supports SMB3 it will be negotiated automatically.

**Comment by SimonGurney** [comment]
Thanks.  Also, will the SMBv2 client failback to v1 or do I need to connect with v2 and then if it's not successful try SMBv1?

**Comment by TalAloni** [comment]
No, the SMB2 client will not fallback to v1. if needed, you'll need to implement your own fallback mechanism and use the SMB1 client.

**Comment by darshija** [comment]
Does SMB Server is also supports SMB3 now?

**Comment by TalAloni** [comment]
The [readme](https://github.com/TalAloni/SMBLibrary) is pretty clear:
SMBLibrary is an open-source C# SMB 1.0/CIFS, SMB 2.0, SMB 2.1 and SMB 3.0 server and client implementation.

**Comment by darshija** [comment]
> The [readme](https://github.com/TalAloni/SMBLibrary) is pretty clear: SMBLibrary is an open-source C# SMB 1.0/CIFS, SMB 2.0, SMB 2.1 and SMB 3.0 server and client implementation.

Thank you! , Could you please let me know how we can enable it in SMB Server app, in windows app I cant see that option, Is it by making the last parameter to "True" in Server Start method ?

**Comment by TalAloni** [comment]
[darshija](https://github.com/darshija) This issue is about connecting an Azure SMB Share, this issue is resolved and closed.
