### ISSUE TITLE
Create file on smb drive

### ISSUE THREAD

**Issue by tone220601** [TalAloni/SMBLibrary#56]
Can you give an example of how to create a file from a Windows folder to a samba shared folder?

**Comment by TalAloni** [comment]
Added an example under ClientExamples.md: [Create a file and write to it](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md#create-a-file-and-write-to-it)

**Comment by tone220601** [comment]
Thank you, but I am getting file does not exist?

**Comment by TalAloni** [comment]
note that the directory you are trying to place the file into must exist
