### ISSUE TITLE
Gather files of Directory throws STATUS_NO_MORE_FILES

### ISSUE THREAD

**Issue by arjen1984** [TalAloni/SMBLibrary#58]
I am using your library for a .NET Core Projects in MacOS.
I was successfully able to connect to a share and gather all data folders. But when I specifically want to gather *.jpeg files it returns me STATUS_NO_MORE_FILES. Since I tested it with 1 jpeg file in a folder, I also tried it with 2 files, but it gave me the same problem.
Here is my code:
`_status = share.CreateFile(out handle, out fileStatus, "", AccessMask.SYNCHRONIZE | (AccessMask)DirectoryAccessMask.FILE_LIST_DIRECTORY, 0, ShareAccess.Read | ShareAccess.Write | ShareAccess.Delete, CreateDisposition.FILE_OPEN, CreateOptions.FILE_SYNCHRONOUS_IO_NONALERT | CreateOptions.FILE_DIRECTORY_FILE, null);
                //We can then retrieve the FileInformation
                _status = share.QueryDirectory(out List<QueryDirectoryFileInformation> files, handle, "*.jpeg", FileInformationClass.FileNamesInformation);
                //_status = share.QueryDirectory(out List<QueryDirectoryFileInformation> directories, handle, "*", FileInformationClass.FileDirectoryInformation);`

**Comment by TalAloni** [comment]
I would suggest you see how Windows perform this query (e.g. using cmd.exe and entering 'dir *.jpeg').
I'm closing for now since this is not an issue with the library (as far as I understand). if you're able to prove otherwise let me know.
