### ISSUE TITLE
Can I get the userName anywhere?

### ISSUE THREAD

**Issue by yls087412** [TalAloni/SMBLibrary#6]
Can you help me? I want to get the connect user in method "GetNetrShareEnumResponse " of file "SMBLibrary\Services\ServerService\ServerService.cs"? Is there a way to get the userName anywhere, such as "session" in asp.net.  
Thank you very much!

**Comment by TalAloni** [comment]
NTFileStore.CreateFile() has a 'SecurityContext' parameter containing the UserName property,
However, currently this parameter is not passed down to the server service named pipe ("srvsvc") that is responsible to return the list of shares.

Passing the SecurityContext / UserName down to the server service, and replacing the share list with the actual FileSystemShare objects, will allow the service to list different shares to different users (.e.g check permissions on each share and list only those with at least Read permission). shouldn't be too hard, let me know if you need help with it.

p.s. Note that the current implementation of simply listing all the shares is similar to the Windows implementation: the services are not context-dependent.

**Comment by yls087412** [comment]
Thank you very much!  I will try it later.
