### ISSUE TITLE
ADS

### ISSUE THREAD

**Issue by ncptbtptp** [TalAloni/SMBLibrary#60]
Hi, Does SMBLibrary support reading alternate data streams and ACL of a file, when used as a SMB client? Also, have we tested when the SMB client is used on Linux?

**Comment by TalAloni** [comment]
ADS - yes.
ACL - never tested this.
Yes, The SMB client is working under Linux.

**Comment by ncptbtptp** [comment]
Thanks TalAloni for confirming.
