### ISSUE TITLE
Using FileRenameInformationType2 for moving file --> file is empty/corrupted

### ISSUE THREAD

**Issue by GambaJo** [TalAloni/SMBLibrary#62]
I try to use the function SetFileInformation() and FileRenameInformationType2 to move a file in the same share. Like rename but with different target path.
The file moves from one folder to another, but it's empty (0 kB) and even corrupted (can't open it). I thought it would work like a rename file --> change the entry in the file system.

I know, I can copy the file and delete the source file, but I want to avoid this because I think it's slower.

**Comment by GambaJo** [comment]
@TalAloni 
I made a simplified example of my code:
`        static void Main(string[] args)
        {
            SMB2Client client = new SMB2Client();
            bool success = client.Connect(System.Net.IPAddress.Parse("172.18.119.6"), SMBTransportType.DirectTCPTransport);
            if (success)
            {
                NTStatus status = client.Login(String.Empty, "testtest", "#Test1234");
                if (status == NTStatus.STATUS_SUCCESS)
                {
                    SMB2FileStore fileStore = client.TreeConnect("UncPathTest", out status) as SMB2FileStore;
                    if (fileStore != null)
                    {
                        object fileHandle = null;
                        status = fileStore.CreateFile(out fileHandle, out FileStatus _, @"move1\test_move.pdf", AccessMask.GENERIC_ALL | AccessMask.SYNCHRONIZE, FileAttributes.Normal, ShareAccess.Write, CreateDisposition.FILE_OVERWRITE, CreateOptions.FILE_NON_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);
                        if (status == NTStatus.STATUS_SUCCESS)
                        {
                            status = fileStore.SetFileInformation(fileHandle, new FileRenameInformationType2()
                            {
                                FileName = @"move2\test_move.pdf"
                            });

                            status = fileStore.CloseFile(fileHandle);
                        }

                        fileStore.Disconnect();
                        client.Logoff();
                        client.Disconnect();
                    }
                }
            }
        }`

This example results in a corrupted file.

**Comment by TalAloni** [comment]
CreateDisposition.FILE_OVERWRITE means you are overwriting the original file as soon as you open it. for rename / move you need to use CreateDisposition.FILE_OPEN

**Comment by GambaJo** [comment]
Ah, this works. Thx!
It's difficult to find the right parameters. Also try to copy a file, but at the end I read the whole file (stream), create a new one and insert the content in te new file. Maybe there is a better way. Also for copy and move directories.
