### ISSUE TITLE
Unexpected exception thrown on SMB2Client.Login error 

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#65]
Hello

I get this exception when trying to call SMB2Client.Login to a local (127.0.0.1) Windows 10 share using SMBLibrary v1.4.3 with wrong credentials (I translated the error message from French)

System.InvalidCastException
  HResult=0x80004002
  Message=Impossible to perform a cast from objet of type 'SMBLibrary.SMB2.ErrorResponse' to type 'SMBLibrary.SMB2.SessionSetupResponse'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by TalAloni** [comment]
Thank you. The issue is now fixed in v1.4.6.

**Comment by JX75** [comment]
Damned, this was quick. Thanks.
