### ISSUE TITLE
DCE-RPC data stub encryption

### ISSUE THREAD

**Issue by CraigBT** [TalAloni/SMBLibrary#66]
Over the past several months I've been extending the code base to support SAMR and LSA RPC client calls. I'm now in the process of adding WINREG and SVCCTL support which uses RPC authentication level 6 (RPC_C_AUTHN_LEVEL_PKT_PRIVACY) for encrypting the RPC data stubs.

I do see that RequestPDU and ResponsePDU take the AuthLength and AuthInfo into account when building/parsing the RPC packets but I cannot find any code that creates the AuthInfo blob and encrypts/decrypts the RPC data stub. 

Is this currently support? If not, will it be?

Thanks for a great library!

**Comment by TalAloni** [comment]
Hi Craig,
Thanks, my strategy with the library is to implement / accept the minimum set of infrastructure that will allow you to extend it and add the necessary functionality that you need.
I'm not too familiar with RPC data encryption and it is currently not implemented, is it mandatory for WINREG and SVCCTL?
