### ISSUE TITLE
How to get the file list of the shared directory?

### ISSUE THREAD

**Issue by yika-aixi** [TalAloni/SMBLibrary#67]
Below is my test code, I don't know if it is correct, your client example is missing=-=

```C#
SMB2Client client = new SMB2Client();

client.Connect(IPAddress.Parse("192.168.0.185"), SMBTransportType.DirectTCPTransport);

var state = client.Login("","name", "pass");

if (state == NTStatus.STATUS_SUCCESS)
{
	var ls = client.ListShares(out state);
	
	if (state == NTStatus.STATUS_SUCCESS)
	{
		infos      = ls;
		_fileCount = infos.Length;

		var fs = client.TreeConnect("Voides", out state);
		
		if (state == NTStatus.STATUS_SUCCESS)
		{
			//todo Can I get the file list here?
		}
	}
	else
	{
		_fileCount = 0;
	}
}
```

**Comment by TalAloni** [comment]
[See ClientExamples.md - Connect to share and list files and directories](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md#connect-to-share-and-list-files-and-directories---smb2)

**Comment by yika-aixi** [comment]
> See [ClientExamples.md - Connect to share and list files and directories](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md#connect-to-share-and-list-files-and-directories---smb2)
thanks
