### ISSUE TITLE
Creating Directories with Files

### ISSUE THREAD

**Issue by rebelweb** [TalAloni/SMBLibrary#70]
Hello, I want to start off by thanking you for your hard work.

I am having a problem where I need to create directories for files to be stored. I tried adding the path when I create the file but I get a STATUS_OBJECT_PATH_NOT_FOUND. IS there an option or separate command to create the directories?

I am upgrading some legacy code stores file in a pattern like so "image/{id}/{file_name}"

**Comment by TalAloni** [comment]
Hi Ryan, Create a directory and storing a file in this new directory are two separate operations, both are performed using the CreateFile method, but each has its own parameters. (e.g. CreateOptions.FILE_DIRECTORY_FILE and CreateOptions.FILE_NON_DIRECTORY_FILE)
