### ISSUE TITLE
2gb file limit

### ISSUE THREAD

**Issue by dlukowski-smarsh** [TalAloni/SMBLibrary#71]
I'm attempting to retrieve large files from an SMB share returns an error.  The server is a windows 2019 server and I have no problem retrieving the files from a UNC path in Windows Explorer.

When attempting to retrieve the same file though SMBLibrary (SMB2FileStore.ReadFile) I encounter an error:

    ExceptionMessage: "MESSAGE:Unable to read file.  
        HASH:65909363 
        HOST:qa-vault-01.devqa.com
        SHARE:QA-Fileserver 
        IS_CONNECTED:False 
        FILE:\\qa-vault-01.devqa.com\QA-Fileserver\A\large_files\2gb.txt"
    SmbStatus: "STATUS_INVALID_PARAMETER"

This happens when chunking the 2gb file into the output stream.
```
                while (read)
                {
                    _clientStatus = _smb2FileStore.ReadFile(out var chunk, _fileHandle, start, chunkSize);

                    if (_clientStatus != NTStatus.STATUS_SUCCESS && _clientStatus != NTStatus.STATUS_END_OF_FILE)
                    {
                        string errorMessage =
                            $"Unable to read file.\n HASH:{InstanceHash}\n HOST:{Key}\n SHARE:{Share}\n IS_CONNECTED:{IsConnected}\n FILE:\\\\{_host}\\{_share}\\{pathToFile}";
                        _logger.LogWarning(errorMessage);
                        throw new SmbConnectionException(errorMessage, _host, _share, _domain, _username, 502, _clientStatus.ToString());
                    }

                    yield return chunk;

                    start += chunkSize;
                    if (chunk == null || chunk.Length < chunkSize)
                    {
                        read = false;
                    }
                }
```

The container this is running in is using a Debian 10 OS with Linux Kernel 4.19.

**Is there a 2gb limitation with SMBLibrary?  Is there a way around it?**

Thanks for all your work on this project.

**Comment by TalAloni** [comment]
Hi,
You must not read more bytes in a ReadFile request than the maximum negotiated between the client and the server (client.MaxReadSize)

**Comment by dlukowski-smarsh** [comment]
How do I change the maximum negotiated bytes?

I see a hard coded limit on line 28 of SMB2Client.
`public static readonly uint ClientMaxReadSize = 1048576;`

In my example above, the chunkSize  is 65536 so I'm not requesting more then 1048576. If I follow correctly.

This code works fine for every file up to 2gb.  Any file over that limit will return the "STATUS_INVALID_PARAMETER" error.

**Comment by TalAloni** [comment]
Sorry, I misunderstood earlier.
Did you try running the code sample provided in [Client Examples](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md#read-large-file-to-its-end)?
I'm not familiar with any 2GB limit, it could be the result of a bug in your code (you only provided small part so it's hard to tell).

**Comment by dlukowski-smarsh** [comment]
I wrote the simplest retriever I could and have no issues retrieving a 2gb file on Windows.  However, my application is running on debian 10 and I have not been able to validate functionality there yet.

For the record here is the Console Application.

```
using System;
using System.IO;
using System.Net;
using SMBLibrary;
using SMBLibrary.Client;

namespace SMB2FileTransfer
{
    class Program
    {
        static void Main(string[] args)
        {
			string host = "qa-vault-01.devqa.com";
			string share = "QA-Fileserver";
			string filePath = "A\\large_files";
			string fileName = "3gb.txt";
			string domain = "devqa.com";
			string username = "USERNAME";
			string password = "PASSWORD";

			SMB2Client client = new SMB2Client();
			SMB2FileStore fileStore = null;
			NTStatus status = NTStatus.STATUS_INVALID_SMB;
			object fileHandle = new object();
			FileStatus fileStatus = FileStatus.FILE_DOES_NOT_EXIST;
			bool connected = false;

			connected = client.Connect(Dns.GetHostAddresses(host)[0], SMBTransportType.DirectTCPTransport);
			if (connected)
			{
				status = client.Login(domain, username, password);
				if (status == NTStatus.STATUS_SUCCESS)
				{
					fileStore = client.TreeConnect(share, out status) as SMB2FileStore;
					if (fileStore == null)
					{
						Console.WriteLine($"Could not connect to Share:{share}");
						Environment.Exit(1);
					}
				}
				else
				{
					Console.WriteLine($"Could not login to Host:{host}");
					Environment.Exit(1);
				}

			}
			else
			{
				Console.WriteLine($"Could not connect to host:{host}");
				Environment.Exit(1);
			}


			status = fileStore.CreateFile(out fileHandle, out fileStatus, $"{filePath}\\{fileName}", AccessMask.GENERIC_READ, SMBLibrary.FileAttributes.Normal, ShareAccess.Read, CreateDisposition.FILE_OPEN, CreateOptions.FILE_NON_DIRECTORY_FILE, null);

			if (status == NTStatus.STATUS_SUCCESS)
			{
				FileStream stream = new FileStream($"C:\\tmp\\{fileName}", FileMode.OpenOrCreate);
				byte[] data;
				long bytesRead = 0;
				while (true)
				{
					status = fileStore.ReadFile(out data, fileHandle, bytesRead, 65536);
					if (status != NTStatus.STATUS_SUCCESS && status != NTStatus.STATUS_END_OF_FILE)
					{
						throw new Exception("Failed to read from file");
					}

					if (status == NTStatus.STATUS_END_OF_FILE || data.Length == 0)
					{
						break;
					}
					if (bytesRead % 10485760 == 0)
						Console.WriteLine($"Read {bytesRead} bytes");
					bytesRead += data.Length;
					stream.Write(data, 0, data.Length);
				}
			}
			status = fileStore.CloseFile(fileHandle);
			status = fileStore.Disconnect();
		}
    }
}
```

**Comment by TalAloni** [comment]
Are you saying the same code works and Windows and Fails on Debian?

**Comment by rodion-m** [comment]
@dlukowski-smarsh Hi! Have you solved this issue so far?

We also ran into the same problem.

**Comment by TalAloni** [comment]
@rodion-m 
There is no 2 GB limit in the library, if there is an issue it originates elsewhere. (likely some issue with the code using the library)

**Comment by rodion-m** [comment]
I've found the problem. I passed negative offset to `public NTStatus WriteFile(out int numberOfBytesWritten, object handle, long offset, byte[] data)`. So, I have a suggestion — I believe that we should add parameters validation to all public members of SMBLibrary (like not null, in the range, etc.) to fail fast. @TalAloni what do you think?
