### ISSUE TITLE
A call to SMB1Client.Connect never returns.

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#72]
Hello.

I’m testing different scenarios and I have a spotted a strange behaviour on SMB1Client.Connect.

The client program is calling SMB1Client.Connect using its own IP (not the loopback) on Windows 10. 

If the transport is TCP (port 445) the call returns false, but if the transport is NetBios (port 139) the call just keeps waiting forever.

Since SMB1 is not supported I see an exception in both cases (System.Net.Sockets.SocketException: 'An existing connection was forcibly closed by the remote host'), but it doesn't unblock the call if the port is 139.

The version is 1.4.6, downloaded with NuGet.

**Comment by TalAloni** [comment]
Does this happen only on localhost? or can you reproduce it when connecting to a remote IP as well?

**Comment by JX75** [comment]
The call does return when :
- I try to connect to a foreign IP address
- I try to connect with my own station (Windows 10 station) using 127.0.0.1

The call does not return when :
- I try to connect to my own station using its IP
- I try to connect to my own station using its hostname

**Comment by rebelweb** [comment]
You may want to check Turn Windows Features On/Off and ensure SMB1 is enabled. I do believe it was recently disabled, also that setting can be controlled via a group policy if the machine is a part of a domain network.

**Comment by JX75** [comment]
@rebelweb The problem is not that SMB1 is disabled - I'm totally OK with that. The problem is that the connection function doesn't return.

**Comment by TalAloni** [comment]
JX75 - according to the data you provided and the connection logic this is related to OS behavior and not really a bug with the library. I don't have anything to do on this matter.
