### ISSUE TITLE
Make client connections and file stores disposable.

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#73]
Not a bug, just a suggestion to make interfaces (especially ISMBFileStore and ISMBClient) disposable and to disconnect connections when disposed.

**Comment by TalAloni** [comment]
Thanks for the suggestion.

**Comment by SonnyX** [comment]
@JX75 You might want to check out my fork of SMBLibrary: https://github.com/SonnyX/SMB-Client which is also available on Nuget

**Comment by mungojam** [comment]
@TalAloni did you decide not to do this?
