### ISSUE TITLE
Status code missing in enum.

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#74]
In some cases (I don't remember which, maybe SMB1) I get a return status of 3221225578 (value not in enum) instead of the expected SMBLibrary.NTStatus.STATUS_LOGON_FAILURE after a call to Connect with wrong credentials.

**Comment by JX75** [comment]
It looks like STATUS_WRONG_PASSWORD (0xC000006A)

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/8f11e0f3-d545-46cc-97e6-f00569e3e1bc

**Comment by TalAloni** [comment]
Added
