### ISSUE TITLE
Delete folder returns STATUS_DIRECTORY_NOT_EMPTY --> need to delete folder and all files in it like with force delete

### ISSUE THREAD

**Issue by GambaJo** [TalAloni/SMBLibrary#75]
Hey, it's me again ;)

I try to delete  a folder, but there is a file in this folder. So I get the NTStatus = STATUS_DIRECTORY_NOT_EMPTY. Is there a way to delete the folder and its files at once? Or have I to delete first all the files in the folder and finally the folder?
I found an enum with the element "ForceSharedDelete". But I didn't found, where I could set it.

Here my example code:
`static void DeleteFolder()
{
	SMB2Client client = new SMB2Client();
	bool success = client.Connect(System.Net.IPAddress.Parse("172.21.67.129"), SMBTransportType.DirectTCPTransport);
	if (success)
	{
		NTStatus status = client.Login(String.Empty, "testtest", "#Test1234");
		if (status == NTStatus.STATUS_SUCCESS)
		{
			SMB2FileStore fileStore = client.TreeConnect("UncPathTest", out status) as SMB2FileStore;
			if (fileStore != null)
			{
				status = fileStore.CreateFile(out object fileHandle, out FileStatus fileStatus, "ffc26c1c-6a3b-4519-901a-e910cf440f69", AccessMask.GENERIC_WRITE | AccessMask.DELETE | AccessMask.SYNCHRONIZE, SMBLibrary.FileAttributes.Directory, ShareAccess.Delete, CreateDisposition.FILE_OPEN, CreateOptions.FILE_DIRECTORY_FILE | CreateOptions.FILE_SYNCHRONOUS_IO_ALERT, null);
				if (status == NTStatus.STATUS_SUCCESS)
				{
					status = fileStore.SetFileInformation(fileHandle, new FileDispositionInformation()
					{ 
						DeletePending = true
					});

					System.Diagnostics.Debug.WriteLine(status);

					fileStore.CloseFile(fileHandle);
				}
				fileStore.Disconnect();
			}
			client.Logoff();
		}
		client.Disconnect();
	}
}`

**Comment by GambaJo** [comment]
Sorry, I'm to stupid to insert code here properly.

**Comment by TalAloni** [comment]
AFAIK you must delete the folder content before you can delete the folder. this is how Windows does it as well.

**Comment by GambaJo** [comment]
Ok, thx.
