### ISSUE TITLE
Is there a method, that can copy/read folders with it's contents recursively ?

### ISSUE THREAD

**Issue by Pfannaa** [TalAloni/SMBLibrary#79]
More of a question than an issue.

Or do i have to enter every folder and read every file on it's own ?

**Comment by TalAloni** [comment]
Usually a copy is performed by the client by reading and writing the files in the folder you wish to copy.
Server-side copy is a more exotic feature that is not widely supported (Windows 7 / Server 2008 do not support it for example), 
If you wish to learn more about server-side copy - look into FSCTL_SRV_COPYCHUNK.

**Comment by Pfannaa** [comment]
Thanks for the info. But i was thinking of a "Local to Remote" or "Client to Server", not a server sided copy.
But that answers my question. I have to read every file on it's own and create the specific folder on the remote computer.
Thanks a lot!

**Comment by maciejstepie** [comment]
> Usually a copy is performed by the client by reading and writing the files in the folder you wish to copy. Server-side copy is a more exotic feature that is not widely supported (Windows 7 / Server 2008 do not support it for example), If you wish to learn more about server-side copy - look into FSCTL_SRV_COPYCHUNK.

Do you have amybe any example how to handle server side copy ?

**Comment by TalAloni** [comment]
I don't. sorry.
