### ISSUE TITLE
Sign assemblies 

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#80]
Loading the SMBClient assembly from a program using signing with a strong name key file fails because SMBClient itself is not signed (in C# : project properties / signing / sign the assembly).

The exception is:

`System.IO.FileLoadException: 'Could not load file or assembly 'SMBLibrary, Version=1.4.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'
`

**Comment by TalAloni** [comment]
I can definitely consider signing the assembly with a strong name, but can you make the case why you couldn't do this after the fact as part of your build process?

**Comment by JX75** [comment]
Users of my application are losing their settings at each upgrade because the settings path depends on the exe’s location, which varies in my case. I found today that signing my own assemblies fixed the problem since the “Evidence type” goes from “URL”  “to Strong Name”. It works fine except that all sub-assemblies also have to be signed, which is not the case for SMBLibrary.

Here is a short discussion of my user settings issue:
https://www.codeproject.com/Questions/200550/Net-user-config-path-Hash

As to signing SMBLibrary myself it seems possible but it makes the integration of new versions of SMBLibrary (which is so simple with NuGet) more difficult. As far as I understand (see below link) and unless there is anothe way I have to create a signed copy of the DLL whenever I upgrade and then reference it in my project. It’s not really a build step that I could automate.

https://www.codeproject.com/Tips/341645/Referenced-assembly-does-not-have-a-strong-name

**Comment by TalAloni** [comment]
There are other ways that can be automated, once you have an updated build process that sign the library before linking then it will not be a problem to update the library, it will be covered by your build process.
while this will take some work and learning on your part to set up, it's definitely can be done.

**Comment by JX75** [comment]
Well, I can try.

**Comment by JX75** [comment]
I added Brutal Dev’s “Strong Name Signer” NuGet package in my solution and added a block to the project file that automagically signs unsigned assemblies as defined below. It seems to work and it’s simple to do.

https://github.com/brutaldev/StrongNameSigner/

**Comment by TalAloni** [comment]
Nice! Thanks for sharing!
