### ISSUE TITLE
Is there a way to obtain server credits?

### ISSUE THREAD

**Issue by jdenicola** [TalAloni/SMBLibrary#81]
Hi!
I'm using in C# your library as SMB client, obtaning files from a server and sending to a collection of servers. So far so good.
I'm logging onto a SMB server and making several transactions until server credits are depleted. So I get a 'Not enough credits' exception.
So, I can get more credits 'stalling' my application, like adding 1 second sleep between transactions, or reconnecting to the server, but I would like to handle this event so I can reset my credits counter.

Is there any method for getting the credit value, or obtaining more credits from the SMB server?

More info: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/46256e72-b361-4d73-ac7d-d47c04b32e4b

Thanks in advance.-
Juan

**Comment by TalAloni** [comment]
It is my experience that when users have issues with credit it is due to usage pattern that is either incorrect or not supported.
Each client should not perform more than one concurrent operation. (it is not supported ATM).

**Comment by jdenicola** [comment]
Great then.
I was re-using the connection established for doing several operations such as downloading a list of files and uploading them to same server. 
This 'source' server is the only one having this credit issue when performing write operations.

Thanks!!!
