### ISSUE TITLE
RejectUnencryptedAccess=true --> access denied

### ISSUE THREAD

**Issue by GambaJo** [TalAloni/SMBLibrary#83]
Hey guys, when the option [RejectUnencryptedAccess](https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-security) is set to true in Windows Server, I can't access to the share.
What can I do to gat access to shares with this option?

**Comment by TalAloni** [comment]
How exactly are you trying to access the share?
Are you using the latest version of the library?
Please provide a code example.

**Comment by GambaJo** [comment]
I'm using SMBLibraryLite 1.4.3.2 at the moment.

`using SMBLibrary;
using SMBLibrary.Client;
using System;
using System.IO;

namespace TestSMBLibrary
{
class Program
{
static string FilePath = @"C:\temp\test.pdf";

    static void Main(string[] args)
    {
        UploadFile();
    }

    static void UploadFile()
    {
        SMB2Client client = new SMB2Client();
        bool success = client.Connect(System.Net.IPAddress.Parse("172.21.67.129"), SMBTransportType.DirectTCPTransport);
        if (success)
        {
            NTStatus status = client.Login(String.Empty, "testtest", "#Test1234");
            if (status == NTStatus.STATUS_SUCCESS)
            {
                SMB2FileStore fileStore = client.TreeConnect("UncPathTest", out status) as SMB2FileStore;
                if (fileStore != null)
                {
                    status = fileStore.CreateFile(out object fileHandle, out FileStatus fileStatus, Path.GetFileName(FilePath), AccessMask.SYNCHRONIZE | AccessMask.GENERIC_WRITE, SMBLibrary.FileAttributes.Normal, ShareAccess.None, CreateDisposition.FILE_CREATE, CreateOptions.FILE_SYNCHRONOUS_IO_ALERT | CreateOptions.FILE_NON_DIRECTORY_FILE, null);
                    if (status == NTStatus.STATUS_SUCCESS)
                    {
                        long bytesWrittenTotal = 0;
                        byte[] fileArray = File.ReadAllBytes(FilePath);
                        do
                        {
                            long chunkArrayLength = fileArray.Length - bytesWrittenTotal < client.MaxWriteSize ? fileArray.Length - bytesWrittenTotal : client.MaxWriteSize;
                            byte[] chunkArray = new byte[chunkArrayLength];
                            Array.Copy(fileArray, bytesWrittenTotal, chunkArray, 0, chunkArrayLength);
                            status = fileStore.WriteFile(out int bytesWrittenChunk, fileHandle, bytesWrittenTotal, chunkArray);
                            if(status != NTStatus.STATUS_SUCCESS)
                            {
                                throw new Exception("Failed to write file");
                            }
                            bytesWrittenTotal += bytesWrittenChunk;
                        } while (bytesWrittenTotal < fileArray.Length);

                        fileStore.CloseFile(fileHandle);
                    }
                    fileStore.Disconnect();
                }
                client.Logoff();
            }
            client.Disconnect();
        }
    }
}

}`

**Comment by TalAloni** [comment]
This is not the place for SMBLibraryLite issues.
If you want to open an issue with this project - please verify that the issue occurs with the latest version of this project's library before opening an issue.

**Comment by GambaJo** [comment]
[SMBLibraryLite](https://github.com/jordanlytle/SMBLibrary) is only a fork of this project. I can't open issues there:
![grafik](https://user-images.githubusercontent.com/1378907/121710232-b054e600-cad9-11eb-937a-cdc50452f540.png).

**Comment by TalAloni** [comment]
note that it's a one-year old fork.
SMB 3.0 (which is what you need) was only added later.
If you want to open an issue with this project - please verify that the issue occurs with the latest version of this project's library before opening an issue.
