### ISSUE TITLE
Exception in SMB1.NegotiateResponse() constructor when connecting to a NT4 share.

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#84]
As on can see in the capture, the challenge field is the last one in the Negotiate Protocol response from the NT4 station.

The SMB1.NegotiateResponse() constructor tries to read DomainName and ServerName past the end of the SMBData buffer, which causes an exception.

I corrected code as follows, which fixes this issue (unfortunately I have another one):
```
            int dataOffset = 0;
            Challenge = ByteReader.ReadBytes(this.SMBData, ref dataOffset, ChallengeLength);
            // [MS-CIFS] <90> Padding is not added before DomainName
            // DomainName and ServerName are always in Unicode
            if (dataOffset < SMBData.Length)
                DomainName = SMB1Helper.ReadSMBString(this.SMBData, ref dataOffset, true);
            if (dataOffset < SMBData.Length)
                ServerName = SMB1Helper.ReadSMBString(this.SMBData, ref dataOffset, true);

```

[negotiation.zip](https://github.com/TalAloni/SMBLibrary/files/6629938/negotiation.zip)

**Comment by TalAloni** [comment]
When the NT Lan Manager dialect is used, domain name should be present:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/a4229e1a-8a4e-489a-a2eb-11b7f360e60c

Which dialect are you using? AFAIK NT4 on latest updates should be able to use the NT Lan Manager dialect.
