### ISSUE TITLE
SMB1 connection impossible to NT4: NTSMB, RpcRemoteApi and NTStatusCode capabilities not supported

### ISSUE THREAD

**Issue by JX75** [TalAloni/SMBLibrary#85]
Hello again,

SMB1Client.HegotiateDialect() returns false when connecting a a NT4 server because NTSMB, RpcRemoteApi and NTStatusCode capabilities are not supported (as can be seen in the capture file).

What are the features that make those capabilities compulsory for a connection and do you think it would be feasible to make those features optional?

[negotiation.zip](https://github.com/TalAloni/SMBLibrary/files/6630004/negotiation.zip)

**Comment by TalAloni** [comment]
it's too much trouble to support servers that do not support NTStatusCode.
IIRC even NT4 (on the latest updates) support NTStatusCode.
