### ISSUE TITLE
Windows Cluster Shared Volume - Multiple Aliases

### ISSUE THREAD

**Issue by pedrosakuma** [TalAloni/SMBLibrary#88]
When connecting with a clustered shared volume, is required to be explicit in the host name when using TreeConnect or ListShares (ServerName). 

Using Ip returns Cluster Host shares instead of share provided by cluster.

**Comment by TalAloni** [comment]
Thanks,
So what you are saying is that the TreeConnect method needs an overload that will allow you to set the server name?
And in addition ListShares needs the same overload and should use the overloaded TreeConnect?

**Comment by pedrosakuma** [comment]
Yes, i think that would solve my problem. 
But i am not sure if SMB1 would support that change to TreeConnect. 
Probably this TreeConnect overload will not be a part of the ISMBClient interface.

**Comment by TalAloni** [comment]
I'll try to install and test such an environment when I have time.

**Comment by TalAloni** [comment]
Done. Merged to Master.
Thanks!

**Comment by TalAloni** [comment]
The new overload is included in SMBLibrary v1.4.6.2
