### ISSUE TITLE
How to upload large file 

### ISSUE THREAD

**Issue by rajatjhaexate** [TalAloni/SMBLibrary#89]
How to upload file in SMB please suggest any examples

**Comment by TalAloni** [comment]
it's very similar to "Read large file to its end" from [ClientExamples](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md) with write instead of read.

**Comment by TalAloni** [comment]
Added an example to [Client Examples](https://github.com/TalAloni/SMBLibrary/blob/master/ClientExamples.md#write-a-large-file)
