### ISSUE TITLE
How to create directory 

### ISSUE THREAD

**Issue by rajatjhaexate** [TalAloni/SMBLibrary#90]
NTStatus status = sMBFileStore.CreateFile(out directoryHandle, out fileStatus, relativePath, AccessMask.WRITE_OWNER, SMBLibrary.FileAttributes.Directory, ShareAccess.Read | ShareAccess.Write | ShareAccess.Delete, CreateDisposition.FILE_CREATE, CreateOptions.FILE_NON_DIRECTORY_FILE, null);

I used this code return Object path not found

**Comment by TalAloni** [comment]
CreateOptions.FILE_NON_DIRECTORY_FILE is wrong here. to create a directory you should use CreateOptions.FILE_DIRECTORY_FILE

**Comment by rajatjhaexate** [comment]
Thank you but I used this also 
My Path this Upload\\_csv\\2\\in 
so the upload folder is already created but csv\\2\\in is not created 
show same Object path not found

**Comment by TalAloni** [comment]
You cannot create 3 directories in one command. you must create them one by one.

**Comment by rajatjhaexate** [comment]
Thank you It's working 😄
