### ISSUE TITLE
How to use FileSystem-copyfile

### ISSUE THREAD

**Issue by M-Beezy** [TalAloni/SMBLibrary#94]
Hi, can you please give an example of how to use FileSystem.copyfile?
I just want to copy files from a local PC to a Server.
I tried this (translated it to vb.net):
`
       Dim client As SMB2Client = New SMB2Client()
            Dim isConnected As Boolean = client.Connect(IPAddress.Parse("10.100.130.221"), SMBTransportType.DirectTCPTransport)

            If isConnected Then
                Dim status As NTStatus = client.Login(_domain, _username, _passwordStr)

                If status = NTStatus.STATUS_SUCCESS Then
                    Dim shares As List(Of String) = client.ListShares(status)
                End If
            End If
`
I want to copy a file to 10.200.120.123\folder1\folder2\folder3\myfile.pdf.

Please Advice. 
Thanks!

**Comment by TalAloni** [comment]
Hi,
You need to read the file stream and write it to the server using WriteFile, there are already several issues detailing how to perform this operation.
