### ISSUE TITLE
File status STATUS_SHARING_VIOLATION when read & write 

### ISSUE THREAD

**Issue by rajatjhaexate** [TalAloni/SMBLibrary#95]
please help with this status issue. so the situation is when we write a file in smb file share then the file connection does not disconnect properly and we open this file again to show this error. how to handle this error. 
Thank you

**Comment by TalAloni** [comment]
You should make sure you release all resources and disconnect in an orderly fashion.
Otherwise you have to wait for the server to release those resources.
