### ISSUE TITLE
When writing a file, the offset cannot be used normally

### ISSUE THREAD

**Issue by bonnlee2016** [TalAloni/SMBLibrary#97]
Hi  TalAloni,
     Last time I asked you how to use file write stream.  you told me to use ReadFile and WriteFile when connecting to an SMB server and wishing to read / write.   But  there was a problem,  when i set the offset of  ISMBFileStore.WriteFile,  the result is that all bytes before the offset become null.   

So after setting the offset, I need to append data after the current offset,  not to completing null before the offset.
I don't want to write a full amount of files. If the file is large, I need to write incrementally, that is, write in stream.

Thank U.

**Comment by TalAloni** [comment]
Make sure you open the file using the appropriate flags to avoid existing content from being modified.
This question is not specific to the library but to how the Win32 file-access API works.
