### ISSUE TITLE
STATUS_BAD_NETWORK_NAME while trying to connect

### ISSUE THREAD

**Issue by truten** [TalAloni/SMBLibrary#98]
Hello,

First of all thanks for the library!
Secondly I would like to ask a question.
I have checked the example code but I am still having issues while trying to connect to a Windows Server share.

My structure is the following: \\192.168.1.2\masterfolder\subfolder1\subfolder2
When my folder  is set to only "masterfolder" it's working and I can list directory and write file. 
For example like: \\192.168.1.2\masterfolder\NewFile.txt
When i try to connect directly to the a subfolder i get STATUS_BAD_NETWORK_NAME.
I have tried to format the destination in different modes ("masterfolder/subfolder", "masterfolder//subfolder", "masterfolder\\subfolder" or "masterfolder//subfolder") but I'm still getting the bad network name status.

I think that it must be something easy but I cannot figure it out.
Could you please point me in what I am doing wrong?
Many thanks.

```
SMB2Client client = new SMB2Client();
            bool isConnected = client.Connect(IPAddress.Parse("192.168.1.2"), SMBTransportType.DirectTCPTransport);
            if (isConnected)
            {
                NTStatus status = client.Login("NFSdomain", "NFSusername", "NFSpassword");
                string NFSfolder = "masterfolder\\subfolder";
                if (status == NTStatus.STATUS_SUCCESS)
                {
                    List<string> shares = client.ListShares(out status);
                }
                ISMBFileStore fileStore = client.TreeConnect(NFSfolder, out status);              
                if (status == NTStatus.STATUS_SUCCESS)
                {
//do things
}
}```

**Comment by TalAloni** [comment]
'masterfolder' is the share name.
'masterfolder\subfolder1' is not a share name, 'subfolder1' is a directory under the 'masterfolder'
You are attempting to access a subdirectory in the same way you connect to a share - which is incorrect.
First you connect to the share - then you access files and directories.

**Comment by truten** [comment]
Hi. Thanks for the heads up. In the end combining your response, the examples and this answer (https://github.com/TalAloni/SMBLibrary/issues/9)  i was able to do it.

I am now having some issues with file writing but i'll check it.
