### ISSUE TITLE
status =3221226071

### ISSUE THREAD

**Issue by tokotech** [TalAloni/SMBLibrary#99]
trying to read form a subfolder returns this status code : 3221226071
What does that mean ?

    var fileStore = client.TreeConnect("MyShare", out status);
    if (status == NTStatus.STATUS_SUCCESS)
    {
            var filePath = "MySubFolder"
            status = fileStore.CreateFile(out var directoryHandle,
                                                      out fileStatus,
                                                      filePath,
                                                      AccessMask.GENERIC_READ,
                                                      FileAttributes.Directory | FileAttributes.ReparsePoint,
                                                      ShareAccess.Read,
                                                      CreateDisposition.FILE_OPEN,
                                                      CreateOptions.FILE_DIRECTORY_FILE,
                                                      null);

**Comment by TalAloni** [comment]
3221226071  = 0xC0000257 = STATUS_PATH_NOT_COVERED
Usually means "DFS pathname not on local server"
